### ISSUE TITLE
[SOLVED] AttributeError: 'FaceSwapScript' object has no attribute 'save_original'

### ISSUE THREAD

**Issue by andypotato** [Gourieff/sd-webui-reactor#100]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Face swap will crash when used via API

### Steps to reproduce the problem

Try creating any face swap via A1111 API with Reactor as alwayson_script

### Sysinfo

Debian Linux / 3080ti GPU

### Relevant console log

```Shell
2023-09-19T03:45:48.096171834-04:00 *** Error running postprocess_batch: /workspace/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_faceswap.py
2023-09-19T03:45:48.097464584-04:00     Traceback (most recent call last):
2023-09-19T03:45:48.097468218-04:00       File "/workspace/stable-diffusion-webui/modules/scripts.py", line 659, in postprocess_batch
2023-09-19T03:45:48.097469230-04:00         script.postprocess_batch(p, *script_args, images=images, **kwargs)
2023-09-19T03:45:48.097470051-04:00       File "/workspace/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_faceswap.py", line 344, in postprocess_batch
2023-09-19T03:45:48.097470932-04:00         if self.enable and not self.save_original:
2023-09-19T03:45:48.097471803-04:00     AttributeError: 'FaceSwapScript' object has no attribute 'save_original'
```
```


### Additional information

_No response_

**Comment by Gourieff** [comment]
Please look at this example https://github.com/Gourieff/sd-webui-reactor/blob/main/example/api_example.py
If you send all the required arguments, there will be no errors

**Comment by andypotato** [comment]
Shouldn't each parameter have a default argument? In this case parameter 16 should default to "False", right?

Until now I was only sending the first two parameters and that worked just fine. The error started appearing after I updated to the latest version. It seems the default value is not set any longer?

**Comment by Gourieff** [comment]
Please provide your workflow
txt2img or img2img?
single image or batch?

**Comment by andypotato** [comment]
My workflow is txt2img with a single image. A1111 WebUI version is 1.6.0.

The extension worked without problems before I updated today. My previous version before the update was b2ace90b7296c2d5fb29ab133737ced1cf152a63. When I downgrade to this version, it works normally.

**Comment by Gourieff** [comment]
I've just tried and cannot repeat this bug
No any errors
I've even tried API without the "#16" argument - no errors
Works pretty good

I can recommend you to delete the "sd-webui-reactor" folder from the "extensions" directory and `git clone` this repo again
Perhaps, smth went wrong during "git pull" when you updated it earlier

**Comment by Dutch77** [comment]
I have clear repo and everything newly installed and I have the same error in UI. Weird is that same docker image works on another machine. Really weird

```
[API](http://localhost:8080/docs)  •  [Github](https://github.com/AUTOMATIC1111/stable-diffusion-webui)  •  [Gradio](https://gradio.app/)  •  [Startup profile](http://localhost:8080/#)  •  [Reload UI](http://localhost:8080/)
version: [v1.6.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4)  •  python: 3.10.13  •  torch: 2.0.1+cu117  •  xformers: 0.0.21  •  gradio: 3.41.2  •  checkpoint: [0aecbcfa2c]
```

```
 *** Error running postprocess_batch: /workspace/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_faceswap.py
app_1  |     Traceback (most recent call last):
app_1  |       File "/workspace/stable-diffusion-webui/modules/scripts.py", line 659, in postprocess_batch
app_1  |         script.postprocess_batch(p, *script_args, images=images, **kwargs)
app_1  |       File "/workspace/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_faceswap.py", line 344, in postprocess_batch
app_1  |         if self.enable and not self.save_original:
app_1  |     AttributeError: 'FaceSwapScript' object has no attribute 'save_original'
app_1  | 
app_1  | ---
app_1  | *** Error running postprocess_image: /workspace/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_faceswap.py
app_1  |     Traceback (most recent call last):
app_1  |       File "/workspace/stable-diffusion-webui/modules/scripts.py", line 675, in postprocess_image
app_1  |         script.postprocess_image(p, pp, *script_args)
app_1  |       File "/workspace/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_faceswap.py", line 348, in postprocess_image
app_1  |         if self.enable and self.swap_in_generated and not self.save_original:
app_1  |     AttributeError: 'FaceSwapScript' object has no attribute 'save_original'
app_1  | 
app_1  | ---
app_1  | *** Error running postprocess: /workspace/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_faceswap.py
app_1  |     Traceback (most recent call last):
app_1  |       File "/workspace/stable-diffusion-webui/modules/scripts.py", line 651, in postprocess
app_1  |         script.postprocess(p, processed, *script_args)
app_1  |       File "/workspace/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_faceswap.py", line 287, in postprocess
app_1  |         if self.save_original:
app_1  |     AttributeError: 'FaceSwapScript' object has no attribute 'save_original'
app_1  | 
app_1  | ---

```

**Comment by andypotato** [comment]
That's interesting. I've always deployed via docker and didn't realize the inswapper model didn't get downloaded. I triggered a manual download of the model and it works now.

Thank you both for looking into this, it helped a lot!
