### ISSUE TITLE
[SOLVED] AttributeError: 'FaceSwapScript' object has no attribute 'enable'

### ISSUE THREAD

**Issue by greasemonkey2603** [Gourieff/sd-webui-reactor#104]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

When im running reactor in img 2 img, the image is being generated without face swapping.

### Steps to reproduce the problem

1. Go to img2img
2. Upload source image and image to be face swapped
3. Hit generate
4. cmd log gives error 
5. Image generates without faceswap

### Sysinfo

WINDOWS 11, GTX 1650, 16 GB RAM, 	AMD Ryzen 5 4600H with Radeon Graphics 

### Relevant console log

```Shell
*** Error running process: D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
    TypeError: FaceSwapScript.process() missing 17 required positional arguments: 'img', 'enable', 'source_faces_index', 'faces_index', 'model', 'face_restorer_name', 'face_restorer_visibility', 'restore_first', 'upscaler_name', 'upscaler_scale', 'upscaler_visibility', 'swap_in_source', 'swap_in_generated', 'console_logging_level', 'gender_source', 'gender_target', and 'save_original'

---
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:21<00:00, 21.68s/it]
*** Error running postprocess_batch: D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 659, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
      File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 346, in postprocess_batch
        if self.enable and not self.save_original:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

---
*** Error running postprocess_image: D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 350, in postprocess_image
        if self.enable and self.swap_in_generated and not self.save_original:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

---
*** Error running postprocess: D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 283, in postprocess
        if self.enable:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'
```

### Additional information

Issue Seems to be only happening in img2img. Im also using mov2mov and its working there. Im new to this, any help or tips would be extremely helpful

**Comment by Gourieff** [comment]
Hello
https://github.com/Gourieff/sd-webui-reactor#iv-attributeerror-faceswapscript-object-has-no-attribute-enable

**Comment by greasemonkey2603** [comment]
Thank you so much i didnt see that part. thank you so much for the help @Gourieff
