### ISSUE TITLE
[SOLVED] Value Error ['AzureExecutionProvider', 'CPUExecutionProvider']

### ISSUE THREAD

**Issue by WylkDraco** [Gourieff/sd-webui-reactor#107]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Trying to get this running for the 5th time, always loops back to this 1 specific error with no apparent guides for how to fix it

### Steps to reproduce the problem

1. Generate any image with reactor enabled
2. Read the error

### Sysinfo

Nvidia 4080 laptop gpu
google chrome
Automatic1111

### Relevant console log

```Shell
venv "C:\Balls\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Checking ReActor requirements... Ok
Launching Web UI with arguments: --xformers
22:56:18 - ReActor - STATUS - Running v0.4.2-b2
Loading weights [4199bcdd14] from C:\Balls\stable-diffusion-webui\models\Stable-diffusion\revAnimated_v122EOL.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: C:\Balls\stable-diffusion-webui\configs\v1-inference.yaml
Startup time: 7.5s (prepare environment: 1.7s, import torch: 2.3s, import gradio: 0.6s, setup paths: 0.5s, initialize shared: 0.2s, other imports: 0.4s, load scripts: 0.9s, create ui: 0.2s, gradio launch: 0.4s).
Applying attention optimization: xformers... done.
Model loaded in 4.8s (load weights from disk: 0.4s, create model: 0.3s, apply weights to model: 2.5s, apply half(): 0.8s, calculate empty prompt: 0.7s).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 11.03it/s]
22:56:54 - ReActor - STATUS - Working: source face index [0], target face index [0]▋   | 19/20 [00:01<00:00, 16.02it/s]
22:56:54 - ReActor - STATUS - Detecting Source Face, Index = 0
*** Error running postprocess_image: C:\Balls\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\Balls\stable-diffusion-webui\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\Balls\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 362, in postprocess_image
        result, output, swapped = swap_face(
      File "C:\Balls\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 279, in swap_face
        source_face, wrong_gender, source_age, source_gender = get_face_single(source_img, face_index=source_faces_index[0], gender_source=gender_source)
      File "C:\Balls\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 198, in get_face_single
        face_analyser = copy.deepcopy(getAnalysisModel())
      File "C:\Users\astit\AppData\Local\Programs\Python\Python310\lib\copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "C:\Users\astit\AppData\Local\Programs\Python\Python310\lib\copy.py", line 271, in _reconstruct
        state = deepcopy(state, memo)
      File "C:\Users\astit\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "C:\Users\astit\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "C:\Users\astit\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "C:\Users\astit\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "C:\Users\astit\AppData\Local\Programs\Python\Python310\lib\copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "C:\Users\astit\AppData\Local\Programs\Python\Python310\lib\copy.py", line 271, in _reconstruct
        state = deepcopy(state, memo)
      File "C:\Users\astit\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "C:\Users\astit\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "C:\Users\astit\AppData\Local\Programs\Python\Python310\lib\copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "C:\Users\astit\AppData\Local\Programs\Python\Python310\lib\copy.py", line 273, in _reconstruct
        y.__setstate__(state)
      File "C:\Balls\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 33, in __setstate__
        self.__init__(model_path)
      File "C:\Balls\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "C:\Balls\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__
        raise e
      File "C:\Balls\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "C:\Balls\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 451, in _create_inference_session
        raise ValueError(
    ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)
```

**Comment by Gourieff** [comment]
`'AzureExecutionProvider'` is for Audio as I know

Perhaps, you have an extension that uninstalled `onnxruntime` and installed `onnxruntime-extension` instead

So try the same as for this case:
https://github.com/Gourieff/sd-webui-reactor#troubleshooting s.VI
But also you need to uninstall `onnxruntime-extensions`

Unfortunately, different versions of ORT cannot get along together

Anyone who knows `onnxruntime-extensions` library better - correct me if I'm wrong

**Comment by Gourieff** [comment]
Tested https://github.com/Gourieff/sd-webui-reactor/issues/108#issuecomment-1728956930 - the method above works

**Comment by gbtyangxinhua** [comment]
02:21:18 - ReActor - STATUS - Working: source face index [0], target face index [0]
02:21:18 - ReActor - STATUS - Detecting Source Face, Index = 0
*** Error running postprocess_image: /stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_faceswap.py
    Traceback (most recent call last):
      File "/stable-diffusion-webui/modules/scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_faceswap.py", line 362, in postprocess_image
        result, output, swapped = swap_face(
      File "/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_swapper.py", line 279, in swap_face
        source_face, wrong_gender, source_age, source_gender = get_face_single(source_img, face_index=source_faces_index[0], gender_source=gender_source)
      File "/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_swapper.py", line 198, in get_face_single
        face_analyser = copy.deepcopy(getAnalysisModel())
      File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
        state = deepcopy(state, memo)
      File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
        state = deepcopy(state, memo)
      File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "/usr/local/lib/python3.10/copy.py", line 273, in _reconstruct
        y.__setstate__(state)
      File "/usr/local/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 33, in __setstate__
        self.__init__(model_path)
      File "/usr/local/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "/usr/local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 432, in __init__
        raise e
      File "/usr/local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "/usr/local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 451, in _create_inference_session
        raise ValueError(
    ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)

my version number: 
onnx                      1.14.1
onnxruntime               1.16.0
open-clip-torch           2.20.0
opencv-python             4.6.0.66
opencv-python-headless    4.8.0.76
This error still occurs.

**Comment by gbtyangxinhua** [comment]
> Tested [#108 (comment)](https://github.com/Gourieff/sd-webui-reactor/issues/108#issuecomment-1728956930) - the method above works

02:21:18 - ReActor - STATUS - Working: source face index [0], target face index [0]
02:21:18 - ReActor - STATUS - Detecting Source Face, Index = 0
*** Error running postprocess_image: /stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_faceswap.py
Traceback (most recent call last):
File "/stable-diffusion-webui/modules/scripts.py", line 675, in postprocess_image
script.postprocess_image(p, pp, *script_args)
File "/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_faceswap.py", line 362, in postprocess_image
result, output, swapped = swap_face(
File "/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_swapper.py", line 279, in swap_face
source_face, wrong_gender, source_age, source_gender = get_face_single(source_img, face_index=source_faces_index[0], gender_source=gender_source)
File "/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_swapper.py", line 198, in get_face_single
face_analyser = copy.deepcopy(getAnalysisModel())
File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
y = _reconstruct(x, memo, *rv)
File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
state = deepcopy(state, memo)
File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
y = copier(x, memo)
File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)
File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
y = copier(x, memo)
File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)
File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
y = _reconstruct(x, memo, *rv)
File "/usr/local/lib/python3.10/copy.py", line 271, in _reconstruct
state = deepcopy(state, memo)
File "/usr/local/lib/python3.10/copy.py", line 146, in deepcopy
y = copier(x, memo)
File "/usr/local/lib/python3.10/copy.py", line 231, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)
File "/usr/local/lib/python3.10/copy.py", line 172, in deepcopy
y = _reconstruct(x, memo, *rv)
File "/usr/local/lib/python3.10/copy.py", line 273, in _reconstruct
y.setstate(state)
File "/usr/local/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 33, in setstate
self.init(model_path)
File "/usr/local/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 25, in init
super().init(model_path, **kwargs)
File "/usr/local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 432, in init
raise e
File "/usr/local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in init
self._create_inference_session(providers, provider_options, disabled_optimizers)
File "/usr/local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 451, in _create_inference_session
raise ValueError(
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)

my version number:
onnx 1.14.1
onnxruntime 1.16.0
open-clip-torch 2.20.0
opencv-python 4.6.0.66
opencv-python-headless 4.8.0.76
This error still occurs.

**Comment by Sakolz35802** [comment]
Thanks.
