### ISSUE TITLE
Does not work for current AUTOMATIC1111 web-ui

### ISSUE THREAD

**Issue by adam-andrzejczak** [Gourieff/sd-webui-reactor#118]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Clean installation, few problems appear but googleable. Unfortunately with this one, I have no clue:

### Steps to reproduce the problem

Log after hitting: webui-user.bat

### Sysinfo

Windows 10

### Relevant console log

```Shell
venv "U:\AI\sd.webuiXXX\webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 48a15821de768fea76e66f26df83df3fddf18f4b
Installing requirements for Web UI
Error running install.py for extension extensions\sd-webui-reactor.
Command: "U:\AI\sd.webuiXXX\webui\venv\Scripts\python.exe" "extensions\sd-webui-reactor\install.py"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "U:\AI\sd.webuiXXX\webui\extensions\sd-webui-reactor\install.py", line 8, in <module>
    from modules.paths_internal import models_path
ModuleNotFoundError: No module named 'modules.paths_internal'


Launching Web UI with arguments: --xformers
Error loading script: console_log_patch.py
Traceback (most recent call last):
  File "U:\AI\sd.webuiXXX\webui\modules\scripts.py", line 218, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "U:\AI\sd.webuiXXX\webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "U:\AI\sd.webuiXXX\webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 5, in <module>
    from insightface.model_zoo.model_zoo import ModelRouter, PickableInferenceSession
ModuleNotFoundError: No module named 'insightface.model_zoo'

Error loading script: reactor_api.py
Traceback (most recent call last):
  File "U:\AI\sd.webuiXXX\webui\modules\scripts.py", line 218, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "U:\AI\sd.webuiXXX\webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "U:\AI\sd.webuiXXX\webui\extensions\sd-webui-reactor\scripts\reactor_api.py", line 17, in <module>
    from scripts.reactor_swapper import EnhancementOptions, swap_face
  File "U:\AI\sd.webuiXXX\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 16, in <module>
    from modules.paths_internal import models_path
ModuleNotFoundError: No module named 'modules.paths_internal'

Error loading script: reactor_faceswap.py
Traceback (most recent call last):
  File "U:\AI\sd.webuiXXX\webui\modules\scripts.py", line 218, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "U:\AI\sd.webuiXXX\webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "U:\AI\sd.webuiXXX\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 16, in <module>
    from modules.paths_internal import models_path
ModuleNotFoundError: No module named 'modules.paths_internal'

Error loading script: reactor_swapper.py
Traceback (most recent call last):
  File "U:\AI\sd.webuiXXX\webui\modules\scripts.py", line 218, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "U:\AI\sd.webuiXXX\webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "U:\AI\sd.webuiXXX\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 16, in <module>
    from modules.paths_internal import models_path
ModuleNotFoundError: No module named 'modules.paths_internal'

21:27:05 - ReActor - STATUS - Running v0.4.2-b3
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [879db523c3] from U:\AI\sd.webuiXXX\webui\models\Stable-diffusion\dreamshaper_8.safetensors
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 3.1s (0.4s create model, 1.3s load weights).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

**Comment by Gourieff** [comment]
Ok, I will fix it today, they use a different paths module in the portable version

**Comment by Gourieff** [comment]
Fixed https://github.com/Gourieff/sd-webui-reactor/commit/077862376e8fb76757d9a00a6f6e241b24c3f712

**Comment by Ehtz** [comment]
Still is not accessible for me despite following instructions.

**Comment by Gourieff** [comment]
@Ehtz please provide your log

**Comment by andrey-krasnov** [comment]
I have the same trouble and no reactor tab. My log is below:
Launching Web UI with arguments: --xformers --force-enable-xformers
*** Error loading script: console_log_patch.py
    Traceback (most recent call last):
      File "D:\ai\sd.webui\webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\ai\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\ai\sd.webui\webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 4, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_api.py
    Traceback (most recent call last):
      File "D:\ai\sd.webui\webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\ai\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\ai\sd.webui\webui\extensions\sd-webui-reactor\scripts\reactor_api.py", line 17, in <module>
        from scripts.reactor_swapper import EnhancementOptions, swap_face
      File "D:\ai\sd.webui\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 10, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_faceswap.py
    Traceback (most recent call last):
      File "D:\ai\sd.webui\webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\ai\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\ai\sd.webui\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 26, in <module>
        from scripts.reactor_swapper import EnhancementOptions, swap_face, check_process_halt, reset_messaged
      File "D:\ai\sd.webui\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 10, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_swapper.py
    Traceback (most recent call last):
      File "D:\ai\sd.webui\webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\ai\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\ai\sd.webui\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 10, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
10:34:47 - ReActor - STATUS - Running v0.4.2
Loading weights [7440042bbd] from D:\ai\sd.webui\webui\models\Stable-diffusion\sd_xl_refiner_1.0.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
