### ISSUE TITLE
AttributeError: module 'modules.scripts' has no attribute 'PostprocessImageArgs'

### ISSUE THREAD

**Issue by fabianslife** [Gourieff/sd-webui-reactor#125]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I wanted to install the extension and followed the instruction carefully. However i get the error: AttributeError: module 'modules.scripts' has no attribute 'PostprocessImageArgs'

### Steps to reproduce the problem

1. Install VS as described
2. Go into SD GUI
3. Import from URL and restart UI

### Sysinfo

Windows 10
Firefox
python: 3.10.11  •  torch: 1.13.1+cu117  •  xformers: N/A  •  gradio: 3.16.2  •  commit: [48a15821](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/48a15821de768fea76e66f26df83df3fddf18f4b)  •  checkpoint: [8635af1c8c]

### Relevant console log

```Shell
Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
10:42:13 - ReActor - STATUS - Running v0.4.2
Error loading script: reactor_faceswap.py
Traceback (most recent call last):
  File "C:\Users\Fabia\Desktop\SD\webui\modules\scripts.py", line 218, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\Fabia\Desktop\SD\webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\Fabia\Desktop\SD\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 49, in <module>
    class FaceSwapScript(scripts.Script):
  File "C:\Users\Fabia\Desktop\SD\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 363, in FaceSwapScript
    def postprocess_image(self, p, script_pp: scripts.PostprocessImageArgs, *args):
AttributeError: module 'modules.scripts' has no attribute 'PostprocessImageArgs'
```

**Comment by Gourieff** [comment]
You need to update your webui to the latest version
Just call `git pull` with CMD from the `webui` folder (don't forget to close your sd-webui server before that - if it's running)

**Comment by fabianslife** [comment]
Unfortunatly this did not solve the problem. I am still getting the following error:

```
Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
20:06:53 - ReActor - STATUS - Running v0.4.2
Error loading script: reactor_faceswap.py
Traceback (most recent call last):
  File "C:\Users\Fabia\Desktop\SD\webui\modules\scripts.py", line 218, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\Fabia\Desktop\SD\webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\Fabia\Desktop\SD\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 49, in <module>
    class FaceSwapScript(scripts.Script):
  File "C:\Users\Fabia\Desktop\SD\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 363, in FaceSwapScript
    def postprocess_image(self, p, script_pp: scripts.PostprocessImageArgs, *args):
AttributeError: module 'modules.scripts' has no attribute 'PostprocessImageArgs'
```

**Comment by Gourieff** [comment]
> AttributeError: module 'modules.scripts' has no attribute 'PostprocessImageArgs'

This error can only appear if you use the initial version of SD WebUI (v1.0.0-pre) with very old variant of `modules/scripts.py' file that has no `PostprocessImageArgs` class inside

Show please the entire console log, not only part with error
