### ISSUE TITLE
Model broken even after being replaced by a freshly downloaded one.

### ISSUE THREAD

**Issue by GoregoriDes** [Gourieff/sd-webui-reactor#134]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Every time the extension starts, it overrides the original model, sometimes turning it into a 28MB file, sometimes to 294MB. It doesn't matter if I directly download the model as suggested in the known issues. 
- I've updated my VS 
- I've tried to create the models/insightface folder manually
-  Replaced the broken model with the freshly downloaded one after the reactor finished installing
-  Replaced the model with the freshly downloaded one after trying to generate an image and got the model broken again.
-  I've installed the extension by using the SD webui and also tried clonning it and installing the requirements.

- I always receive one of the 3 different errors related: 

([failed: Protobuf parsing failed" OR "AttributeError: 'NoneType' object has no attribute 'get'" OR "AttributeError: 'FaceSwapScript' object has no attribute 'save_original'"](https://github.com/Gourieff/sd-webui-reactor#v-invalid_protobuf--load-model-from-modelsinsightfaceinswapper_128onnx-failedprotobuf-parsing-failed-or-attributeerror-nonetype-object-has-no-attribute-get-or-attributeerror-faceswapscript-object-has-no-attribute-save_original)

### Steps to reproduce the problem

The model gets broken every time I try to install the extension, or generate an image.

### Sysinfo

Windows 11, Chrome, i9-13900K, RTX 4090, Automatic1111 up-to-date. 
My extensions:

ABG_extension
Auto-Photoshop-StableDiffusion-Plugin
a1111-sd-webui-tagcomplete
adetailer
clip-interrogator-ext
corridor-crawler-outpainting
infinite-zoom-automatic1111-webui
model-keyword
openOutpaint-webUI-extension
openpose-editor
posex
sd-dynamic-prompts
sd-webui-3d-open-pose-editor
sd-webui-animatediff
sd-webui-controlnet
sd-webui-inpaint-anything
sd-webui-reactor
sd-webui-roop
sd-webui-segment-anything
stable-diffusion-webui-aesthetic-gradients
stable-diffusion-webui-images-browser
stable-diffusion-webui-inspiration
stable-diffusion-webui-rembg
stable-diffusion-webui-vectorstudio
webui-qrcode-generator
LDSR
Lora
ScuNET
SwinIR
canvas-zoom-and-pan
extra-options-section
mobile
prompt-bracket-checker

### Relevant console log

```Shell
Model loaded in 5.4s (load weights from disk: 0.4s, create model: 0.4s, apply weights to model: 3.2s, load VAE: 0.2s, calculate empty prompt: 1.2s).
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  5.33it/s]
15:06:10 - ReActor - STATUS - Working: source face index [0], target face index [0]                                                                                                                                   | 0/1 [00:00<?, ?it/s]
15:06:10 - ReActor - STATUS - Analyzing Source Image...
download_path: C:\Automatic1111\stable-diffusion-webui\models\insightface\models\buffalo_l
Downloading C:\Automatic1111\stable-diffusion-webui\models\insightface\models\buffalo_l.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 281857/281857 [00:29<00:00, 9424.16KB/s]
15:06:44 - ReActor - STATUS - Analyzing Target Image...
15:06:45 - ReActor - STATUS - Detecting Source Face, Index = 0
15:06:45 - ReActor - STATUS - Detected: -77- y.o. Male
*** Error running postprocess_image: C:\Automatic1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\Automatic1111\stable-diffusion-webui\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\Automatic1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 376, in postprocess_image
        result, output, swapped = swap_face(
      File "C:\Automatic1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 320, in swap_face
        face_swapper = getFaceSwapModel(model)
      File "C:\Automatic1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 89, in getFaceSwapModel
        FS_MODEL = insightface.model_zoo.get_model(model_path, providers=providers)
      File "C:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
        model = router.get_model(providers=providers, provider_options=provider_options)
      File "C:\Automatic1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 21, in patched_get_model
        session = PickableInferenceSession(self.onnx_file, **kwargs)
      File "C:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "C:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "C:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
        sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Automatic1111\stable-diffusion-webui\models\insightface\inswapper_128.onnx failed:Protobuf parsing failed.

---
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:34<00:00, 34.37s/it]
Total progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:34<00:00, 34.37s/it]
```

**Comment by GoregoriDes** [comment]
I have checked, and it wasn't really breaking the model, it was "re-downloading it" but didn't completely download it, the weird thing is that it was consistent in sizes (28 and 290 MB), even if it was already in the folder... I added a check in the installation just to make sure it doesn't re-download the model if it already exists.

install.py from 34

model_url = "https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128.onnx"
model_name = os.path.basename(model_url)
model_path = os.path.join(models_dir, model_name)

if not os.path.exists(model_path):
    download(model_url, model_path)
else:
    print(f"{model_name} already exists, skipping download")
