### ISSUE TITLE
*** Error loading script: reactor_faceswap.py

### ISSUE THREAD

**Issue by SirVonStein** [Gourieff/sd-webui-reactor#136]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Installed and updated. Checked everything for correct files in folders. Reran the extension download. Done all that has been troubleshot here. Still no fix.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### Sysinfo

A1111 WebUI

### Relevant console log

```Shell
*** Error loading script: reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\Program Files (x86)\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Program Files (x86)\Stable Diffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Program Files (x86)\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 28, in <module>
        from scripts.console_log_patch import apply_logging_patch
      File "C:\Program Files (x86)\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 5, in <module>
        from insightface.model_zoo.model_zoo import ModelRouter, PickableInferenceSession
    ModuleNotFoundError: No module named 'insightface.model_zoo'
```

**Comment by Gourieff** [comment]
It seems that there's smth wrong with the insightface library
Try to remove both insightface folders (insightface and insightface-0.7.3.dist-info) from the `C:\Program Files (x86)\Stable Diffusion\stable-diffusion-webui\venv\Lib\site-packages`
And then:
https://github.com/Gourieff/sd-webui-reactor#insightfacebuild

**Comment by permskychel** [comment]
I have a similar problem and I can't fix it. Please help!


Restarting UI...
Closing server running on port: 7860
2023-11-12 16:16:26,294 - ControlNet - INFO - ControlNet v1.1.215
2023-11-12 16:16:26,294 - ControlNet - INFO - ControlNet v1.1.215
Error loading script: console_log_patch.py
Traceback (most recent call last):
  File "E:\SD2023\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\SD2023\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\SD2023\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 5, in <module>
    from insightface.model_zoo.model_zoo import ModelRouter, PickableInferenceSession
ModuleNotFoundError: No module named 'insightface.model_zoo'

16:16:26 - ReActor - STATUS - Running v0.5.0-b1
Error loading script: reactor_faceswap.py
Traceback (most recent call last):
  File "E:\SD2023\stable-diffusion-webui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "E:\SD2023\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\SD2023\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 33, in <module>
    from scripts.console_log_patch import apply_logging_patch
  File "E:\SD2023\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 5, in <module>
    from insightface.model_zoo.model_zoo import ModelRouter, PickableInferenceSession
ModuleNotFoundError: No module named 'insightface.model_zoo'

**Comment by mingren713** [comment]
I have a similar problem and I can't fix it. Please help!

 Traceback (most recent call last):
      File "E:\sd-webui-aki-v4.5\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "E:\sd-webui-aki-v4.5\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 370, in postprocess_image
        result, output, swapped = swap_face(
      File "E:\sd-webui-aki-v4.5\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 506, in swap_face
        source_faces = analyze_faces(source_img)
      File "E:\sd-webui-aki-v4.5\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 270, in analyze_faces
        face_analyser = copy.deepcopy(getAnalysisModel())
      File "E:\sd-webui-aki-v4.5\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 115, in getAnalysisModel
        ANALYSIS_MODEL = insightface.app.FaceAnalysis(
      File "E:\sd-webui-aki-v4.5\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 59, in patched_faceanalysis_init
        assert 'detection' in self.models
    AssertionError
