### ISSUE TITLE
[SOLVED] ModuleNotFoundError: No module named 'insightface'

### ISSUE THREAD

**Issue by consecutiotemporum** [Gourieff/sd-webui-reactor#146]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Insightface seems to be not installed properly.
The folders `insightface` and `insightface-0.7.3.dist-info` in `C:\Automatic1111\webui\venv\Lib\site-packages` are present

### Steps to reproduce the problem

- Nvidia GPU RTX 4070
- Python 3.10.6 64-bit
- Clean install of Automatic1111 (not in Windows user folder)
- No Stability Matrix
- Automatic1111 is fully functional
- (context: I have generated RT Tensor Engine for a safetensor model. This is the only "addon" that I installed)

- Installed complete Visual Studio 2022 (trying with and without dependencies [CC++ Tools] for desktop)

- Installed Reactor from URL in the Extension tab.

- The terminal invited me to stop the Server
- CTRL + C

Relaunch Automatic1111

BELOW THE MESSAGES THAT I GET.

### Sysinfo

Win 11 Home
32 GB DDR5
Python 3.10.6
RTX 4070 12 GB

### Relevant console log

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Collecting insightface==0.7.3
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
**Checking ReActor requirements... Error: The 'insightface==0.7.3' distribution was not found and is required by the application**

--- PLEASE, RESTART the Server! ---
You are up to date with the most recent release.
Launching Web UI with arguments: --update-check --xformers --precision full --no-half
*** Error loading script: console_log_patch.py
    Traceback (most recent call last):
      File "C:\Automatic1111\webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Automatic1111\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Automatic1111\webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 4, in <module>
        import insightface
    **ModuleNotFoundError: No module named 'insightface'**

---
*** Error loading script: reactor_api.py
    Traceback (most recent call last):
      File "C:\Automatic1111\webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Automatic1111\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Automatic1111\webui\extensions\sd-webui-reactor\scripts\reactor_api.py", line 17, in <module>
        from scripts.reactor_swapper import EnhancementOptions, swap_face
      File "C:\Automatic1111\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 10, in <module>
        import insightface
    **ModuleNotFoundError: No module named 'insightface'**

---
*** Error loading script: reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\Automatic1111\webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Automatic1111\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Automatic1111\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 26, in <module>
        from scripts.reactor_swapper import EnhancementOptions, swap_face, check_process_halt, reset_messaged
      File "C:\Automatic1111\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 10, in <module>
        import insightface
    **ModuleNotFoundError: No module named 'insightface'**

---
*** Error loading script: reactor_swapper.py
    Traceback (most recent call last):
      File "C:\Automatic1111\webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Automatic1111\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Automatic1111\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 10, in <module>
        import insightface
    **ModuleNotFoundError: No module named 'insightface'**
```

### Additional information

I tried the solution VIII.
Nothing.

If I force renistall of insightface with `python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl --force-reinstall` i get this error (bold)

ERROR: **pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.20 requires pyre-extensions==0.0.29, which is not installed.
blendmodes 2022 requires Pillow<10,>=9.0.0, but you have pillow 10.1.0 which is incompatible.
open-clip-torch 2.20.0 requires protobuf<4, but you have protobuf 4.24.4 which is incompatible.
tb-nightly 2.15.0a20231021 requires protobuf<4.24,>=3.19.6, but you have protobuf 4.24.4 which is incompatible.**
Successfully installed Pillow-10.1.0 PyYAML-6.0.1 albumentations-1.3.1 certifi-2023.7.22 charset-normalizer-3.3.0 colorama-0.4.6 contourpy-1.1.1 cycler-0.12.1 cython-3.0.4 easydict-1.10 fonttools-4.43.1 idna-3.4 imageio-2.31.5 insightface-0.7.3 joblib-1.3.2 kiwisolver-1.4.5 lazy_loader-0.3 matplotlib-3.8.0 networkx-3.2 numpy-1.26.1 onnx-1.14.1 opencv-python-headless-4.8.1.78 packaging-23.2 prettytable-3.9.0 protobuf-4.24.4 pyparsing-3.1.1 python-dateutil-2.8.2 qudida-0.0.4 requests-2.31.0 scikit-image-0.22.0 scikit-learn-1.3.1 scipy-1.11.3 six-1.16.0 threadpoolctl-3.2.0 tifffile-2023.9.26 tqdm-4.66.1 typing-extensions-4.8.0 urllib3-2.0.7 wcwidth-0.2.8

**Comment by Gourieff** [comment]
Try `system\python\python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl` from the `webui` folder where must be the downloaded `insightface-0.7.3-cp310-cp310-win_amd64.whl` file
And it's not a very good idea to run `pip install` with a `--force-reinstall` flag, because all the deps also will be recompiled, rebuild and reinstalled
You can run into some "incompatible" problems - just what you got
If you want to reinstall only one desirable package - set `--no-deps --force-reinstall`

if you run `python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl` not from the `sd.webui\system\python` directory - you will install Insightface in your OS but not inside the A1111 enclosure

**Comment by consecutiotemporum** [comment]
Solved with solution II

**Comment by henryfw** [comment]
Get file at https://www.reddit.com/r/StableDiffusion/comments/1749kpk/problem_with_pip_install_insightface073_newbie/

```
stable-diffusion-webui-master> .\venv\Scripts\activate
(venv) stable-diffusion-webui-master> pip install insightface-0.7.3-cp310-cp310-win_amd64.whl
```

**Comment by azamet90** [comment]
> Get file at https://www.reddit.com/r/StableDiffusion/comments/1749kpk/problem_with_pip_install_insightface073_newbie/
> 
> ```
> stable-diffusion-webui-master> .\venv\Scripts\activate
> (venv) stable-diffusion-webui-master> pip install insightface-0.7.3-cp310-cp310-win_amd64.whl
> ```

ERROR: insightface-0.7.3-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.
