### ISSUE TITLE
AttributeError: partially initialized module 'modules.sysinfo' 

### ISSUE THREAD

**Issue by luciacoffeelove** [Gourieff/sd-webui-reactor#148]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

After installing the program, an error occurs and the program cannot be operated.
AttributeError: partially initialized module 'modules.sysinfo' has no attribute 'format_exception' (most likely due to a circular import)

I want to solve the problem, please help me

### Steps to reproduce the problem

1. available 'ReActor' Search and install
2. installed > apply and reatart ui
3. cmd exe > Click on anything (error)
4. Closing and restarting open programs
5. cmd exe > Click on anything (error)

### Sysinfo

 SD WebUI, 1.6
CPU 3060 / x64 based processor / 32.0GB
13th Gen Intel(R) Core(TM) i7-13700F

### Relevant console log

```Shell
C:\stable-diffusion-webui>git pull
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

venv "C:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\launch_utils.py", line 231, in run_extension_installer
    stdout = run(f'"{python}" "{path_installer}"', errdesc=f"Error running install.py for extension {extension_dir}", custom_env=env).strip()
  File "C:\stable-diffusion-webui\modules\launch_utils.py", line 115, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Error running install.py for extension C:\stable-diffusion-webui\extensions\sd-webui-reactor.
Command: "C:\stable-diffusion-webui\venv\Scripts\python.exe" "C:\stable-diffusion-webui\extensions\sd-webui-reactor\install.py"
Error code: 1
stderr: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 815, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 3]  θ ã  ϴ: 'C:\\stable-diffusion-webui\\models\\roop\\inswapper_128.onnx' -> 'C:\\stable-diffusion-webui\\models\\insightface\\inswapper_128.onnx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\extensions\sd-webui-reactor\install.py", line 28, in <module>
    shutil.move(os.path.join(models_dir_old, file), os.path.join(models_dir, file))
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\stable-diffusion-webui\\models\\insightface\\inswapper_128.onnx'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 26, in preload_extensions
    module = load_module(preload_script)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-wd14-tagger\preload.py", line 4, in <module>
    from modules.shared import models_path
ImportError: cannot import name 'models_path' from partially initialized module 'modules.shared' (most likely due to a circular import) (C:\stable-diffusion-webui\modules\shared.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\launch.py", line 48, in <module>
    main()
  File "C:\stable-diffusion-webui\launch.py", line 39, in main
    prepare_environment()
  File "C:\stable-diffusion-webui\modules\launch_utils.py", line 400, in prepare_environment
    run_extensions_installers(settings_file=args.ui_settings_file)
  File "C:\stable-diffusion-webui\modules\launch_utils.py", line 268, in run_extensions_installers
    run_extension_installer(path)
  File "C:\stable-diffusion-webui\modules\launch_utils.py", line 235, in run_extension_installer
    errors.report(str(e))
  File "C:\stable-diffusion-webui\modules\errors.py", line 29, in report
    record_exception()
  File "C:\stable-diffusion-webui\modules\errors.py", line 17, in record_exception
    from modules import sysinfo
  File "C:\stable-diffusion-webui\modules\sysinfo.py", line 13, in <module>
    from modules import paths_internal, timer, shared, extensions, errors
  File "C:\stable-diffusion-webui\modules\shared.py", line 5, in <module>
    from modules import shared_cmd_options, shared_gradio_themes, options, shared_items, sd_models_types
  File "C:\stable-diffusion-webui\modules\shared_cmd_options.py", line 9, in <module>
    script_loading.preload_extensions(extensions_dir, parser, extension_list=launch.list_extensions(launch.args.ui_settings_file))
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 31, in preload_extensions
    errors.report(f"Error running preload() for {preload_script}", exc_info=True)
  File "C:\stable-diffusion-webui\modules\errors.py", line 29, in report
    record_exception()
  File "C:\stable-diffusion-webui\modules\errors.py", line 18, in record_exception
    exception_records.append(sysinfo.format_exception(e, tb))
AttributeError: partially initialized module 'modules.sysinfo' has no attribute 'format_exception' (most likely due to a circular import)
```

**Comment by Gourieff** [comment]
Please look at your folder `C:\stable-diffusion-webui\models\insightface`
It should contain the following folders and files:
```
inswapper_128.onnx
models\buffalo_l\1k3d68.onnx
models\buffalo_l\2d106det.onnx
models\buffalo_l\det_10g.onnx
models\buffalo_l\genderage.onnx
models\buffalo_l\w600k_r50.onnx
```
