### ISSUE TITLE
[SOLVED] AttributeError: 'INSwapper' object has no attribute 'taskname'

### ISSUE THREAD

**Issue by lost-in-emotions** [Gourieff/sd-webui-reactor#149]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

hey everyone, just tried out ReActor and when i locate a source and target face, i get this error lines as below. and of course, the face isnt swapped. is this a bug, or does i have something forgotten to do? thx4hlp

### Steps to reproduce the problem

hey everyone, just tried out ReActor and when i locate a source and target face, i get this error lines as below. and of course, the face isnt swapped. is this a bug, or does i have something forgotten to do? thx4hlp

### Sysinfo

Windows 10, RTX 3060 ti, 16GB RAM, SD 1.6

### Relevant console log

```Shell
18:46:03 - ReActor - STATUS - Working: source face index [0], target face index [0]████| 11/11 [00:05<00:00,  1.69it/s]
18:46:03 - ReActor - STATUS - Analyzing Source Image...
*** Error running postprocess_image: C:\Users\NAME\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\Users\NAME\stable-diffusion-webui\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\Users\NAME\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 402, in postprocess_image
        result, output, swapped = swap_face(
      File "C:\Users\NAME\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 327, in swap_face
        source_faces = analyze_faces(source_img)
      File "C:\Users\NAME\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 222, in analyze_faces
        face_analyser = copy.deepcopy(getAnalysisModel())
      File "C:\Users\NAME\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 86, in getAnalysisModel
        ANALYSIS_MODEL = insightface.app.FaceAnalysis(
      File "C:\Users\NAME\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 54, in patched_faceanalysis_init
        elif model.taskname not in self.models and (allowed_modules is None or model.taskname in allowed_modules):
    AttributeError: 'INSwapper' object has no attribute 'taskname'
```

**Comment by Gourieff** [comment]
Hello there
Go to the `C:\Users\NAME\stable-diffusion-webui\models\insightface\models\buffalo_l` folder and look there for the `inswapper_128.onnx` file. Move it to the `C:\Users\NAME\stable-diffusion-webui\models\insightface` folder

**Comment by lost-in-emotions** [comment]
Hey and thank you. There was in both folder the .onnx file. i copied it as you said.
now the buffalo_1 doesnt have one anymore, only in the insightface.

but now i get another error. its render but the face is not swapped (not lookalike)

*** Error running postprocess_image: C:\Users\NAME\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\Users\NAME\stable-diffusion-webui\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\Users\NAME\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 402, in postprocess_image
        result, output, swapped = swap_face(
      File "C:\Users\NAME\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 327, in swap_face
        source_faces = analyze_faces(source_img)
      File "C:\Users\NAME\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 222, in analyze_faces
        face_analyser = copy.deepcopy(getAnalysisModel())
      File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 271, in _reconstruct
        state = deepcopy(state, memo)
      File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 271, in _reconstruct
        state = deepcopy(state, memo)
      File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "C:\Users\NAME\AppData\Local\Programs\Python\Python310\lib\copy.py", line 273, in _reconstruct
        y.__setstate__(state)
      File "C:\Users\NAME\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 33, in __setstate__
        self.__init__(model_path)
      File "C:\Users\NAME\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "C:\Users\NAME\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__
        raise e
      File "C:\Users\NAME\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "C:\Users\NAME\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 451, in _create_inference_session
        raise ValueError(
    ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

---
Total progress: 100%|████████████████████████████████████████████████████████████████████| 5/5 [00:09<00:00,  1.99s/it]
Total progress: 100%|████████████████████████████████████████████████████████████████████| 5/5 [00:09<00:00,  1.91it/s]

**Comment by Gourieff** [comment]
> ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

This is because you have ORT-GPU installed but ReActor needs ORT
https://github.com/Gourieff/sd-webui-reactor#vi-valueerror-this-ort-build-has-tensorrtexecutionprovider-cudaexecutionprovider-cpuexecutionprovider-enabled-or-valueerror-this-ort-build-has-azureexecutionprovider-cpuexecutionprovider-enabled
In the 4th step (point 3) you can run `pip install onnx onnxruntime` instead of `pip install onnx==1.14.1 onnxruntime==1.15.1`

**Comment by lost-in-emotions** [comment]
Thank you! This worked! (y)

**Comment by lost-in-emotions** [comment]
( even ive done it with: pip install onnx==1.14.1 onnxruntime==1.15.1 )

**Comment by Adi-Immersfy** [comment]
Thanks, it worked
