### ISSUE TITLE
ModuleNotFoundError: No module named 'insightface.model_zoo'

### ISSUE THREAD

**Issue by DavidDadd** [Gourieff/sd-webui-reactor#152]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

ModuleNotFoundError: No module named 'insightface.model_zoo'

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### Sysinfo

windows10 ,A1111

### Relevant console log

```Shell
Error loading script: console_log_patch.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 5, in <module>
    from insightface.model_zoo.model_zoo import ModelRouter, PickableInferenceSession
ModuleNotFoundError: No module named 'insightface.model_zoo'

00:33:27 - ReActor - STATUS - Running v0.4.3-b4
Error loading script: reactor_faceswap.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 28, in <module>
    from scripts.console_log_patch import apply_logging_patch
  File "C:\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 5, in <module>
    from insightface.model_zoo.model_zoo import ModelRouter, PickableInferenceSession
ModuleNotFoundError: No module named 'insightface.model_zoo'
```

**Comment by Gourieff** [comment]
https://github.com/Gourieff/sd-webui-reactor/issues/136#issuecomment-1767023124
