### ISSUE TITLE
Error running postprocess image

### ISSUE THREAD

**Issue by HiIvan1990** [Gourieff/sd-webui-reactor#163]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

It is does not process the image completely

### Steps to reproduce the problem

I just go step by step for an instruction of use

### Sysinfo

[sysinfo-2023-10-28-22-18.txt](https://github.com/Gourieff/sd-webui-reactor/files/13196807/sysinfo-2023-10-28-22-18.txt)

### Relevant console log

```Shell
Error running postprocess_image: C:\Users\KUDES\Downloads\A1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\Users\KUDES\Downloads\A1111\stable-diffusion-webui\modules\scripts.py", line 679, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\Users\KUDES\Downloads\A1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 402, in postprocess_image
        result, output, swapped = swap_face(
      File "C:\Users\KUDES\Downloads\A1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 327, in swap_face
        source_faces = analyze_faces(source_img)
      File "C:\Users\KUDES\Downloads\A1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 222, in analyze_faces
        face_analyser = copy.deepcopy(getAnalysisModel())
      File "C:\Users\KUDES\AppData\Local\Programs\Python\Python310\lib\copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "C:\Users\KUDES\AppData\Local\Programs\Python\Python310\lib\copy.py", line 271, in _reconstruct
        state = deepcopy(state, memo)
      File "C:\Users\KUDES\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "C:\Users\KUDES\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "C:\Users\KUDES\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "C:\Users\KUDES\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "C:\Users\KUDES\AppData\Local\Programs\Python\Python310\lib\copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "C:\Users\KUDES\AppData\Local\Programs\Python\Python310\lib\copy.py", line 271, in _reconstruct
        state = deepcopy(state, memo)
      File "C:\Users\KUDES\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "C:\Users\KUDES\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "C:\Users\KUDES\AppData\Local\Programs\Python\Python310\lib\copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "C:\Users\KUDES\AppData\Local\Programs\Python\Python310\lib\copy.py", line 273, in _reconstruct
        y.__setstate__(state)
      File "C:\Users\KUDES\Downloads\A1111\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 33, in __setstate__
        self.__init__(model_path)
      File "C:\Users\KUDES\Downloads\A1111\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "C:\Users\KUDES\Downloads\A1111\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "C:\Users\KUDES\Downloads\A1111\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 375, in _create_inference_session
        raise ValueError(
    ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)
```

**Comment by HiIvan1990** [comment]
This method not help

python -m pip install -U pip
pip uninstall -y onnx onnxruntime onnxruntime-gpu onnxruntime-silicon
pip uninstall -y onnxruntime-extensions <<<<< This i didn't have it, but i tried.
pip install onnx==1.14.0 onnxruntime==1.15.0
