### ISSUE TITLE
Error installing from clean

### ISSUE THREAD

**Issue by darktar** [Gourieff/sd-webui-reactor#175]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

i was using Reactor Extension until 2 days ago, when today i find troubles opening Stable Diffusion.
after not finding the error in Internet, i decide to delete all and start over.
i install controlnet without issues.
when install ReActor extension following the steps on the tutorial, i cannot open Stable Diffusion 111 UI again.
`
Traceback (most recent call last):
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\launch.py", line 44, in main
    start()
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\modules\launch_utils.py", line 681, in start
    webui.webui()
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\webui.py", line 64, in webui
    shared.demo = ui.create_ui()
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\modules\ui.py", line 721, in create_ui
    custom_inputs = scripts.scripts_txt2img.setup_ui()
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\modules\scripts.py", line 541, in setup_ui
    self.setup_ui_for_section(None)
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\modules\scripts.py", line 527, in setup_ui_for_section
    self.create_script_ui(script)
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\modules\scripts.py", line 490, in create_script_ui
    control.custom_script_source = os.path.basename(script.filename)
AttributeError: 'str' object has no attribute 'custom_script_source'`

i receive the error: AttributeError: 'str' object has no attribute 'custom_script_source' at the start the start script

when i disable the extensions (adding --disable-extra-extensions at ARGS) i run the stable diffusion again without troubles.
i disable ReActor extension and i can run normally but without reActor.

Someone can help me ? i think the new pool of stable-diffusion-webui-directml has some changes that make ReActor crash when try to create new elements UI.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### Sysinfo

Windows 10 64, AMD 6700 RX

### Relevant console log

```Shell
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.6.0
Commit hash: 64e6b0687e182d5f17216755561c9c143d69c220
Installing sd-webui-controlnet requirement: changing opencv-python version from 4.7.0.72 to 4.8.0
ReActor preheating... Device: CPU
Launching Web UI with arguments: --medvram --opt-split-attention
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
2023-11-05 01:13:12,892 - ControlNet - INFO - ControlNet v1.1.415
ControlNet preprocessor location: C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\downloads
2023-11-05 01:13:12,996 - ControlNet - INFO - ControlNet v1.1.415
01:13:13 - ReActor - STATUS - Running v0.5.0-a3
Loading weights [a435b37393] from C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\models\Stable-diffusion\realcartoonRealistic_v9.safetensors
Traceback (most recent call last):
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\launch.py", line 44, in main
    start()
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\modules\launch_utils.py", line 681, in start
    webui.webui()
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\webui.py", line 64, in webui
    shared.demo = ui.create_ui()
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\modules\ui.py", line 721, in create_ui
    custom_inputs = scripts.scripts_txt2img.setup_ui()
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\modules\scripts.py", line 541, in setup_ui
    self.setup_ui_for_section(None)
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\modules\scripts.py", line 527, in setup_ui_for_section
    self.create_script_ui(script)
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\modules\scripts.py", line 490, in create_script_ui
    control.custom_script_source = os.path.basename(script.filename)
AttributeError: 'str' object has no attribute 'custom_script_source'
Creating model from config: C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\configs\v1-inference.yaml
Applying attention optimization: Doggettx... done.
Model loaded in 4.1s (load weights from disk: 0.4s, create model: 0.3s, apply weights to model: 1.9s, apply half(): 1.1s, calculate empty prompt: 0.3s).
```

**Comment by Gourieff** [comment]
But it's very strange - according to your log there's no errors with ReActor
Could you provide `pip list` of your VENV?

**Comment by Gourieff** [comment]
Updated, should work, please delete ReActor and try again
Unfortunately, I don't have AMD GPUs or MAC M# to test - only NVIDIA and Intel

**Comment by darktar** [comment]
> Updated, should work, please delete ReActor and try again Unfortunately, I don't have AMD GPUs or MAC M# to test - only NVIDIA and Intel

i move to version_flag = "v0.4.2" i open without issues

`
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.6.0
Commit hash: 64e6b0687e182d5f17216755561c9c143d69c220
Collecting onnxruntime==1.15.1
  Downloading onnxruntime-1.15.1-cp310-cp310-win_amd64.whl (6.7 MB)
     ---------------------------------------- 6.7/6.7 MB 13.5 MB/s eta 0:00:00
Requirement already satisfied: coloredlogs in c:\users\seeb\desktop\stablediffusion\stable-diffusion-webui-directml\venv\lib\site-packages (from onnxruntime==1.15.1) (15.0.1)
Requirement already satisfied: numpy>=1.21.6 in c:\users\seeb\desktop\stablediffusion\stable-diffusion-webui-directml\venv\lib\site-packages (from onnxruntime==1.15.1) (1.23.5)
Requirement already satisfied: sympy in c:\users\seeb\desktop\stablediffusion\stable-diffusion-webui-directml\venv\lib\site-packages (from onnxruntime==1.15.1) (1.12)
Requirement already satisfied: protobuf in c:\users\seeb\desktop\stablediffusion\stable-diffusion-webui-directml\venv\lib\site-packages (from onnxruntime==1.15.1) (3.20.3)
Requirement already satisfied: packaging in c:\users\seeb\desktop\stablediffusion\stable-diffusion-webui-directml\venv\lib\site-packages (from onnxruntime==1.15.1) (23.2)
Requirement already satisfied: flatbuffers in c:\users\seeb\desktop\stablediffusion\stable-diffusion-webui-directml\venv\lib\site-packages (from onnxruntime==1.15.1) (23.5.26)
Requirement already satisfied: humanfriendly>=9.1 in c:\users\seeb\desktop\stablediffusion\stable-diffusion-webui-directml\venv\lib\site-packages (from coloredlogs->onnxruntime==1.15.1) (10.0)
Requirement already satisfied: mpmath>=0.19 in c:\users\seeb\desktop\stablediffusion\stable-diffusion-webui-directml\venv\lib\site-packages (from sympy->onnxruntime==1.15.1) (1.3.0)
Requirement already satisfied: pyreadline3 in c:\users\seeb\desktop\stablediffusion\stable-diffusion-webui-directml\venv\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime==1.15.1) (3.4.1)
Installing collected packages: onnxruntime
  Attempting uninstall: onnxruntime
    Found existing installation: onnxruntime 1.15.0
    Uninstalling onnxruntime-1.15.0:
      Successfully uninstalled onnxruntime-1.15.0
Successfully installed onnxruntime-1.15.1
Checking ReActor requirements... Error: (onnxruntime 1.15.0 (c:\users\seeb\desktop\stablediffusion\stable-diffusion-webui-directml\venv\lib\site-packages), Requirement.parse('onnxruntime==1.15.1'))

--- PLEASE, RESTART the Server! ---
Launching Web UI with arguments: --medvram --opt-split-attention
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
2023-11-05 10:51:41,714 - ControlNet - INFO - ControlNet v1.1.415
ControlNet preprocessor location: C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\downloads
2023-11-05 10:51:41,840 - ControlNet - INFO - ControlNet v1.1.415
10:51:42 - ReActor - STATUS - Running v0.4.2
Loading weights [a435b37393] from C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\models\Stable-diffusion\realcartoonRealistic_v9.safetensors
Running on local URL:  http://127.0.0.1:7860
`

i will try increase the commit number until the error

**Comment by Gourieff** [comment]
> i will try increase the commit number until the error

Good idea 👍

**Comment by darktar** [comment]
> Updated, should work, please delete ReActor and try again Unfortunately, I don't have AMD GPUs or MAC M# to test - only NVIDIA and Intel

Last commit that works:

`
SHA-1: 4721a4baef1e80c094b0f8b6f4d0aa20b76a398d

* VersionUP (0.5.0 alpha1)
`

stop working at:

`
SHA-1: b75aa16b11ce96d7088dfaa8e7338e7ab5fa74b2

* UPDATE: CUDA Support

- Full support of ORT-GPU alongside with ORT
- New opton in Settings: Execution Provider selector
- Many different fixes and improvements
VersionUP (0.5.0 alpha2)
`

it's something with the settings UI load that not work.. sorry i can't help you more.

**Comment by darktar** [comment]
> > i will try increase the commit number until the error
> 
> Good idea 👍

if you make a new pull branch with DEBUG tools (a bunch of prints to log.txt) i can run it and upload for you. 
(i am active for the next 3 o 4 hours)

**Comment by Gourieff** [comment]
@darktar I published Debug branch and will be very grateful if you'll make a run
There must be logs inside `extensions/sd-webui-reactor` and `extensions/sd-webui-reactor/scripts`

**Comment by darktar** [comment]
> @darktar I published Debug branch and will be very grateful if you'll make a run There must be logs inside `extensions/sd-webui-reactor` and `extensions/sd-webui-reactor/scripts`

hello there, i was need the python class win32-setctime.. after installing that
(pip install win32-setctime on the env(scripts) i was able to run it, but the logs are empty

OUTPUT:
`
15:37:00 - ReActor - STATUS - Running v0.5.0-a5
Loading weights [ecefb796ff] from C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\models\Stable-diffusion\neverendingDreamNED_v122BakedVae.safetensors
Traceback (most recent call last):
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\launch.py", line 44, in main
    start()
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\modules\launch_utils.py", line 681, in start
    webui.webui()
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\webui.py", line 64, in webui
    shared.demo = ui.create_ui()
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\modules\ui.py", line 721, in create_ui
    custom_inputs = scripts.scripts_txt2img.setup_ui()
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\modules\scripts.py", line 541, in setup_ui
    self.setup_ui_for_section(None)
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\modules\scripts.py", line 527, in setup_ui_for_section
    self.create_script_ui(script)
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\modules\scripts.py", line 490, in create_script_ui
    control.custom_script_source = os.path.basename(script.filename)
AttributeError: 'str' object has no attribute 'custom_script_source'
Creating model from config: C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\configs\v1-inference.yaml
Applying attention optimization: Doggettx... done.
Model loaded in 2.2s (load weights from disk: 0.2s, create model: 0.3s, apply weights to model: 1.1s, apply half(): 0.3s, calculate empty prompt: 0.3s).
Presione una tecla para continuar . . .

`
folder screenshot:
![screen01](https://github.com/Gourieff/sd-webui-reactor/assets/12651608/ff405071-bc3c-48f2-b752-9a9917bc6664)

also _install.log was 0kb

try put logs lines before and after every step so you can see if crash in some place. The class loguru  i don't know how to work, so i can't help you why isnt printing everything what happen.

**Comment by darktar** [comment]
> @darktar I published Debug branch and will be very grateful if you'll make a run There must be logs inside `extensions/sd-webui-reactor` and `extensions/sd-webui-reactor/scripts`

if it helps to you, i make pprint on scripts.py (when the error occurs ) and this is what show up:

`Launching Web UI with arguments: --medvram --opt-split-attention
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
2023-11-05 15:59:19,018 - ControlNet - INFO - ControlNet v1.1.415
ControlNet preprocessor location: C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\downloads
2023-11-05 15:59:19,117 - ControlNet - INFO - ControlNet v1.1.415
15:59:19 - ReActor - STATUS - Running v0.5.0-a5
Loading weights [ecefb796ff] from C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\models\Stable-diffusion\neverendingDreamNED_v122BakedVae.safetensors
checkbox
dropdown
slider
number
checkbox
number
slider
slider
slider
state
state
state
image
checkbox
textbox
textbox
dropdown
radio
slider
checkbox
dropdown
slider
slider
checkbox
checkbox
radio
radio
radio
checkbox
slider
checkbox
checkbox
'CPU'
Traceback (most recent call last):
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\launch.py", line 44, in main
    start()
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\modules\launch_utils.py", line 681, in start
    webui.webui()
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\webui.py", line 64, in webui
    shared.demo = ui.create_ui()
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\modules\ui.py", line 721, in create_ui
    custom_inputs = scripts.scripts_txt2img.setup_ui()
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\modules\scripts.py", line 542, in setup_ui
    self.setup_ui_for_section(None)
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\modules\scripts.py", line 528, in setup_ui_for_section
    self.create_script_ui(script)
  File "C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\modules\scripts.py", line 491, in create_script_ui
    control.custom_script_source = os.path.basename(script.filename)
AttributeError: 'str' object has no attribute 'custom_script_source'
Creating model from config: C:\Users\Seeb\Desktop\StableDiffusion\stable-diffusion-webui-directml\configs\v1-inference.yaml
Applying attention optimization: Doggettx... done.
Model loaded in 2.2s (load weights from disk: 0.2s, create model: 0.3s, apply weights to model: 1.1s, apply half(): 0.3s, calculate empty prompt: 0.3s).
Presione una tecla para continuar . . .`

it's seems that the type of control that it's giving to the UI was 'CPU' text insted of textbox maybe.

**Comment by Gourieff** [comment]
Oh... What a weird error...
And thank you so much too for such a good help! 🤝
Will be fixed soon!
