### ISSUE TITLE
Doesn't work on Mac M2 (ImportError, onnxruntime)

### ISSUE THREAD

**Issue by eliu9395** [Gourieff/sd-webui-reactor#177]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Keep getting "Error loading script: reactor_swapper.py" followed by some lines, and "ImportError: Unable to import dependency onnxruntime".

### Steps to reproduce the problem

I installed the extension with URL thru Automatic1111, installed insightface in the directory, then restarted the program. Then tried installing onnxruntime using "pip install onnxruntime" but it doesn't help.

### Sysinfo

MacOS Sonoma 14.1, m2 pro, 16gb ram
Automatic1111 Stable Diffusion - latest

### Relevant console log

```Shell
Python 3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.0.40.1)]
Version: v1.6.0-2-g4afaaf8a
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
ReActor preheating... Device: CPU
Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
*** Error loading script: console_log_patch.py
    Traceback (most recent call last):
      File "/Users/eliu/stable-diffusion-webui/venv/lib/python3.10/site-packages/insightface/__init__.py", line 8, in <module>
        import onnxruntime
      File "/Users/eliu/stable-diffusion-webui/venv/lib/python3.10/site-packages/onnxruntime/__init__.py", line 56, in <module>
        raise import_capi_exception
      File "/Users/eliu/stable-diffusion-webui/venv/lib/python3.10/site-packages/onnxruntime/__init__.py", line 23, in <module>
        from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
      File "/Users/eliu/stable-diffusion-webui/venv/lib/python3.10/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
        from .onnxruntime_pybind11_state import *  # noqa
    ModuleNotFoundError: No module named 'onnxruntime.capi.onnxruntime_pybind11_state'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/eliu/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/eliu/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/eliu/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/console_log_patch.py", line 4, in <module>
        import insightface
      File "/Users/eliu/stable-diffusion-webui/venv/lib/python3.10/site-packages/insightface/__init__.py", line 10, in <module>
        raise ImportError(
    ImportError: Unable to import dependency onnxruntime. 

---
*** Error loading script: reactor_api.py
    Traceback (most recent call last):
      File "/Users/eliu/stable-diffusion-webui/venv/lib/python3.10/site-packages/insightface/__init__.py", line 8, in <module>
        import onnxruntime
      File "/Users/eliu/stable-diffusion-webui/venv/lib/python3.10/site-packages/onnxruntime/__init__.py", line 56, in <module>
        raise import_capi_exception
      File "/Users/eliu/stable-diffusion-webui/venv/lib/python3.10/site-packages/onnxruntime/__init__.py", line 23, in <module>
        from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
      File "/Users/eliu/stable-diffusion-webui/venv/lib/python3.10/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
        from .onnxruntime_pybind11_state import *  # noqa
    ModuleNotFoundError: No module named 'onnxruntime.capi.onnxruntime_pybind11_state'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/eliu/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/eliu/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/eliu/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_api.py", line 17, in <module>
        from scripts.reactor_swapper import EnhancementOptions, swap_face
      File "/Users/eliu/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_swapper.py", line 10, in <module>
        import insightface
      File "/Users/eliu/stable-diffusion-webui/venv/lib/python3.10/site-packages/insightface/__init__.py", line 10, in <module>
        raise ImportError(
    ImportError: Unable to import dependency onnxruntime. 

---
*** Error loading script: reactor_faceswap.py
    Traceback (most recent call last):
      File "/Users/eliu/stable-diffusion-webui/venv/lib/python3.10/site-packages/insightface/__init__.py", line 8, in <module>
        import onnxruntime
      File "/Users/eliu/stable-diffusion-webui/venv/lib/python3.10/site-packages/onnxruntime/__init__.py", line 56, in <module>
        raise import_capi_exception
      File "/Users/eliu/stable-diffusion-webui/venv/lib/python3.10/site-packages/onnxruntime/__init__.py", line 23, in <module>
        from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
      File "/Users/eliu/stable-diffusion-webui/venv/lib/python3.10/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
        from .onnxruntime_pybind11_state import *  # noqa
    ModuleNotFoundError: No module named 'onnxruntime.capi.onnxruntime_pybind11_state'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/eliu/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/eliu/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/eliu/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_faceswap.py", line 27, in <module>
        from scripts.reactor_swapper import EnhancementOptions, swap_face, check_process_halt, reset_messaged
      File "/Users/eliu/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_swapper.py", line 10, in <module>
        import insightface
      File "/Users/eliu/stable-diffusion-webui/venv/lib/python3.10/site-packages/insightface/__init__.py", line 10, in <module>
        raise ImportError(
    ImportError: Unable to import dependency onnxruntime. 

---
*** Error loading script: reactor_swapper.py
    Traceback (most recent call last):
      File "/Users/eliu/stable-diffusion-webui/venv/lib/python3.10/site-packages/insightface/__init__.py", line 8, in <module>
        import onnxruntime
      File "/Users/eliu/stable-diffusion-webui/venv/lib/python3.10/site-packages/onnxruntime/__init__.py", line 56, in <module>
        raise import_capi_exception
      File "/Users/eliu/stable-diffusion-webui/venv/lib/python3.10/site-packages/onnxruntime/__init__.py", line 23, in <module>
        from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
      File "/Users/eliu/stable-diffusion-webui/venv/lib/python3.10/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
        from .onnxruntime_pybind11_state import *  # noqa
    ModuleNotFoundError: No module named 'onnxruntime.capi.onnxruntime_pybind11_state'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/eliu/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/eliu/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/eliu/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_swapper.py", line 10, in <module>
        import insightface
      File "/Users/eliu/stable-diffusion-webui/venv/lib/python3.10/site-packages/insightface/__init__.py", line 10, in <module>
        raise ImportError(
    ImportError: Unable to import dependency onnxruntime. 

---
01:01:11 - ReActor - STATUS - Running v0.5.0-a3
Loading weights [6ce0161689] from /Users/eliu/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors
Creating model from config: /Users/eliu/stable-diffusion-webui/configs/v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860
```

**Comment by Gourieff** [comment]
Updated, should work 🤞 please delete ReActor and try again
Unfortunately, I don't have AMD GPUs or MAC M# to test - only NVIDIA and Intel

**Comment by eliu9395** [comment]
I updated, but now the program just terminates itself before opening the webui when Reactor is installed.

Here's the current output:
```
Python 3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.0.40.1)]
Version: v1.6.0-2-g4afaaf8a
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
ReActor preheating... Device: CPU
Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
01:57:24 - ReActor - STATUS - Running v0.5.0-a4
Loading weights [6ce0161689] from /Users/eliu/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors
Creating model from config: /Users/eliu/stable-diffusion-webui/configs/v1-inference.yaml
Traceback (most recent call last):
  File "/Users/eliu/stable-diffusion-webui/launch.py", line 48, in <module>
    main()
  File "/Users/eliu/stable-diffusion-webui/launch.py", line 44, in main
    start()
  File "/Users/eliu/stable-diffusion-webui/modules/launch_utils.py", line 436, in start
    webui.webui()
  File "/Users/eliu/stable-diffusion-webui/webui.py", line 64, in webui
    shared.demo = ui.create_ui()
  File "/Users/eliu/stable-diffusion-webui/modules/ui.py", line 411, in create_ui
    custom_inputs = scripts.scripts_txt2img.setup_ui()
  File "/Users/eliu/stable-diffusion-webui/modules/scripts.py", line 541, in setup_ui
    self.setup_ui_for_section(None)
  File "/Users/eliu/stable-diffusion-webui/modules/scripts.py", line 527, in setup_ui_for_section
    self.create_script_ui(script)
  File "/Users/eliu/stable-diffusion-webui/modules/scripts.py", line 490, in create_script_ui
    control.custom_script_source = os.path.basename(script.filename)
AttributeError: 'str' object has no attribute 'custom_script_source'
Applying attention optimization: sub-quadratic... done.
Model loaded in 2.3s (load weights from disk: 0.2s, create model: 0.4s, apply weights to model: 1.3s, apply half(): 0.2s, calculate empty prompt: 0.2s).

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by Gourieff** [comment]
One more fix https://github.com/Gourieff/sd-webui-reactor/commit/0fee58d4bfafa5f85a41b21e31205666f85e795e, please try to delete and install again

**Comment by cuongloveit** [comment]
@Gourieff I have tried, but the error stills there

> One more fix [0fee58d](https://github.com/Gourieff/sd-webui-reactor/commit/0fee58d4bfafa5f85a41b21e31205666f85e795e), please try to delete and install again

**Comment by marekbujko** [comment]
Same problem on Linux today. I cloned stable-diffusion-webui again. Add ReActor extension and same problem:
ReActor - STATUS - Running v0.5.0-a4
Loading weights [6ce0161689] from /Users/eliu/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors
Creating model from config: /Users/eliu/stable-diffusion-webui/configs/v1-inference.yaml
Traceback (most recent call last):
  File "/Users/eliu/stable-diffusion-webui/launch.py", line 48, in <module>
    main()
  File "/Users/eliu/stable-diffusion-webui/launch.py", line 44, in main
    start()
  File "/Users/eliu/stable-diffusion-webui/modules/launch_utils.py", line 436, in start
    webui.webui()
  File "/Users/eliu/stable-diffusion-webui/webui.py", line 64, in webui
    shared.demo = ui.create_ui()
  File "/Users/eliu/stable-diffusion-webui/modules/ui.py", line 411, in create_ui
    custom_inputs = scripts.scripts_txt2img.setup_ui()
  File "/Users/eliu/stable-diffusion-webui/modules/scripts.py", line 541, in setup_ui
    self.setup_ui_for_section(None)
  File "/Users/eliu/stable-diffusion-webui/modules/scripts.py", line 527, in setup_ui_for_section
    self.create_script_ui(script)
  File "/Users/eliu/stable-diffusion-webui/modules/scripts.py", line 490, in create_script_ui
    control.custom_script_source = os.path.basename(script.filename)
AttributeError: 'str' object has no attribute 'custom_script_source'

**Comment by marekbujko** [comment]
Same problem on Linux today, I only update repo from A1111.
I cloned stable-diffusion-webui again. Add ReActor extension and same problem.

13:54:37 - ReActor - STATUS - Running v0.5.0-a5
Loading weights [ad2a33c361] from /home/administrator/Dokumenty/AI/stable-diffusion-webui/models/Stable-diffusion/2-1_768-ema-pruned.ckpt
Traceback (most recent call last):
  File "/home/administrator/Dokumenty/AI/stable-diffusion-webui/launch.py", line 48, in <module>
    main()
  File "/home/administrator/Dokumenty/AI/stable-diffusion-webui/launch.py", line 44, in main
    start()
  File "/home/administrator/Dokumenty/AI/stable-diffusion-webui/modules/launch_utils.py", line 436, in start
    webui.webui()
  File "/home/administrator/Dokumenty/AI/stable-diffusion-webui/webui.py", line 64, in webui
    shared.demo = ui.create_ui()
  File "/home/administrator/Dokumenty/AI/stable-diffusion-webui/modules/ui.py", line 411, in create_ui
    custom_inputs = scripts.scripts_txt2img.setup_ui()
  File "/home/administrator/Dokumenty/AI/stable-diffusion-webui/modules/scripts.py", line 541, in setup_ui
    self.setup_ui_for_section(None)
  File "/home/administrator/Dokumenty/AI/stable-diffusion-webui/modules/scripts.py", line 527, in setup_ui_for_section
    self.create_script_ui(script)
  File "/home/administrator/Dokumenty/AI/stable-diffusion-webui/modules/scripts.py", line 490, in create_script_ui
    control.custom_script_source = os.path.basename(script.filename)
AttributeError: 'str' object has no attribute 'custom_script_source'
Creating model from config: /home/administrator/Dokumenty/AI/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/configs/stable-diffusion/v2-inference-v.yaml
Applying attention optimization: InvokeAI... done.
Model loaded in 15.6s (load weights from disk: 11.2s, find config: 2.2s, create model: 0.2s, apply weights to model: 1.1s, calculate empty prompt: 0.7s).

And after this crash.

**Comment by Gourieff** [comment]
If you guys roll back to 0.4.3 - do you still get it?

**Comment by marekbujko** [comment]
> If you guys roll back to [0.4.3](https://github.com/Gourieff/sd-webui-reactor/releases/tag/v0.4.3) - do you still get it?

Linux - Ubuntu
14:09:02 - ReActor - STATUS - Running v0.4.3
![ReActor0 4 3](https://github.com/Gourieff/sd-webui-reactor/assets/114984527/5edc5021-f02a-4af4-8581-f83b8db99711)

**Comment by Gourieff** [comment]
> Does the Python version also need to be upgraded? I use 3.10.6.

No, 3.10.6 is ok

> 14:09:02 - ReActor - STATUS - Running v0.4.3

And A1111 lunches with no errors?

**Comment by marekbujko** [comment]
> > Does the Python version also need to be upgraded? I use 3.10.6.
> 
> No, 3.10.6 is ok
> 
> > 14:09:02 - ReActor - STATUS - Running v0.4.3
> 
> And A1111 lunches with no errors?

Yes, no error.

**Comment by xvoland** [comment]
```
Python 3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.0.40.1)]
Version: v1.6.0-266-g7e01f7e7
Commit hash: 7e01f7e7cf8dbba1d97459648174a41d50b9bac8
Fetching updates for midas...
Checking out commit for midas with hash: 1645b7e...
ReActor preheating... Device: CPU
Installing opencv-python
Installing opencv-python for pixel extension
Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --use-cpu interrogate --theme dark
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
2023-11-05 16:04:18,779 - ControlNet - INFO - ControlNet v1.1.415
ControlNet preprocessor location: /Volumes/xv-external/AI.StableDiffusion/stable-diffusion-webui/extensions/sd-webui-controlnet-sdxl/annotator/downloads
2023-11-05 16:04:18,835 - ControlNet - INFO - ControlNet v1.1.415
16:04:19 - ReActor - STATUS - Running v0.5.0-a5
```

It just won't start

macOS, M2

**Comment by marekbujko** [comment]
> ```
> Python 3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.0.40.1)]
> Version: v1.6.0-266-g7e01f7e7
> Commit hash: 7e01f7e7cf8dbba1d97459648174a41d50b9bac8
> Fetching updates for midas...
> Checking out commit for midas with hash: 1645b7e...
> ReActor preheating... Device: CPU
> Installing opencv-python
> Installing opencv-python for pixel extension
> Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --use-cpu interrogate --theme dark
> no module 'xformers'. Processing without...
> no module 'xformers'. Processing without...
> No module 'xformers'. Proceeding without it.
> Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
> [AddNet] Updating model hashes...
> 0it [00:00, ?it/s]
> [AddNet] Updating model hashes...
> 0it [00:00, ?it/s]
> 2023-11-05 16:04:18,779 - ControlNet - INFO - ControlNet v1.1.415
> ControlNet preprocessor location: /Volumes/external/AI.StableDiffusion/stable-diffusion-webui/extensions/sd-webui-controlnet-sdxl/annotator/downloads
> 2023-11-05 16:04:18,835 - ControlNet - INFO - ControlNet v1.1.415
> 16:04:19 - ReActor - STATUS - Running v0.5.0-a5
> 
> ...
> 
> Applying attention optimization: sub-quadratic... done.
> No Image data blocks found.
> Model loaded in 22.2s (load weights from disk: 0.8s, create model: 0.5s, apply weights to model: 17.2s, move model to device: 0.2s, load textual inversion embeddings: 0.4s, calculate empty prompt: 3.0s).
> 
> _>
> ```
> 
> It just won't start UI.
> 
> macOS, M2

Test if the old version 0.4.3 works for you:
https://github.com/Gourieff/sd-webui-reactor/archive/refs/tags/v0.4.3.zip

Delete sd-webui-reactor folder from stable-diffusion-webui/extensions. Extract v0.4.3 sd-webui-reactor to stable-diffusion-webui/extensions. Does this older version work?

**Comment by xvoland** [comment]
@marekbujko I answered here https://github.com/Gourieff/sd-webui-reactor/issues/176#issuecomment-1793749254
Yes it works, but there are still errors
