### ISSUE TITLE
    ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by swumagic** [Gourieff/sd-webui-reactor#182]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

*** Error running postprocess: M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_faceswap.py  4.57it/s]
    Traceback (most recent call last):
      File "M:\SD\git\sdxlwebui\modules\scripts.py", line 655, in postprocess
        script.postprocess(p, processed, *script_args)
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_faceswap.py", line 376, in postprocess
        result, output, swapped = swap_face(
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 448, in swap_face
        result_image = enhance_image(result_image, enhancement_options)
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 162, in enhance_image
        result_image = restore_face(result_image, enhancement_options)
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 123, in restore_face
        numpy_image = enhancement_options.face_restorer.restore(numpy_image)
      File "M:\SD\git\sdxlwebui\modules\gfpgan_model.py", line 121, in restore
        return gfpgan_fix_faces(np_image)
      File "M:\SD\git\sdxlwebui\modules\gfpgan_model.py", line 60, in gfpgan_fix_faces
        model = gfpgann()
      File "M:\SD\git\sdxlwebui\modules\gfpgan_model.py", line 38, in gfpgann
        latest_file = max(gfp_models, key=os.path.getctime)
    ValueError: max() arg is an empty sequence

### Steps to reproduce the problem

Downloading: "https://github.com/xinntao/facexlib/releases/download/v0.1.0/detection_Resnet50_Final.pth" to M:\SD\git\sdxlwebui\models\GFPGAN\detection_Resnet50_Final.pth

100%|███████████████████████████████████████████████████████████████████████████████| 104M/104M [00:23<00:00, 4.71MB/s]
Downloading: "https://github.com/xinntao/facexlib/releases/download/v0.2.2/parsing_parsenet.pth" to M:\SD\git\sdxlwebui\models\GFPGAN\parsing_parsenet.pth

100%|█████████████████████████████████████████████████████████████████████████████| 81.4M/81.4M [00:19<00:00, 4.47MB/s]
*** Error running postprocess: M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "M:\SD\git\sdxlwebui\modules\scripts.py", line 655, in postprocess
        script.postprocess(p, processed, *script_args)
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_faceswap.py", line 376, in postprocess
        result, output, swapped = swap_face(
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 448, in swap_face
        result_image = enhance_image(result_image, enhancement_options)
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 162, in enhance_image
        result_image = restore_face(result_image, enhancement_options)
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 123, in restore_face
        numpy_image = enhancement_options.face_restorer.restore(numpy_image)
      File "M:\SD\git\sdxlwebui\modules\gfpgan_model.py", line 121, in restore
        return gfpgan_fix_faces(np_image)
      File "M:\SD\git\sdxlwebui\modules\gfpgan_model.py", line 60, in gfpgan_fix_faces
        model = gfpgann()
      File "M:\SD\git\sdxlwebui\modules\gfpgan_model.py", line 47, in gfpgann
        model = gfpgan_constructor(model_path=model_file, upscale=1, arch='clean', channel_multiplier=2, bg_upsampler=None, device=devices.device_gfpgan)
      File "M:\SD\git\sdxlwebui\venv\lib\site-packages\gfpgan\utils.py", line 90, in __init__
        model_path = load_file_from_url(
      File "M:\SD\git\sdxlwebui\modules\gfpgan_model.py", line 101, in my_load_file_from_url
        return load_file_from_url_orig(**dict(kwargs, model_dir=model_file_path))
      File "M:\SD\git\sdxlwebui\venv\lib\site-packages\basicsr\utils\download_util.py", line 89, in load_file_from_url
        os.makedirs(model_dir, exist_ok=True)
      File "M:\SD\Python31011\lib\os.py", line 215, in makedirs
        makedirs(head, exist_ok=exist_ok)
      File "M:\SD\Python31011\lib\os.py", line 215, in makedirs
        makedirs(head, exist_ok=exist_ok)
      File "M:\SD\Python31011\lib\os.py", line 215, in makedirs
        makedirs(head, exist_ok=exist_ok)
      [Previous line repeated 4 more times]
      File "M:\SD\Python31011\lib\os.py", line 225, in makedirs
        mkdir(name, mode)
    OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'https:'

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [01:00<00:00,  3.00s/it]
Reusing loaded model darkSushiMixMix_225D.safetensors [cca17b08da] to load chilloutmix_NiPrunedFp32Fix.safetensors [fc2511737a]
Loading weights [fc2511737a] from M:\SD\sdwebui\models\Stable-diffusion\chilloutmix_NiPrunedFp32Fix.safetensors
Applying attention optimization: xformers... done.
Weights loaded in 6.0s (send model to cpu: 1.1s, load weights from disk: 0.3s, apply weights to model: 3.5s, move model to device: 1.0s).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.05it/s]
*** Error running postprocess: M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_faceswap.py  5.57it/s]
    Traceback (most recent call last):
      File "M:\SD\git\sdxlwebui\modules\scripts.py", line 655, in postprocess
        script.postprocess(p, processed, *script_args)
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_faceswap.py", line 376, in postprocess
        result, output, swapped = swap_face(
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 448, in swap_face
        result_image = enhance_image(result_image, enhancement_options)
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 162, in enhance_image
        result_image = restore_face(result_image, enhancement_options)
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 123, in restore_face
        numpy_image = enhancement_options.face_restorer.restore(numpy_image)
      File "M:\SD\git\sdxlwebui\modules\gfpgan_model.py", line 121, in restore
        return gfpgan_fix_faces(np_image)
      File "M:\SD\git\sdxlwebui\modules\gfpgan_model.py", line 60, in gfpgan_fix_faces
        model = gfpgann()
      File "M:\SD\git\sdxlwebui\modules\gfpgan_model.py", line 38, in gfpgann
        latest_file = max(gfp_models, key=os.path.getctime)
    ValueError: max() arg is an empty sequence

### Sysinfo

win10,sd1.6.1

### Relevant console log

```Shell
*** Error running postprocess: M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_faceswap.py  4.57it/s]
    Traceback (most recent call last):
      File "M:\SD\git\sdxlwebui\modules\scripts.py", line 655, in postprocess
        script.postprocess(p, processed, *script_args)
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_faceswap.py", line 376, in postprocess
        result, output, swapped = swap_face(
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 448, in swap_face
        result_image = enhance_image(result_image, enhancement_options)
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 162, in enhance_image
        result_image = restore_face(result_image, enhancement_options)
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 123, in restore_face
        numpy_image = enhancement_options.face_restorer.restore(numpy_image)
      File "M:\SD\git\sdxlwebui\modules\gfpgan_model.py", line 121, in restore
        return gfpgan_fix_faces(np_image)
      File "M:\SD\git\sdxlwebui\modules\gfpgan_model.py", line 60, in gfpgan_fix_faces
        model = gfpgann()
      File "M:\SD\git\sdxlwebui\modules\gfpgan_model.py", line 38, in gfpgann
        latest_file = max(gfp_models, key=os.path.getctime)
    ValueError: max() arg is an empty sequence
```

**Comment by swumagic** [comment]
EP Error D:\a_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:739 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

when using ['CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
Installing requirements for InsightFace: ['"insightface>=0.7.3"']
Installing requirements for Face Editor

MY PC win 11 ,RTX4090 ，cuda 12.3 ,cudnn 12.X

**Comment by swumagic** [comment]
MY PC win 11 ,RTX4090 ，cuda 11.8 ,cudnn 11.X  have a bug also
*** Error running postprocess: M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "M:\SD\git\sdxlwebui\modules\scripts.py", line 655, in postprocess
        script.postprocess(p, processed, *script_args)
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_faceswap.py", line 376, in postprocess
        result, output, swapped = swap_face(
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 448, in swap_face
        result_image = enhance_image(result_image, enhancement_options)
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 162, in enhance_image
        result_image = restore_face(result_image, enhancement_options)
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 123, in restore_face
        numpy_image = enhancement_options.face_restorer.restore(numpy_image)
      File "M:\SD\git\sdxlwebui\modules\gfpgan_model.py", line 121, in restore
        return gfpgan_fix_faces(np_image)
      File "M:\SD\git\sdxlwebui\modules\gfpgan_model.py", line 60, in gfpgan_fix_faces
        model = gfpgann()
      File "M:\SD\git\sdxlwebui\modules\gfpgan_model.py", line 38, in gfpgann
        latest_file = max(gfp_models, key=os.path.getctime)
    ValueError: max() arg is an empty sequence

**Comment by swumagic** [comment]
DOWNLOD CUDA 12.1 ,CUDA12.1 CUDNN12.x ok

**Comment by Eugeniusz-Gienek** [comment]
I have the same issue and CUDA 12.3. The solution doesn't work unfortunately :(
