### ISSUE TITLE
InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF 

### ISSUE THREAD

**Issue by protector131090** [Gourieff/sd-webui-reactor#186]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

dosnt work

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### Sysinfo

windows a1111

### Relevant console log

```Shell
21:12:02 - ReActor - STATUS - Working: source face index [0], target face index [0]████████████████████████▍    | 19/20 [00:01<00:00, 17.18it/s]
21:12:02 - ReActor - STATUS - Analyzing Source Image...
21:12:04 - ReActor - STATUS - Analyzing Target Image...
21:12:05 - ReActor - STATUS - Detecting Source Face, Index = 0
21:12:05 - ReActor - STATUS - Detected: -66- y.o. Male
*** Error running postprocess_image: C:\sd.webui\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\sd.webui\webui\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\sd.webui\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 433, in postprocess_image
        result, output, swapped = swap_face(
      File "C:\sd.webui\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 385, in swap_face
        face_swapper = getFaceSwapModel(model)
      File "C:\sd.webui\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 103, in getFaceSwapModel
        FS_MODEL = insightface.model_zoo.get_model(model_path, providers=PROVIDERS)
      File "C:\sd.webui\webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
        model = router.get_model(providers=providers, provider_options=provider_options)
      File "C:\sd.webui\webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 21, in patched_get_model
        session = PickableInferenceSession(self.onnx_file, **kwargs)
      File "C:\sd.webui\webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "C:\sd.webui\webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "C:\sd.webui\webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
        sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\sd.webui\webui\models\insightface\inswapper_128.onnx failed:Protobuf parsing failed.


Total progress: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.31it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 16.41it/s]
21:12:24 - ReActor - STATUS - Working: source face index [0], target face index [0]███████████████████▉         | 18/20 [00:00<00:00, 20.63it/s]
21:12:24 - ReActor - STATUS - Using Ready Source Face(s) Model...
21:12:24 - ReActor - STATUS - Analyzing Target Image...
21:12:25 - ReActor - STATUS - Detecting Source Face, Index = 0
21:12:25 - ReActor - STATUS - Detected: -66- y.o. Male
21:12:25 - ReActor - STATUS - Detecting Target Face, Index = 0
21:12:25 - ReActor - STATUS - Detected: -38- y.o. Male
21:12:25 - ReActor - STATUS - Swapping Source into Target
*** Error running postprocess_image: C:\sd.webui\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\sd.webui\webui\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\sd.webui\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 433, in postprocess_image
        result, output, swapped = swap_face(
      File "C:\sd.webui\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 414, in swap_face
        result = face_swapper.get(result, target_face, source_face)
    AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by protector131090** [comment]
redownloaded the model and it works fine
