### ISSUE TITLE
After some run, A1111 won't compute again

### ISSUE THREAD

**Issue by francoisbonnard** [Gourieff/sd-webui-reactor#194]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

After a couple of computes with ReActor (installed on my PC on A1111) A1111 won't run again, even if I un-checked ReActor.

  RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### Sysinfo

windows 11 / 16 Go RAM / nvidia Geforce RTX 4060

webui-user.bat :
set COMMANDLINE_ARGS=--xformers --theme dark --medvram

### Relevant console log

```Shell
---
*** Error completing request
*** Arguments: ('task(vbpi8270u18zxa9)', 'PHOTOREALISTIC, Rembrandt painting, portrait of toothpaste seller ', '', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 1024, 1024, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x000002E543424460>, 0, False, '', 0.8, 357509313, False, -1, 0, 0, 0, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002E51C929390>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002E543408280>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000002E54340A4A0>, <PIL.Image.Image image mode=RGB size=1024x1024 at 0x2E540E30DC0>, True, '0', '0', 'inswapper_128.onnx', 'GFPGAN', 1, True, 'None', 1, 1, False, True, 1, 2, 2, False, 0.5, True, False, 'CUDA', False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50) {}
    Traceback (most recent call last):
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\modules\call_queue.py", line 57, in f     
        res = list(func(*args, **kwargs))
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\modules\call_queue.py", line 36, in f     
        res = func(*args, **kwargs)
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img  
        processed = processing.process_images(p)
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\modules\processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
        return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\modules\processing.py", line 856, in process_images_inner
        p.setup_conds()
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\modules\processing.py", line 1309, in setup_conds
        super().setup_conds()
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\modules\processing.py", line 469, in setup_conds
        self.uc = self.get_conds_with_caching(prompt_parser.get_learned_conditioning, negative_prompts, total_steps, [self.cached_uc], self.extra_network_data)
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\modules\processing.py", line 455, in get_conds_with_caching
        cache[1] = function(shared.sd_model, required_prompts, steps, hires_steps, shared.opts.use_old_scheduling) 
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\modules\prompt_parser.py", line 189, in get_learned_conditioning
        conds = model.get_learned_conditioning(texts)
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\modules\sd_models_xl.py", line 31, in get_learned_conditioning
        c = self.conditioner(sdxl_conds, force_zero_embeddings=['txt'] if force_zero_negative_prompt else [])      
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
        result = forward_call(*args, **kwargs)
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\repositories\generative-models\sgm\modules\encoders\modules.py", line 141, in forward
        emb_out = embedder(batch[embedder.input_key])
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\modules\sd_hijack_clip.py", line 234, in forward
        z = self.process_tokens(tokens, multipliers)
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\modules\sd_hijack_clip.py", line 273, in process_tokens
        z = self.encode_with_transformers(tokens)
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\modules\sd_hijack_clip.py", line 349, in encode_with_transformers
        outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=self.wrapped.layer == "hidden")  
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 822, in forward
        return self.text_model(
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 730, in forward
        hidden_states = self.embeddings(input_ids=input_ids, position_ids=position_ids)
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 227, in forward
        inputs_embeds = self.token_embedding(input_ids)
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\modules\sd_hijack.py", line 321, in forward
        inputs_embeds = self.wrapped(input_ids)
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\sparse.py", line 162, in forward
        return F.embedding(
      File "C:\Users\franc\OneDrive\Documents\vsc\stable-diffusion-webui\venv\lib\site-packages\torch\nn\functional.py", line 2210, in embedding
        return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
    RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)

---
```

**Comment by Gourieff** [comment]
This error has nothing to do with the ReActor extension

According to your log you have no errors with ReActor

> return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
    RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)

Perhaps smth's wrong with embeddings you use, try to clear your prompt and load other model
Or maybe smth's wrong with your torch version, you can run A1111 with `--reinstall-torch` parameter (don't forget to delete this line afterwards)
