### ISSUE TITLE
onnxruntime-gpu ERROR 

### ISSUE THREAD

**Issue by Nsanity03** [Gourieff/sd-webui-reactor#206]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I tried to install this extension, only once I followed all the steps (installed visual studio) and then pasted the link on stable diffusion a1111 I get this error

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### Sysinfo

gpu: gtx 1070 8gb vram

### Relevant console log

```Shell
Installing requirements
Collecting onnxruntime-gpu
  Using cached onnxruntime_gpu-1.16.3-cp311-cp311-win_amd64.whl (141.5 MB)
Collecting coloredlogs (from onnxruntime-gpu)
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Requirement already satisfied: flatbuffers in c:\users\miche\stable-diffusion-webui\venv\lib\site-packages (from onnxruntime-gpu) (23.5.26)
Collecting numpy>=1.24.2 (from onnxruntime-gpu)
  Using cached numpy-1.26.2-cp311-cp311-win_amd64.whl (15.8 MB)
Requirement already satisfied: packaging in c:\users\miche\stable-diffusion-webui\venv\lib\site-packages (from onnxruntime-gpu) (23.2)
Requirement already satisfied: protobuf in c:\users\miche\stable-diffusion-webui\venv\lib\site-packages (from onnxruntime-gpu) (3.20.3)
Requirement already satisfied: sympy in c:\users\miche\stable-diffusion-webui\venv\lib\site-packages (from onnxruntime-gpu) (1.12)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime-gpu)
  Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Requirement already satisfied: mpmath>=0.19 in c:\users\miche\stable-diffusion-webui\venv\lib\site-packages (from sympy->onnxruntime-gpu) (1.3.0)
Requirement already satisfied: pyreadline3 in c:\users\miche\stable-diffusion-webui\venv\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime-gpu) (3.4.1)
Installing collected packages: numpy, humanfriendly, coloredlogs, onnxruntime-gpu
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5
ReActor preheating... Error: The 'onnxruntime-gpu' distribution was not found and is required by the application
Device: CUDA

        +---------------------------------+
        --- PLEASE, RESTART the Server! ---
        +---------------------------------+
Launching Web UI with arguments: --xformers
2023-11-21 20:03:41,686 - ControlNet - INFO - ControlNet v1.1.418
ControlNet preprocessor location: C:\Users\miche\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-11-21 20:03:41,750 - ControlNet - INFO - ControlNet v1.1.418
*** Error loading script: console_log_patch.py
    Traceback (most recent call last):
      File "C:\Users\miche\stable-diffusion-webui\venv\Lib\site-packages\insightface\__init__.py", line 8, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\miche\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\miche\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\miche\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 4, in <module>
        import insightface
      File "C:\Users\miche\stable-diffusion-webui\venv\Lib\site-packages\insightface\__init__.py", line 10, in <module>
        raise ImportError(
    ImportError: Unable to import dependency onnxruntime.

---
*** Error loading script: reactor_api.py
    Traceback (most recent call last):
      File "C:\Users\miche\stable-diffusion-webui\venv\Lib\site-packages\insightface\__init__.py", line 8, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\miche\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\miche\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\miche\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_api.py", line 17, in <module>
        from scripts.reactor_swapper import EnhancementOptions, swap_face
      File "C:\Users\miche\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 10, in <module>
        import insightface
      File "C:\Users\miche\stable-diffusion-webui\venv\Lib\site-packages\insightface\__init__.py", line 10, in <module>
        raise ImportError(
    ImportError: Unable to import dependency onnxruntime.

---
*** Error loading script: reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\Users\miche\stable-diffusion-webui\venv\Lib\site-packages\insightface\__init__.py", line 8, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\miche\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\miche\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\miche\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 31, in <module>
        from scripts.reactor_swapper import EnhancementOptions, swap_face, check_process_halt, reset_messaged
      File "C:\Users\miche\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 10, in <module>
        import insightface
      File "C:\Users\miche\stable-diffusion-webui\venv\Lib\site-packages\insightface\__init__.py", line 10, in <module>
        raise ImportError(
    ImportError: Unable to import dependency onnxruntime.

---
*** Error loading script: reactor_swapper.py
    Traceback (most recent call last):
      File "C:\Users\miche\stable-diffusion-webui\venv\Lib\site-packages\insightface\__init__.py", line 8, in <module>
        import onnxruntime
    ModuleNotFoundError: No module named 'onnxruntime'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\miche\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\miche\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\miche\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 10, in <module>
        import insightface
      File "C:\Users\miche\stable-diffusion-webui\venv\Lib\site-packages\insightface\__init__.py", line 10, in <module>
        raise ImportError(
    ImportError: Unable to import dependency onnxruntime.

---
20:03:41 - ReActor - STATUS - Running v0.5.0-b2
Loading weights [bff4610d23] from C:\Users\miche\stable-diffusion-webui\models\Stable-diffusion\epicrealism_naturalSin.safetensors
Running on local URL:  http://127.0.0.1:7860
```

**Comment by Gourieff** [comment]
> Device: CUDA
>
>        +---------------------------------+
>        --- PLEASE, RESTART the Server! ---
>        +---------------------------------+

Just do it

**Comment by dugmai** [comment]
Hi Ad! Please help me.
*** Error loading script: reactor_swapper.py
    Traceback (most recent call last):
      File "C:\ST\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\ST\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\ST\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 10, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

**Comment by Gourieff** [comment]
https://github.com/Gourieff/sd-webui-reactor/issues?q=is%3Aissue+is%3Aclosed+ModuleNotFoundError%3A+No+module+named+%27insightface%27
