### ISSUE TITLE
 ImportError: cannot import name 'FaceArea' from 'scripts.entities.face' (M:\SD\sdwebui\extensions\sd-face-editor\scripts\entities\face.py)

### ISSUE THREAD

**Issue by swumagic** [Gourieff/sd-webui-reactor#211]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

*** Error loading script: reactor_api.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "M:\SD\sdwebui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "M:\SD\sdwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_api.py", line 17, in <module>
        from scripts.reactor_swapper import EnhancementOptions, swap_face
      File "M:\SD\sdwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 25, in <module>
        from modules.reactor_mask import apply_face_mask
      File "M:\SD\sdwebui\extensions\sd-webui-roop-nsfw\modules\reactor_mask.py", line 9, in <module>
        from scripts.entities.face import FaceArea
    ImportError: cannot import name 'FaceArea' from 'scripts.entities.face' (M:\SD\sdwebui\extensions\sd-face-editor\scripts\entities\face.py)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error loading script: reactor_faceswap.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "M:\SD\sdwebui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "M:\SD\sdwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_faceswap.py", line 31, in <module>
        from scripts.reactor_swapper import (
      File "M:\SD\sdwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 25, in <module>
        from modules.reactor_mask import apply_face_mask
      File "M:\SD\sdwebui\extensions\sd-webui-roop-nsfw\modules\reactor_mask.py", line 9, in <module>
        from scripts.entities.face import FaceArea
    ImportError: cannot import name 'FaceArea' from 'scripts.entities.face' (M:\SD\sdwebui\extensions\sd-face-editor\scripts\entities\face.py)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

---
*** Error loading script: reactor_swapper.py
    Traceback (most recent call last):
      File "M:\SD\sdwebui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "M:\SD\sdwebui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "M:\SD\sdwebui\extensions\sd-webui-roop-nsfw\scripts\reactor_swapper.py", line 25, in <module>
        from modules.reactor_mask import apply_face_mask
      File "M:\SD\sdwebui\extensions\sd-webui-roop-nsfw\modules\reactor_mask.py", line 9, in <module>
        from scripts.entities.face import FaceArea
    ImportError: cannot import name 'FaceArea' from 'scripts.entities.face' (M:\SD\sdwebui\extensions\sd-face-editor\scripts\entities\face.py)
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

### Steps to reproduce the problem

 ImportError: cannot import name 'FaceArea' from 'scripts.entities.face' (M:\SD\sdwebui\extensions\sd-face-editor\scripts\entities\face.py)

### Sysinfo

Win10，py310,gpu2060

### Relevant console log

```Shell
ImportError: cannot import name 'FaceArea' from 'scripts.entities.face' (M:\SD\sdwebui\extensions\sd-face-editor\scripts\entities\face.py)
```

**Comment by Gourieff** [comment]
Fixed https://github.com/Gourieff/sd-webui-reactor/commit/70479479b314aa84dc37bda01a44988adabdb9b4

**Comment by swumagic** [comment]
Thank you!
