### ISSUE TITLE
[SOLVED] assert 'detection' in self.models | AssertionError

### ISSUE THREAD

**Issue by mingren713** [Gourieff/sd-webui-reactor#243]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Installed and updated. Checked everything for correct files in folders. Reran the extension download. Done all that has been troubleshot here. Still no fix.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### Sysinfo

A1111 WebUI

### Relevant console log

```Shell
*** Error running postprocess_image: E:\sd-webui-aki-v4.5\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "E:\sd-webui-aki-v4.5\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "E:\sd-webui-aki-v4.5\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 370, in postprocess_image
        result, output, swapped = swap_face(
      File "E:\sd-webui-aki-v4.5\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 506, in swap_face
        source_faces = analyze_faces(source_img)
      File "E:\sd-webui-aki-v4.5\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 270, in analyze_faces
        face_analyser = copy.deepcopy(getAnalysisModel())
      File "E:\sd-webui-aki-v4.5\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 115, in getAnalysisModel
        ANALYSIS_MODEL = insightface.app.FaceAnalysis(
      File "E:\sd-webui-aki-v4.5\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 59, in patched_faceanalysis_init
        assert 'detection' in self.models
    AssertionError
```

**Comment by mingren713** [comment]
> Try to download buffalo_l models again (https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip) and put all five models into "models\insightface\models\buffalo_l"

It works!Thank you so much for your help！I really appreciate it!

**Comment by chinalinshen** [comment]
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\annotator\downloads\insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 [1, 3, 192, 192] 0.0 1.0
Traceback (most recent call last):
  File "D:\sd-webui-aki-v4.9\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\sd-webui-aki-v4.9\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\sd-webui-aki-v4.9\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\sd-webui-aki-v4.9\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\sd-webui-aki-v4.9\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\sd-webui-aki-v4.9\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\sd-webui-aki-v4.9\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 951, in run_annotator
    result = preprocessor.cached_call(
  File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\supported_preprocessor.py", line 198, in cached_call
    result = self._cached_call(input_image, *args, **kwargs)
  File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\utils.py", line 82, in decorated_func
    return cached_func(*args, **kwargs)
  File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\utils.py", line 66, in cached_func
    return func(*args, **kwargs)
  File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\supported_preprocessor.py", line 211, in _cached_call
    return self(*args, **kwargs)
  File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\legacy_preprocessors.py", line 105, in __call__
    result, is_image = self.call_function(
  File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 768, in face_id_plus
    face_embed, _ = g_insight_face_model.run_model(img)
  File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 696, in run_model
    self.load_model()
  File "D:\sd-webui-aki-v4.9\extensions\sd-webui-controlnet\scripts\preprocessor\legacy\processor.py", line 688, in load_model
    self.model = FaceAnalysis(
  File "D:\sd-webui-aki-v4.9\python\lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
AssertionError
![b2b6682fc1a0554f8d9a9f51497e282](https://github.com/user-attachments/assets/09584111-b123-4536-946c-4eb7bd0853f3)
Why didn't it work for my problem？
