### ISSUE TITLE
When you launch SD WebUI do you see the line "ReActor preheating... **Device: CUDA**"?

### ISSUE THREAD

**Issue by AmroSharafAldeen** [Gourieff/sd-webui-reactor#249]
When you launch SD WebUI do you see the line "ReActor preheating... **Device: CUDA**"?
Do you have this in the Settings tab?
![изображение](https://github.com/Gourieff/sd-webui-reactor/assets/85128026/f43900a0-9c27-44ac-9357-7f102ea5fecd)

_Originally posted by @Gourieff in https://github.com/Gourieff/sd-webui-reactor/discussions/203#discussioncomment-7621135_

**Comment by AmroSharafAldeen** [comment]
i have the ReActor preheating... Device: Cuda line and when i try to face swap an image, i get these errors

*** Error running postprocess_image: D:\AI Tools\Programs\Stable Diffusion Automatic1111\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
Traceback (most recent call last):
File "D:\AI Tools\Programs\Stable Diffusion Automatic1111\webui\modules\scripts.py", line 675, in postprocess_image
script.postprocess_image(p, pp, *script_args)
File "D:\AI Tools\Programs\Stable Diffusion Automatic1111\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 571, in postprocess_image
result, output, swapped = swap_face(
File "D:\AI Tools\Programs\Stable Diffusion Automatic1111\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 512, in swap_face
result_image = enhance_image(result_image, enhancement_options)
File "D:\AI Tools\Programs\Stable Diffusion Automatic1111\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 170, in enhance_image
result_image = restore_face(result_image, enhancement_options)
File "D:\AI Tools\Programs\Stable Diffusion Automatic1111\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 127, in restore_face
numpy_image = codeformer_model.codeformer.restore(
File "D:\AI Tools\Programs\Stable Diffusion Automatic1111\webui\modules\codeformer_model.py", line 81, in restore
self.create_models()
File "D:\AI Tools\Programs\Stable Diffusion Automatic1111\webui\modules\codeformer_model.py", line 64, in create_models
face_helper = FaceRestoreHelper(1, face_size=512, crop_ratio=(1, 1), det_model='retinaface_resnet50', save_ext='png', use_parse=True, device=devices.device_codeformer)
File "D:\AI Tools\Programs\Stable Diffusion Automatic1111\webui\repositories\CodeFormer\facelib\utils\face_restoration_helper.py", line 109, in init
self.face_parse = init_parsing_model(model_name='parsenet', device=self.device)
File "D:\AI Tools\Programs\Stable Diffusion Automatic1111\webui\repositories\CodeFormer\facelib\parsing_init_.py", line 19, in init_parsing_model
load_net = torch.load(model_path, map_location=lambda storage, loc: storage)
File "D:\AI Tools\Programs\Stable Diffusion Automatic1111\webui\modules\safe.py", line 108, in load
return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
File "D:\AI Tools\Programs\Stable Diffusion Automatic1111\webui\modules\safe.py", line 156, in load_with_extra
return unsafe_torch_load(filename, *args, **kwargs)
File "D:\AI Tools\Programs\Stable Diffusion Automatic1111\system\python\lib\site-packages\torch\serialization.py", line 815, in load
return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
File "D:\AI Tools\Programs\Stable Diffusion Automatic1111\system\python\lib\site-packages\torch\serialization.py", line 1051, in _legacy_load
typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 1214777 more bytes. The file might be corrupted.

**Comment by Gourieff** [comment]
> RuntimeError: unexpected EOF, expected 1214777 more bytes. The file might be corrupted.

There's smth wrong with detection model
Try to delete both files in models\Codeformer and let the script to download them again after restart during the next processing
