### ISSUE TITLE
InputAccordion is not defined

### ISSUE THREAD

**Issue by lfedesp** [Gourieff/sd-webui-reactor#269]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

after installing the update, A1111 wouldn't start any more as long as ReActor is in the extentions folder

### Steps to reproduce the problem

after updating ReActor on MacOS

### Sysinfo

A1111 in MacOS

### Relevant console log

```Shell
AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /Users/federicosolis/Documents/STABLE_DIFFUSION/stable-diffusion-webui/launc │
│ h.py:39 in <module>                                                          │
│                                                                              │
│   36                                                                         │
│   37                                                                         │
│   38 if __name__ == "__main__":                                              │
│ ❱ 39 │   main()                                                              │
│   40                                                                         │
│                                                                              │
│ /Users/federicosolis/Documents/STABLE_DIFFUSION/stable-diffusion-webui/launc │
│ h.py:35 in main                                                              │
│                                                                              │
│   32 │   if args.test_server:                                                │
│   33 │   │   configure_for_tests()                                           │
│   34 │                                                                       │
│ ❱ 35 │   start()                                                             │
│   36                                                                         │
│   37                                                                         │
│   38 if __name__ == "__main__":                                              │
│                                                                              │
│ /Users/federicosolis/Documents/STABLE_DIFFUSION/stable-diffusion-webui/modul │
│ es/launch_utils.py:394 in start                                              │
│                                                                              │
│   391 │   if '--nowebui' in sys.argv:                                        │
│   392 │   │   webui.api_only()                                               │
│   393 │   else:                                                              │
│ ❱ 394 │   │   webui.webui()                                                  │
│   395                                                                        │
│                                                                              │
│ /Users/federicosolis/Documents/STABLE_DIFFUSION/stable-diffusion-webui/webui │
│ .py:393 in webui                                                             │
│                                                                              │
│   390 │   │   modules.script_callbacks.before_ui_callback()                  │
│   391 │   │   startup_timer.record("scripts before_ui_callback")             │
│   392 │   │                                                                  │
│ ❱ 393 │   │   shared.demo = modules.ui.create_ui()                           │
│   394 │   │   startup_timer.record("create ui")                              │
│   395 │   │                                                                  │
│   396 │   │   if not cmd_opts.no_gradio_queue:                               │
│                                                                              │
│ /Users/federicosolis/Documents/STABLE_DIFFUSION/stable-diffusion-webui/modul │
│ es/ui.py:1061 in create_ui                                                   │
│                                                                              │
│   1058 │   modules.scripts.scripts_current = None                            │
│   1059 │                                                                     │
│   1060 │   with gr.Blocks(analytics_enabled=False) as extras_interface:      │
│ ❱ 1061 │   │   ui_postprocessing.create_ui()                                 │
│   1062 │                                                                     │
│   1063 │   with gr.Blocks(analytics_enabled=False) as pnginfo_interface:     │
│   1064 │   │   with gr.Row().style(equal_height=False):                      │
│                                                                              │
│ /Users/federicosolis/Documents/STABLE_DIFFUSION/stable-diffusion-webui/modul │
│ es/ui_postprocessing.py:25 in create_ui                                      │
│                                                                              │
│   22 │   │   │                                                               │
│   23 │   │   │   submit = gr.Button('Generate', elem_id="extras_generate", v │
│   24 │   │   │                                                               │
│ ❱ 25 │   │   │   script_inputs = scripts.scripts_postproc.setup_ui()         │
│   26 │   │                                                                   │
│   27 │   │   with gr.Column():                                               │
│   28 │   │   │   result_images, html_info_x, html_info, html_log = ui_common │
│                                                                              │
│ /Users/federicosolis/Documents/STABLE_DIFFUSION/stable-diffusion-webui/modul │
│ es/scripts_postprocessing.py:113 in setup_ui                                 │
│                                                                              │
│   110 │   │                                                                  │
│   111 │   │   for script in self.scripts_in_preferred_order():               │
│   112 │   │   │   with gr.Row() as group:                                    │
│ ❱ 113 │   │   │   │   self.create_script_ui(script, inputs)                  │
│   114 │   │   │                                                              │
│   115 │   │   │   script.group = group                                       │
│   116                                                                        │
│                                                                              │
│ /Users/federicosolis/Documents/STABLE_DIFFUSION/stable-diffusion-webui/modul │
│ es/scripts_postprocessing.py:84 in create_script_ui                          │
│                                                                              │
│    81 │   │                                                                  │
│    82 │   │   script.controls = wrap_call(script.ui, script.filename, "ui")  │
│    83 │   │                                                                  │
│ ❱  84 │   │   for control in script.controls.values():                       │
│    85 │   │   │   control.custom_script_source = os.path.basename(script.fil │
│    86 │   │                                                                  │
│    87 │   │   inputs += list(script.controls.values())                       │
╰──────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'values'
Applying attention optimization: InvokeAI... done.
Model loaded in 5.5s (load weights from disk: 0.5s, create model: 0.8s, apply weights to model: 1.6s, apply half(): 0.9s, move model to device: 1.2s, calculate empty prompt: 0.4s).
```

**Comment by Gourieff** [comment]
This means that you use rather old version of A1111 or SD.Next
Just update your SD-WebUI to latest version
If you don't want to update it for some reason - you can return ReActor to the previous commit (v0.6.0-alpha2):
- Open Console and run:

      git checkout ed66d91

**Comment by ZeroCool22** [comment]
> This means that you use rather old version of A1111 or SD.Next Just update your SD-WebUI to latest version If you don't want to update it for some reason - you can return ReActor to the previous commit (v0.6.0-alpha2):
> 
>     * Open Terminal in the ReActor's folder and run:
>       ```
>       git checkout ed66d91
>       ```

Here?:

stable-diffusion-webui\extensions\sd-webui-reactor

**Comment by ZeroCool22** [comment]
> This means that you use rather old version of A1111 or SD.Next Just update your SD-WebUI to latest version If you don't want to update it for some reason - you can return ReActor to the previous commit (v0.6.0-alpha2):
> 
>     * Open Terminal in the ReActor's folder and run:
>       ```
>       git checkout ed66d91
>       ```

I have this error now:

```
DiffusionWrapper has 859.52 M params.
*** Failed reading extension data from Git repository (sd-webui-reactor)
    Traceback (most recent call last):
      File "C:\Users\ZeroCool22\Desktop\AutoRespaldo\stable-diffusion-webui\modules\extensions.py", line 65, in do_read_info_from_repo
        if repo.active_branch:
      File "C:\Users\ZeroCool22\Desktop\AutoRespaldo\stable-diffusion-webui\venv\lib\site-packages\git\repo\base.py", line 881, in active_branch
        return self.head.reference
      File "C:\Users\ZeroCool22\Desktop\AutoRespaldo\stable-diffusion-webui\venv\lib\site-packages\git\refs\symbolic.py", line 309, in _get_reference
        raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
    TypeError: HEAD is a detached symbolic reference as it points to 'ed66d918190a296c745265a01c090e3e3dbc2cde'

---
preload_extensions_git_metadata for 11 extensions took 1.13s
Loading VAE weights from commandline argument: F:\Stable-diffusion\vae-ft-mse-840000-ema-pruned.ckpt
Applying attention optimization: xformers... done.
```
