### ISSUE TITLE
NoneType object has no attribute get - when using image as a source

### ISSUE THREAD

**Issue by slavasav** [Gourieff/sd-webui-reactor#278]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Trying to face swap with recent Automatic1111 getting this:
```
*** Error running postprocess_image: C:\Users\myuser\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\Users\myuser\stable-diffusion-webui\modules\scripts.py", line 774, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\Users\myuser\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 376, in postprocess_image
        result, output, swapped = swap_face(
      File "C:\Users\myuser\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 581, in swap_face
        result_image, output, swapped = operate(source_img,target_img,target_img_orig,model,source_faces_index,faces_index,source_faces,target_faces,gender_source,gender_target,source_face,wrong_gender,source_age,source_gender,output,swapped,mask_face,entire_mask_image,enhancement_options)
      File "C:\Users\myuser\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 672, in operate
        swapped_image = face_swapper.get(result, target_face, source_face)
    AttributeError: 'NoneType' object has no attribute 'get'
```

I did follow the debugging instructions [here ](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md#v-invalid_protobuf--load-model-from-modelsinsightfaceinswapper_128onnx-failedprotobuf-parsing-failed-or-attributeerror-nonetype-object-has-no-attribute-get-or-attributeerror-faceswapscript-object-has-no-attribute-save_original) and updated all python packages, same result

### Steps to reproduce the problem

1. Go to stable diffusion web ui, Choose img2img, inpaint
2. DargNDrop the source image
3. Enable reactor
4. DragNDrop the face source image
5. Observe the exeption in command line window:
```
21:30:02 - ReActor - STATUS - Detected: -22- y.o. Male
21:30:02 - ReActor - STATUS - Swapping Source into Target
*** Error running postprocess_image: C:\Users\myuser\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
```

### Sysinfo

[sysinfo-2023-12-21-20-31.json](https://github.com/Gourieff/sd-webui-reactor/files/13745993/sysinfo-2023-12-21-20-31.json)

### Relevant console log

```Shell
21:30:00 - ReActor - STATUS - Working: source face index [0], target face index [0]████| 16/16 [00:02<00:00,  6.58it/s]
21:30:00 - ReActor - STATUS - Using Hashed Source Face(s) Model...
21:30:00 - ReActor - STATUS - Analyzing Target Image...
21:30:02 - ReActor - STATUS - Detecting Source Face, Index = 0
21:30:02 - ReActor - STATUS - Source Face 0: Detected Gender -M-
21:30:02 - ReActor - STATUS - OK - Detected Gender matches Condition
21:30:02 - ReActor - STATUS - Detected: -36- y.o. Male
21:30:02 - ReActor - STATUS - Detecting Target Face, Index = 0
21:30:02 - ReActor - STATUS - Target Face 0: Detected Gender -M-
21:30:02 - ReActor - STATUS - OK - Detected Gender matches Condition
21:30:02 - ReActor - STATUS - Detected: -22- y.o. Male
21:30:02 - ReActor - STATUS - Swapping Source into Target
*** Error running postprocess_image: C:\Users\myuser\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\Users\myuser\stable-diffusion-webui\modules\scripts.py", line 774, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\Users\myuser\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 376, in postprocess_image
        result, output, swapped = swap_face(
      File "C:\Users\myuser\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 581, in swap_face
        result_image, output, swapped = operate(source_img,target_img,target_img_orig,model,source_faces_index,faces_index,source_faces,target_faces,gender_source,gender_target,source_face,wrong_gender,source_age,source_gender,output,swapped,mask_face,entire_mask_image,enhancement_options)
      File "C:\Users\myuser\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 672, in operate
        swapped_image = face_swapper.get(result, target_face, source_face)
    AttributeError: 'NoneType' object has no attribute 'get'

---
```

**Comment by slavasav** [comment]
I made it work by placing inswapper_128.onnx under stable-diffusion-webui\models\reactor (instructions mention stable-diffusion-webui\models\insightface instead).

**Comment by faraday** [comment]
@slavasav Could you be more specific about what you did to mitigate?
