### ISSUE TITLE
Error loading some scripts

### ISSUE THREAD

**Issue by Sierra144** [Gourieff/sd-webui-reactor#284]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

The Reactor module don't open in Automatic 1111

### Steps to reproduce the problem

1. Go to run.bat (A1111 Portable)
2. Press ....
3. ...

### Sysinfo

Platform:
arch: AMD64
cpu: Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
system: Windows
release: Windows-10-10.0.22621-SP0
python: 3.10.6

Version :
app: stable-diffusion-webui.git
updated: 2023-12-16
hash: cf2772fa
url: https://github.com/AUTOMATIC1111/stable-diffusion-webui.git/tree/master

Torch :
2.0.1+cu118 autocast  half

GPU : 
device: NVIDIA GeForce RTX 2080 SUPER (1) (compute_37) (7, 5)
cuda: 11.8
cudnn: 8700
driver: 531.18

### Relevant console log

```Shell
*** Error loading script: reactor_api.py
    Traceback (most recent call last):
      File "S:\AI\A1111\webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "S:\AI\A1111\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "S:\AI\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_api.py", line 17, in <module>
        from scripts.reactor_swapper import EnhancementOptions, swap_face
      File "S:\AI\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 10, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_faceswap.py
    Traceback (most recent call last):
      File "S:\AI\A1111\webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "S:\AI\A1111\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "S:\AI\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 18, in <module>
        from reactor_ui import ui_main, ui_upscale, ui_tools, ui_settings
      File "S:\AI\A1111\webui\extensions\sd-webui-reactor\reactor_ui\__init__.py", line 2, in <module>
        import reactor_ui.reactor_tools_ui as ui_tools
      File "S:\AI\A1111\webui\extensions\sd-webui-reactor\reactor_ui\reactor_tools_ui.py", line 2, in <module>
        from scripts.reactor_swapper import build_face_model
      File "S:\AI\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 10, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_helpers.py
    Traceback (most recent call last):
      File "S:\AI\A1111\webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "S:\AI\A1111\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "S:\AI\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in <module>
        from insightface.app.common import Face
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_logger.py
    Traceback (most recent call last):
      File "S:\AI\A1111\webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "S:\AI\A1111\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "S:\AI\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_logger.py", line 7, in <module>
        from scripts.reactor_helpers import addLoggingLevel
      File "S:\AI\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in <module>
        from insightface.app.common import Face
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_swapper.py
    Traceback (most recent call last):
      File "S:\AI\A1111\webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "S:\AI\A1111\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "S:\AI\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 10, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_version.py
    Traceback (most recent call last):
      File "S:\AI\A1111\webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "S:\AI\A1111\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "S:\AI\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_version.py", line 4, in <module>
        from scripts.reactor_logger import logger, get_Run, set_Run
      File "S:\AI\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_logger.py", line 7, in <module>
        from scripts.reactor_helpers import addLoggingLevel
      File "S:\AI\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in <module>
        from insightface.app.common import Face
    ModuleNotFoundError: No module named 'insightface'

---
Loading weights [ec6f68ea63] from S:\AI\A1111\webui\models\Stable-diffusion\lyriel_v16.safetensors
Creating model from config: S:\AI\A1111\webui\configs\v1-inference.yaml
Applying attention optimization: Doggettx... done.
Model loaded in 3.3s (load weights from disk: 0.4s, create model: 0.4s, apply weights to model: 1.7s, calculate empty prompt: 0.6s).
2023-12-26 20:28:06,625 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2023-12-26 20:28:06,628 - modelscope - INFO - Loading ast index from C:\Users\sylva\.cache\modelscope\ast_indexer
2023-12-26 20:28:06,710 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 9dc13d4378f28863996df111cf446472 and a total number of 946 components indexed
*** Error executing callback ui_tabs_callback for S:\AI\A1111\webui\extensions\facechain\scripts\facechain_sdwebui.py
    Traceback (most recent call last):
      File "S:\AI\A1111\webui\modules\script_callbacks.py", line 166, in ui_tabs_callback
        res += c.callback() or []
      File "S:\AI\A1111\webui\extensions\facechain\scripts\facechain_sdwebui.py", line 15, in on_ui_tabs
        import app
      File "S:\AI\A1111\webui\extensions\facechain\app.py", line 16, in <module>
        from facechain.inference import preprocess_pose, GenPortrait
      File "S:\AI\A1111\webui\extensions\facechain\facechain\inference.py", line 10, in <module>
        from diffusers import StableDiffusionPipeline, StableDiffusionControlNetPipeline, ControlNetModel, \
    ImportError: cannot import name 'StableDiffusionXLPipeline' from 'diffusers' (S:\AI\A1111\system\python\lib\site-packages\diffusers\__init__.py)

---
*** Failed reading extension data from Git repository (sd-webui-reactor)
    Traceback (most recent call last):
      File "S:\AI\A1111\webui\modules\extensions.py", line 131, in do_read_info_from_repo
        if repo.active_branch:
      File "S:\AI\A1111\system\python\lib\site-packages\git\repo\base.py", line 896, in active_branch
        return self.head.reference
      File "S:\AI\A1111\system\python\lib\site-packages\git\refs\symbolic.py", line 309, in _get_reference
        raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
    TypeError: HEAD is a detached symbolic reference as it points to 'ed66d918190a296c745265a01c090e3e3dbc2cde'

---
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 41.9s (prepare environment: 26.4s, import torch: 3.2s, import gradio: 1.1s, setup paths
```

**Comment by Pervertica** [comment]
https://github.com/Gourieff/sd-webui-reactor?tab=readme-ov-file#insightfacebuild  
I think it's a visual studio problem. try the method above instead of using visual studio.  
it worked for me.

**Comment by Sierra144** [comment]
Thank you man ! I was sure I'd done this process yesterday, but when in doubt, I redid the process today and it's working now.

**Comment by Sierra144** [comment]
Problem solve.

**Comment by kassabro** [comment]
how did you solve this
