### ISSUE TITLE
Error running postprocess_image

### ISSUE THREAD

**Issue by HolisticPanda** [Gourieff/sd-webui-reactor#290]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Not sure what it's telling me here. It seems there's an error and it's telling me there are errors on line 774, 376, 581, and 672. However I don't fully understand what the error message is telling me or what it wants me to change. I've tried to google but I only get issues for "Roop". (When I wrote this first line I had Pytorch 1.12.3 and after I updated it I got the other errors listed below)

I have updated Pytorch to 2.0.1 and after I updated it I got more errors in which it added that there were errors with lines, 643, 128, 96, 21, 25, 419, and 452 (but it removed an error massage with line 672). I first upgraded it to the latest version and got the same error and then downgraded to see if that changed anything (it didn't).

I have deleted the venv folder, I've checked that the postprocessing.py is written image = image.open(img.name) instead of image = image.open(img)

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### Sysinfo

Windows 10, brave browser, Nvidia RTX 3070, using latest A1111 and using module "realisticVisionV60B1_v60B1VAE.safetensors [e5f3cbc5f7]
And this is what it says at the bottom of my SD page "version: [v1.7.0]  •  python: 3.10.7  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.41.2  •  checkpoint: [e5f3cbc5f7]

### Relevant console log

```Shell
venv "C:\Users\chris\Desktop\Work\SuperStableDiffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Installing xformers
ReActor preheating... Device: CUDA
Launching Web UI with arguments: --xformers
Style database not found: C:\Users\chris\Desktop\Work\SuperStableDiffusion\stable-diffusion-webui\styles.csv
23:05:18 - ReActor - STATUS - Running v0.6.0-a4
Loading weights [e5f3cbc5f7] from C:\Users\chris\Desktop\Work\SuperStableDiffusion\stable-diffusion-webui\models\Stable-diffusion\realisticVisionV60B1_v60B1VAE.safetensors
Creating model from config: C:\Users\chris\Desktop\Work\SuperStableDiffusion\stable-diffusion-webui\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 15.3s (prepare environment: 6.2s, import torch: 2.8s, import gradio: 1.0s, setup paths: 0.9s, initialize shared: 0.2s, other imports: 0.6s, setup codeformer: 0.1s, load scripts: 2.3s, create ui: 0.6s, gradio launch: 0.4s).
Applying attention optimization: xformers... done.
Model loaded in 9.4s (load weights from disk: 0.7s, create model: 0.3s, apply weights to model: 4.3s, apply half(): 2.0s, load VAE: 0.1s, calculate empty prompt: 1.8s).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.32it/s]
23:05:52 - ReActor - STATUS - Working: source face index [0], target face index [0]████| 20/20 [00:03<00:00,  4.75it/s]
23:05:52 - ReActor - STATUS - Analyzing Source Image...
23:05:54 - ReActor - STATUS - Analyzing Target Image...
23:05:55 - ReActor - STATUS - Detecting Source Face, Index = 0
23:05:55 - ReActor - STATUS - Detected: -52- y.o. Male
*** Error running postprocess_image: C:\Users\chris\Desktop\Work\SuperStableDiffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\Users\chris\Desktop\Work\SuperStableDiffusion\stable-diffusion-webui\modules\scripts.py", line 774, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\Users\chris\Desktop\Work\SuperStableDiffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 376, in postprocess_image
        result, output, swapped = swap_face(
      File "C:\Users\chris\Desktop\Work\SuperStableDiffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 581, in swap_face
        result_image, output, swapped = operate(source_img,target_img,target_img_orig,model,source_faces_index,faces_index,source_faces,target_faces,gender_source,gender_target,source_face,wrong_gender,source_age,source_gender,output,swapped,mask_face,entire_mask_image,enhancement_options)
      File "C:\Users\chris\Desktop\Work\SuperStableDiffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 643, in operate
        face_swapper = getFaceSwapModel(model)
      File "C:\Users\chris\Desktop\Work\SuperStableDiffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 128, in getFaceSwapModel
        FS_MODEL = insightface.model_zoo.get_model(model_path, providers=PROVIDERS)
      File "C:\Users\chris\Desktop\Work\SuperStableDiffusion\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
        model = router.get_model(providers=providers, provider_options=provider_options)
      File "C:\Users\chris\Desktop\Work\SuperStableDiffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 21, in patched_get_model
        session = PickableInferenceSession(self.onnx_file, **kwargs)
      File "C:\Users\chris\Desktop\Work\SuperStableDiffusion\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "C:\Users\chris\Desktop\Work\SuperStableDiffusion\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "C:\Users\chris\Desktop\Work\SuperStableDiffusion\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 452, in _create_inference_session
        sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\chris\Desktop\Work\SuperStableDiffusion\stable-diffusion-webui\models\insightface\inswapper_128.onnx failed:Protobuf parsing failed.

---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:10<00:00,  1.90it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:10<00:00,  4.75it/s]
```

**Comment by Gourieff** [comment]
https://github.com/Gourieff/sd-webui-reactor#v-invalid_protobuf--load-model-from-modelsinsightfaceinswapper_128onnx-failedprotobuf-parsing-failed-or-attributeerror-nonetype-object-has-no-attribute-get-or-attributeerror-faceswapscript-object-has-no-attribute-save_original

https://github.com/Gourieff/sd-webui-reactor/issues?q=is%3Aissue+is%3Aclosed+INVALID_PROTOBUF+%3A+Load+model+from
