### ISSUE TITLE
Roop | ModuleNotFoundError: No module named 'ifnude'

### ISSUE THREAD

**Issue by nxgtrouble** [Gourieff/sd-webui-reactor#291]
### Feature description

2023-12-30 20:12:16,447 - ControlNet - INFO - ControlNet v1.1.424
2023-12-30 20:12:16,496 - ControlNet - INFO - ControlNet v1.1.424
20:12:16 - ReActor - STATUS - Running v0.6.0-a4
*** Error loading script: api.py
    Traceback (most recent call last):
      File "D:\STABLE DIFFUSION\AI\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\STABLE DIFFUSION\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\STABLE DIFFUSION\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\api.py", line 17, in <module>
        from scripts.faceswap import get_models
      File "D:\STABLE DIFFUSION\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "D:\STABLE DIFFUSION\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 14, in <module>
        from scripts.cimage import convert_to_sd
      File "D:\STABLE DIFFUSION\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
        from ifnude import detect
    ModuleNotFoundError: No module named 'ifnude'

---
*** Error loading script: cimage.py
    Traceback (most recent call last):
      File "D:\STABLE DIFFUSION\AI\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\STABLE DIFFUSION\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\STABLE DIFFUSION\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
        from ifnude import detect
    ModuleNotFoundError: No module named 'ifnude'

---
*** Error loading script: faceswap.py
    Traceback (most recent call last):
      File "D:\STABLE DIFFUSION\AI\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\STABLE DIFFUSION\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\STABLE DIFFUSION\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, ImageResult
      File "D:\STABLE DIFFUSION\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 14, in <module>
        from scripts.cimage import convert_to_sd
      File "D:\STABLE DIFFUSION\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
        from ifnude import detect
    ModuleNotFoundError: No module named 'ifnude'

---
2023-12-30 20:12:16,739 - roop - INFO - roop v0.0.2
*** Error loading script: swapper.py
    Traceback (most recent call last):
      File "D:\STABLE DIFFUSION\AI\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\STABLE DIFFUSION\AI\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\STABLE DIFFUSION\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\swapper.py", line 14, in <module>
        from scripts.cimage import convert_to_sd
      File "D:\STABLE DIFFUSION\AI\stable-diffusion-webui\extensions\sd-webui-roop\scripts\cimage.py", line 2, in <module>
        from ifnude import detect
    ModuleNotFoundError: No module named 'ifnude'

---
Loading weights [139ac005d4] from D:\STABLE DIFFUSION\AI\stable-diffusion-webui\models\Stable-diffusion\realisticVisionV51_v51VAE.ckpt
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 9.2s (prepare environment: 3.9s, import torch: 1.9s, import gradio: 0.5s, setup paths: 0.5s, initialize shared: 0.2s, other imports: 0.4s, load scripts: 1.2s, create ui: 0.4s, gradio launch: 0.2s).
Creating model from config: D:\STABLE DIFFUSION\AI\stable-diffusion-webui\configs\v1-inference.yaml
Applying attention optimization: Doggettx... done.
Model loaded in 6.0s (load weights from disk: 2.2s, create model: 0.2s, apply weights to model: 2.0s, apply half(): 0.8s, calculate empty prompt: 0.6s).

**Comment by Gourieff** [comment]
Sorry my friend, but "sd-webui-reactor" has nothing to do with "sd-webui-roop" errors you got

> 20:12:16 - ReActor - STATUS - Running v0.6.0-a4

You have ReActor running, but Roop not

> File "D:\STABLE DIFFUSION\AI\stable-diffusion-webui\extensions\\__sd-webui-roop__\scripts\swapper.py", line 14, in
__from scripts.cimage import convert_to_sd__
File "D:\STABLE DIFFUSION\AI\stable-diffusion-webui\extensions\\__sd-webui-roop__\scripts\cimage.py", line 2, in
__from ifnude import detect__
ModuleNotFoundError: No module named 'ifnude'

ReActor has no such modules

ReActor and Roop has different ORT dependencies, they won't work together, you should choose one of them and disable another

**Comment by gushf8** [comment]
The same thing happened to me today January 1, I wanted to reinstall SD and now I get that error, I think it is a problem of VENV, there should be those modules but they do not exist or the code of the modules is wrong, hopefully in a few days they will fix it.

**Comment by Gourieff** [comment]
You can simply remove old Roop if don't need it

**Comment by Rebecasarai** [comment]
Hi, is there any solution?

**Comment by corvo4791** [comment]
Same problem here. Has anybody solved this?

**Comment by oksana001** [comment]
Hi, everyone. All evening and night tried to solve it problem: Module Not Found Error: No module named 'if nude' STABLE DIFFUSION', tried different solutions, ONLY this video helped me: https://www.youtube.com/watch?v=eT9qYOj8Djo.

**Comment by jeonhun6084** [comment]
If downloading doesn't work, check your Python version.
I solved it by changing the Python version. 3.9.x -> 3.10.6
