### ISSUE TITLE
FAIL : LoadLibrary failed with error 126 

### ISSUE THREAD

**Issue by Kedaranatha** [Gourieff/sd-webui-reactor#310]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

just getting error in terminal , see log

no issues with aaa111 initialization
14:39:11 - ReActor - STATUS - Running v0.6.0-a4

### Steps to reproduce the problem

it was no issue with auto111 V1.6

install Automatic1111 version: [v1.7.0-285-g15ec54dd](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/15ec54dd969d6dc3fea7790ca5cce5badcfda426)  •  python: 3.10.6  •  torch: 2.1.2+cu121

### Sysinfo

app: stable-diffusion-webui.git
updated: 2024-01-04
hash: 15ec54dd
url: https://github.com/AUTOMATIC1111/stable-diffusion-webui.git/tree/dev

arch: AMD64
cpu: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
system: Windows
release: Windows-10-10.0.22631-SP0
python: 3.10.6

2.1.2+cu121 autocast  half

device: NVIDIA GeForce RTX 3090 (1) (sm_90) (8, 6)
cuda: 12.1
cudnn: 8801
driver: 546.33

xformers: 
diffusers: 0.16.1
transformers: 4.30.2

### Relevant console log

```Shell
14:42:15 - ReActor - STATUS - Working: source face index [0], target face index [0]████| 20/20 [00:05<00:00,  3.36it/s]
14:42:15 - ReActor - STATUS - Analyzing Source Image...
2024-01-04 14:42:15.6319269 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\sd.webui\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:739 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
 when using ['CUDAExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
2024-01-04 14:42:15.7421274 [E:onnxruntime:Default, provider_bridge_ort.cc:1480 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\sd.webui\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

*** Error running postprocess_image: C:\sd.webui\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\sd.webui\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "C:\sd.webui\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
        sess.initialize_session(providers, provider_options, disabled_optimizers)
    RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:739 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.


    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "C:\sd.webui\webui\modules\scripts.py", line 847, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\sd.webui\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 376, in postprocess_image
        result, output, swapped = swap_face(
      File "C:\sd.webui\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 509, in swap_face
        source_faces = analyze_faces(source_img)
      File "C:\sd.webui\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 273, in analyze_faces
        face_analyser = copy.deepcopy(getAnalysisModel())
      File "C:\sd.webui\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 117, in getAnalysisModel
        ANALYSIS_MODEL = insightface.app.FaceAnalysis(
      File "C:\sd.webui\webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 48, in patched_faceanalysis_init
        model = model_zoo.get_model(onnx_file, **kwargs)
      File "C:\sd.webui\system\python\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
        model = router.get_model(providers=providers, provider_options=provider_options)
      File "C:\sd.webui\webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 21, in patched_get_model
        session = PickableInferenceSession(self.onnx_file, **kwargs)
      File "C:\sd.webui\system\python\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "C:\sd.webui\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 430, in __init__
        raise fallback_error from e
      File "C:\sd.webui\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 425, in __init__
        self._create_inference_session(self._fallback_providers, None)
      File "C:\sd.webui\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 463, in _create_inference_session
        sess.initialize_session(providers, provider_options, disabled_optimizers)
    RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:739 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
```

**Comment by Gourieff** [comment]
You have CUDA 12.1, but ORT-GPU works with 11.8 https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements
There's no guarantee to work with 12.1
You need to downgrade it to 11.8 alongside with Torch and Torchvision
Or you can try this https://github.com/Gourieff/comfyui-reactor-node/issues/119#issuecomment-1841350868
