### ISSUE TITLE
[NEW] AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [Gourieff/sd-webui-reactor#320]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I can't launch stable diffusion with reactor installed! There was a duplicate post but I have already installed a new inswapper manually from the README and that didn't work. Perhaps I could be installing it from the wrong place!

### Steps to reproduce the problem

1. Install sd-webui-reactor
2. Can't open Stable Diffusion

### Sysinfo

Win 11, RTX 3070 TI, SD 1.5.2, 
![image](https://github.com/Gourieff/sd-webui-reactor/assets/45579671/0ae63985-4d6b-4da2-beed-a19cf209d622)

### Relevant console log

```Shell
*** Error calling: D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py/ui
    Traceback (most recent call last):
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\scripts.py", line 339, in wrap_call
        return func(*args, **kwargs)
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 44, in ui
        with ui_components.InputAccordion(False, label=f"{app_title}") as enable:
    AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

---
*** Error calling: D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py/ui
    Traceback (most recent call last):
      File "D:\ai\masterbranch\stable-diffusion-webui\modules\scripts.py", line 339, in wrap_call
        return func(*args, **kwargs)
      File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 44, in ui
        with ui_components.InputAccordion(False, label=f"{app_title}") as enable:
    AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

---
calling D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py/ui: AttributeError
Traceback (most recent call last):
  File "D:\ai\masterbranch\stable-diffusion-webui\modules\scripts_postprocessing.py", line 53, in wrap_call
    res = func(*args, **kwargs)
  File "D:\ai\masterbranch\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 414, in ui
    with ui_components.InputAccordion(False, label=f"{app_title}") as enable:
AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\ai\masterbranch\stable-diffusion-webui\launch.py:39 in <module>                               │
│                                                                                                  │
│   36                                                                                             │
│   37                                                                                             │
│   38 if __name__ == "__main__":                                                                  │
│ ❱ 39 │   main()                                                                                  │
│   40                                                                                             │
│                                                                                                  │
│ D:\ai\masterbranch\stable-diffusion-webui\launch.py:35 in main                                   │
│                                                                                                  │
│   32 │   if args.test_server:                                                                    │
│   33 │   │   configure_for_tests()                                                               │
│   34 │                                                                                           │
│ ❱ 35 │   start()                                                                                 │
│   36                                                                                             │
│   37                                                                                             │
│   38 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ D:\ai\masterbranch\stable-diffusion-webui\modules\launch_utils.py:394 in start                   │
│                                                                                                  │
│   391 │   if '--nowebui' in sys.argv:                                                            │
│   392 │   │   webui.api_only()                                                                   │
│   393 │   else:                                                                                  │
│ ❱ 394 │   │   webui.webui()                                                                      │
│   395                                                                                            │
│                                                                                                  │
│ D:\ai\masterbranch\stable-diffusion-webui\webui.py:393 in webui                                  │
│                                                                                                  │
│   390 │   │   modules.script_callbacks.before_ui_callback()                                      │
│   391 │   │   startup_timer.record("scripts before_ui_callback")                                 │
│   392 │   │                                                                                      │
│ ❱ 393 │   │   shared.demo = modules.ui.create_ui()                                               │
│   394 │   │   startup_timer.record("create ui")                                                  │
│   395 │   │                                                                                      │
│   396 │   │   if not cmd_opts.no_gradio_queue:                                                   │
│                                                                                                  │
│ D:\ai\masterbranch\stable-diffusion-webui\modules\ui.py:1061 in create_ui                        │
│                                                                                                  │
│   1058 │   modules.scripts.scripts_current = None                                                │
│   1059 │                                                                                         │
│   1060 │   with gr.Blocks(analytics_enabled=False) as extras_interface:                          │
│ ❱ 1061 │   │   ui_postprocessing.create_ui()                                                     │
│   1062 │                                                                                         │
│   1063 │   with gr.Blocks(analytics_enabled=False) as pnginfo_interface:                         │
│   1064 │   │   with gr.Row().style(equal_height=False):                                          │
│                                                                                                  │
│ D:\ai\masterbranch\stable-diffusion-webui\modules\ui_postprocessing.py:25 in create_ui           │
│                                                                                                  │
│   22 │   │   │                                                                                   │
│   23 │   │   │   submit = gr.Button('Generate', elem_id="extras_generate", variant='primary')    │
│   24 │   │   │                                                                                   │
│ ❱ 25 │   │   │   script_inputs = scripts.scripts_postproc.setup_ui()                             │
│   26 │   │                                                                                       │
│   27 │   │   with gr.Column():                                                                   │
│   28 │   │   │   result_images, html_info_x, html_info, html_log = ui_common.create_output_pa    │
│                                                                                                  │
│ D:\ai\masterbranch\stable-diffusion-webui\modules\scripts_postprocessing.py:113 in setup_ui      │
│                                                                                                  │
│   110 │   │                                                                                      │
│   111 │   │   for script in self.scripts_in_preferred_order():                                   │
│   112 │   │   │   with gr.Row() as group:                                                        │
│ ❱ 113 │   │   │   │   self.create_script_ui(script, inputs)                                      │
│   114 │   │   │                                                                                  │
│   115 │   │   │   script.group = group                                                           │
│   116                                                                                            │
│                                                                                                  │
│ D:\ai\masterbranch\stable-diffusion-webui\modules\scripts_postprocessing.py:84 in                │
│ create_script_ui                                                                                 │
│                                                                                                  │
│    81 │   │                                                                                      │
│    82 │   │   script.controls = wrap_call(script.ui, script.filename, "ui")                      │
│    83 │   │                                                                                      │
│ ❱  84 │   │   for control in script.controls.values():                                           │
│    85 │   │   │   control.custom_script_source = os.path.basename(script.filename)               │
│    86 │   │                                                                                      │
│    87 │   │   inputs += list(script.controls.values())                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'values'
Creating model from config: D:\ai\masterbranch\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying attention optimization: xformers... done.
Model loaded in 2.2s (load weights from disk: 0.5s, create model: 0.4s, apply weights to model: 0.4s, apply half(): 0.4s, move model to device: 0.5s).
```
```


### Additional information

_No response_

**Comment by ENTPRESTIGIOUS** [comment]
Solved https://github.com/Gourieff/sd-webui-reactor/issues/282#issuecomment-1888731893
