### ISSUE TITLE
Problem values after installation

### ISSUE THREAD

**Issue by KakaoXI** [Gourieff/sd-webui-reactor#321]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Code error after have installed reactor

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...
After have downloaded reactor

### Sysinfo

Windows 11

### Relevant console log

```Shell
*** Error calling: D:\Generale\Nicolas\StableDiffusion\extensions\sd-webui-reactor\scripts\reactor_faceswap.py/ui
    Traceback (most recent call last):
      File "D:\Generale\Nicolas\StableDiffusion\modules\scripts.py", line 294, in wrap_call
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "D:\Generale\Nicolas\StableDiffusion\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 44, in ui        with ui_components.InputAccordion(False, label=f"{app_title}") as enable:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

---
*** Error calling: D:\Generale\Nicolas\StableDiffusion\extensions\sd-webui-reactor\scripts\reactor_faceswap.py/ui
    Traceback (most recent call last):
      File "D:\Generale\Nicolas\StableDiffusion\modules\scripts.py", line 294, in wrap_call
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "D:\Generale\Nicolas\StableDiffusion\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 44, in ui        with ui_components.InputAccordion(False, label=f"{app_title}") as enable:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

---
calling D:\Generale\Nicolas\StableDiffusion\extensions\sd-webui-reactor\scripts\reactor_faceswap.py/ui: AttributeError
Traceback (most recent call last):
  File "D:\Generale\Nicolas\StableDiffusion\modules\scripts_postprocessing.py", line 53, in wrap_call
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Generale\Nicolas\StableDiffusion\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 414, in ui
    with ui_components.InputAccordion(False, label=f"{app_title}") as enable:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

Traceback (most recent call last):
  File "D:\Generale\Nicolas\StableDiffusion\launch.py", line 38, in <module>
    main()
  File "D:\Generale\Nicolas\StableDiffusion\launch.py", line 34, in main
    start()
  File "D:\Generale\Nicolas\StableDiffusion\modules\launch_utils.py", line 344, in start
    webui.webui()
  File "D:\Generale\Nicolas\StableDiffusion\webui.py", line 382, in webui
    shared.demo = modules.ui.create_ui()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Generale\Nicolas\StableDiffusion\modules\ui.py", line 1055, in create_ui
    ui_postprocessing.create_ui()
  File "D:\Generale\Nicolas\StableDiffusion\modules\ui_postprocessing.py", line 25, in create_ui
    script_inputs = scripts.scripts_postproc.setup_ui()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Generale\Nicolas\StableDiffusion\modules\scripts_postprocessing.py", line 113, in setup_ui
    self.create_script_ui(script, inputs)
  File "D:\Generale\Nicolas\StableDiffusion\modules\scripts_postprocessing.py", line 84, in create_script_ui
    for control in script.controls.values():
                   ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'values'
```

**Comment by Gourieff** [comment]
https://github.com/Gourieff/sd-webui-reactor/issues?q=is%3Aissue+is%3Aclosed+%27modules.ui_components%27+has+no+attribute+%27InputAccordion%27
