### ISSUE TITLE
AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

### ISSUE THREAD

**Issue by 0Blueaura** [Gourieff/sd-webui-reactor#327]
### First, confirm

- [x] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

```
Error calling: J:\stablediff\extensions\sd-webui-reactor\scripts\reactor_faceswap.py/ui
Traceback (most recent call last):
  File "J:\stablediff\modules\scripts.py", line 262, in wrap_call
    res = func(*args, **kwargs)
  File "J:\stablediff\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 44, in ui
    with ui_components.InputAccordion(False, label=f"{app_title}") as enable:
AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

Error calling: J:\stablediff\extensions\sd-webui-reactor\scripts\reactor_faceswap.py/ui
Traceback (most recent call last):
  File "J:\stablediff\modules\scripts.py", line 262, in wrap_call
    res = func(*args, **kwargs)
  File "J:\stablediff\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 44, in ui
    with ui_components.InputAccordion(False, label=f"{app_title}") as enable:
AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

calling J:\stablediff\extensions\sd-webui-reactor\scripts\reactor_faceswap.py/ui: AttributeErrorTraceback (most recent call last):
  File "J:\stablediff\modules\scripts_postprocessing.py", line 53, in wrap_call
    res = func(*args, **kwargs)
  File "J:\stablediff\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 414, in ui
    with ui_components.InputAccordion(False, label=f"{app_title}") as enable:
AttributeError: module 'modules.ui_components' has no attribute 'InputAccordion'

Traceback (most recent call last):
  File "J:\stablediff\launch.py", line 381, in <module>
    start()
  File "J:\stablediff\launch.py", line 376, in start
    webui.webui()
  File "J:\stablediff\webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui()
  File "J:\stablediff\modules\ui.py", line 975, in create_ui
    ui_postprocessing.create_ui()
  File "J:\stablediff\modules\ui_postprocessing.py", line 25, in create_ui
    script_inputs = scripts.scripts_postproc.setup_ui()
  File "J:\stablediff\modules\scripts_postprocessing.py", line 113, in setup_ui
    self.create_script_ui(script, inputs)
  File "J:\stablediff\modules\scripts_postprocessing.py", line 84, in create_script_ui
    for control in script.controls.values():
AttributeError: 'NoneType' object has no attribute 'values'
```

### Steps to reproduce the problem

updating via stablediff install from url

### Sysinfo

-

### Relevant console log

```Shell
-
```

### Additional information

6.0 version doesnt work, falling back to 5.1 makes it work again

**Comment by Gourieff** [comment]
https://github.com/Gourieff/sd-webui-reactor/issues?q=is%3Aissue+is%3Aclosed+%27modules.ui_components%27+has+no+attribute+%27InputAccordion%27

**Comment by kassabro** [comment]
You should update A1111 to the latest version (1.7.0)

follow this https://github.com/Gourieff/sd-webui-reactor/issues/324 i had a same issue.
