### ISSUE TITLE
*** Error running postprocess_image: /data/models/stable-diffusion/extensions/sd-webui-reactor/scripts/reactor_faceswap.py

### ISSUE THREAD

**Issue by MacFGalempsy** [Gourieff/sd-webui-reactor#349]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

attempting to run ReActor, it runs, but then there is "Error running postprocess_image". I have moved over from TensorRT, unet to ONNX

### Steps to reproduce the problem

Installed the program and added the required models. Followed a youtube tutorial on running the extension, but received this error after. I have converted back from TensorRT to ONNX, and made all the settings. Ultimately, the image is not swapping the face. 

### Sysinfo

Jetson Orin AGX Developer Kit 64gb - Using the /dusty-nv/jetson-containers version of Automatic 1111

This is an Nvidia accelerated docker container, where the data are stored in /home/<user_name>/jetson-containers/data/
 

### Relevant console log

```Shell
To create a public link, set `share=True` in `launch()`.
Startup time: 31.6s (prepare environment: 19.5s, import torch: 3.9s, import gradio: 1.5s, setup paths: 1.1s, initialize shared: 0.1s, other imports: 1.1s, setup codeformer: 0.1s, load scripts: 2.3s, create ui: 1.4s, gradio launch: 0.4s).
Creating model from config: /opt/stable-diffusion-webui/configs/v1-inference.yaml
Applying attention optimization: xformers... done.
Model loaded in 7.7s (load weights from disk: 2.0s, create model: 1.0s, apply weights to model: 3.8s, load textual inversion embeddings: 0.4s, calculate empty prompt: 0.2s).
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  2.96it/s]
04:38:23 - ReActor - STATUS - ! Working: source face index [0], target face index [0]████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.71it/s]
04:38:23 - ReActor - STATUS - Analyzing Source Image...
*** Error running postprocess_image: /data/models/stable-diffusion/extensions/sd-webui-reactor/scripts/reactor_faceswap.py
    Traceback (most recent call last):
      File "/opt/stable-diffusion-webui/modules/scripts.py", line 774, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "/data/models/stable-diffusion/extensions/sd-webui-reactor/scripts/reactor_faceswap.py", line 418, in postprocess_image
        result, output, swapped = swap_face(
      File "/data/models/stable-diffusion/extensions/sd-webui-reactor/scripts/reactor_swapper.py", line 516, in swap_face
        source_faces = analyze_faces(source_img)
      File "/data/models/stable-diffusion/extensions/sd-webui-reactor/scripts/reactor_swapper.py", line 275, in analyze_faces
        face_analyser = copy.deepcopy(getAnalysisModel())
      File "/data/models/stable-diffusion/extensions/sd-webui-reactor/scripts/reactor_swapper.py", line 119, in getAnalysisModel
        ANALYSIS_MODEL = insightface.app.FaceAnalysis(
      File "/data/models/stable-diffusion/extensions/sd-webui-reactor/scripts/console_log_patch.py", line 59, in patched_faceanalysis_init
        assert 'detection' in self.models
    AssertionError
```

### Additional information

I understand that this is an unconventional setup with the software. If there is a unique solution to fixing the issue, I would be grateful for being put in the right direction.

**Comment by Gourieff** [comment]
Try these solutions https://github.com/Gourieff/sd-webui-reactor/issues?q=is%3Aissue+is%3Aclosed+assert+%27detection%27+in+self.models
