### ISSUE TITLE
ComfyUI | [ReActor] - STATUS - Running v0.4.1-b9 in ComfyUI but fails to load

### ISSUE THREAD

**Issue by offmybach** [Gourieff/sd-webui-reactor#358]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I have been trying to load the node for a week and no luck at all. Says running but fails to load with error:
VAE dtype: torch.bfloat16
[ReActor] - STATUS - Running v0.4.1-b9 in ComfyUI
Torch version: 2.1.2+cu121
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 22, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 30, in <module>
    import scripts.r_archs.codeformer_arch
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\r_archs\codeformer_arch.py", line 8, in <module>
    from scripts.r_archs.vqgan_arch import *
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\r_archs\vqgan_arch.py", line 328, in <module>
    @ARCH_REGISTRY.register()
     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\basicsr\utils\registry.py", line 56, in deco
    self._do_register(name, func_or_class, suffix)
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\basicsr\utils\registry.py", line 42, in _do_register
    assert (name not in self._obj_map), (f"An object named '{name}' was already registered "
            ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: An object named 'VQAutoEncoder' was already registered in 'arch' registry!

Cannot import D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: An object named 'VQAutoEncoder' was already registered in 'arch' registry!

What is going on here and how do I fix this mess?

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...
run nvidia gpu bat

### Sysinfo

win 11 portable comfyui version (updated weekly) 

### Relevant console log

```Shell
D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI startup time: 2024-02-12 11:34:27.357721
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\comfyui.log
[Maras IT] Initialization

Prestartup times for custom nodes:
   0.0 seconds: D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MarasIT-Nodes
   0.1 seconds: D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 32433 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Adding extra search path checkpoints C:\Users\mdmen\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs C:\Users\mdmen\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae C:\Users\mdmen\stable-diffusion-webui\models/VAE
Adding extra search path loras C:\Users\mdmen\stable-diffusion-webui\models/Lora
Adding extra search path loras C:\Users\mdmen\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models C:\Users\mdmen\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models C:\Users\mdmen\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models C:\Users\mdmen\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings C:\Users\mdmen\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks C:\Users\mdmen\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet C:\Users\mdmen\stable-diffusion-webui\models/ControlNet
2024-02-12 11:34:31.993256: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

[Allor]: 0 nodes were overridden.
[Allor]: 12 modules were enabled.
[Allor]: 98 nodes were loaded.
Adding D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
cannot import name 'CompVisVDenoiser' from 'comfy.samplers' (D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py)
[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
Loaded ControlNetPreprocessors nodes from D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
[Errno 2] No such file or directory: 'D:\\ComfyUI_windows_portable\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Advanced-ControlNet\\control/control.py\\__init__.py'
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Could not find VideoHelperSuite nodes
### ComfyUI-Background-Replacement: Requirements already installed.
### ComfyUI-Background-Replacement: Initializing captioner...
### ComfyUI-Background-Replacement: Initializing upscaler...
### ComfyUI-Background-Replacement: Initializing segmenter...
### ComfyUI-Background-Replacement: Initializing depth estimator...
[Crystools INFO] Crystools version: 1.11.0
[Crystools INFO] CPU: 12th Gen Intel(R) Core(TM) i7-12700H - Arch: AMD64 - OS: Windows 10
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3070 Ti Laptop GPU
[Crystools INFO] NVIDIA Driver: 551.23
Comfy-Easy-Use (v1.0.5): Loaded
### ComfyUI-FaceSwap: Check dependencies
### ComfyUI-FaceSwap: Check basic models
### Loading: ComfyUI-Impact-Pack (V4.75)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V0.63)
Total VRAM 8192 MB, total RAM 32433 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Torch version: 2.1.2+cu121
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ComfyUI_windows_portable\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-IPAdapter-FaceIDv2-Workflow\\__init__.py'

Cannot import D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IPAdapter-FaceIDv2-Workflow module for custom nodes: [Errno 2] No such file or directory: 'D:\\ComfyUI_windows_portable\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-IPAdapter-FaceIDv2-Workflow\\__init__.py'
Package diffusers is already installed.
### Loading: ComfyUI-Manager (V2.7.2)
### ComfyUI Revision: 1966 [20e3da6b] | Released on '2024-02-10'
[Maras IT] Loaded
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
--------------
 ### Mixlab Nodes: Loaded
## lama torchscript model not found: D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\models\lama/big-lama.pt,pls download from https://github.com/enesmsahin/simple-lama-inpainting/releases/download/v0.1.0/big-lama.pt
LaMaInpainting.available True
## clip_interrogator_model not found: D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\models\clip_interrogator/Salesforce/blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
ClipInterrogator.available True
## text_generator_model not found: D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\models\prompt_generator/text2image-prompt-generator, pls download from https://huggingface.co/succinctly/text2image-prompt-generator/tree/main
## zh_en_model not found: D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\models\prompt_generator/opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
 --------------
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes-0.15.1\__init__.py", line 533, in <module>
    from .nodes.PromptNode import EmbeddingPrompt,RandomPrompt,PromptSlide,PromptSimplification,PromptImage,JoinWithDelimiter
ModuleNotFoundError: No module named 'comfyui-mixlab-nodes-0'

Cannot import D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes-0.15.1 module for custom nodes: No module named 'comfyui-mixlab-nodes-0'
packaging is already installed.
cpuinfo is already installed.
git is already installed.
moviepy is already installed.
cv2 is already installed.
skbuild is already installed.
typing is already installed.
diskcache is already installed.
llama_cpp is already installed.

OpenPose Editor: Loaded
ComfyUI-Portrait-Maker : ### : Check dependencies
ComfyUI-Portrait-Maker : D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Portrait-Maker\requirements.txt
ComfyUI-Portrait-Maker : aliyun-python-sdk-core-v3==2.13.10

ComfyUI-Portrait-Maker : opencv-python

ComfyUI-Portrait-Maker : tensorflow-cpu

ComfyUI-Portrait-Maker : tensorflow

ComfyUI-Portrait-Maker : onnx

ComfyUI-Portrait-Maker : onnxruntime

ComfyUI-Portrait-Maker : modelscope

ComfyUI-Portrait-Maker : scikit-image

ComfyUI-Portrait-Maker : matplotlib

ComfyUI-Portrait-Maker : insightface

ComfyUI-Portrait-Maker : diffusers==0.18.2

ComfyUI-Portrait-Maker : sentencepiece
2024-02-12 11:34:50,148 - modelscope - INFO - PyTorch version 2.1.2+cu121 Found.
2024-02-12 11:34:50,148 - modelscope - INFO - TensorFlow version 2.15.0 Found.
2024-02-12 11:34:50,148 - modelscope - INFO - Loading ast index from C:\Users\mdmen\.cache\modelscope\ast_indexer
2024-02-12 11:34:50,274 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 4964e32649544be02d50cfc7603a6e46 and a total number of 946 components indexed
Start Setting weights
[INFO] PromptControl: Use STYLE:weight_interpretation:normalization at the start of a prompt to use advanced encodings
[INFO] PromptControl: Weight interpretations available: comfy,A1111,compel,comfy++,down_weight,perp
[INFO] PromptControl: Normalization types available: none,mean,length,length+mean
[SD Prompt Reader] Node version: 1.3.0
[SD Prompt Reader] Core version: 1.3.4.post1
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ComfyUI_windows_portable\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui-ps-plugin\\__init__.py'

Cannot import D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-ps-plugin module for custom nodes: [Errno 2] No such file or directory: 'D:\\ComfyUI_windows_portable\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui-ps-plugin\\__init__.py'
Total VRAM 8192 MB, total RAM 32433 MB
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
[ReActor] - STATUS - Running v0.4.1-b9 in ComfyUI
Torch version: 2.1.2+cu121
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 22, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 30, in <module>
    import scripts.r_archs.codeformer_arch
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\r_archs\codeformer_arch.py", line 8, in <module>
    from scripts.r_archs.vqgan_arch import *
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\r_archs\vqgan_arch.py", line 328, in <module>
    @ARCH_REGISTRY.register()
     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\basicsr\utils\registry.py", line 56, in deco
    self._do_register(name, func_or_class, suffix)
  File "D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\basicsr\utils\registry.py", line 42, in _do_register
    assert (name not in self._obj_map), (f"An object named '{name}' was already registered "
            ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: An object named 'VQAutoEncoder' was already registered in 'arch' registry!

Cannot import D:\ComfyUI_windows_portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: An object named 'VQAutoEncoder' was already registered in 'arch' registry!
```

**Comment by Gourieff** [comment]
Fixed in the latest commits
