### ISSUE TITLE
 No module named 'insightface'

### ISSUE THREAD

**Issue by malbranpablo** [Gourieff/sd-webui-reactor#364]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Insightface seems to be not installed properly.
Folder \models\insightface is present

### Steps to reproduce the problem

- Clean install of Automatic1111 (not in Windows user folder)
- No Stability Matrix
- Automatic1111 is fully functional
- Installed complete Visual Studio 2022 (trying with and without dependencies [CC++ Tools] for desktop)
- Installed Reactor from URL in the Extension tab.
- Install insightface-0.7.3-cp310-cp310-win_amd64.whl venv
- Install  insightface-0.7.3-cp310-cp310-win_amd64.wh in OS
- The terminal invited me to stop the Server
- Relaunch Automatic1111

### Sysinfo

Windows 11
RTX 3090 24gb
Intel I5 13th
16gb ram

### Relevant console log

```Shell
(Automatic1111) C:\StableDiffusion\stable-diffusion-webui>webui-user.bat
venv "C:\StableDiffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 | packaged by conda-forge | (main, Oct 24 2022, 16:02:16) [MSC v.1916 64 bit (AMD64)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Installing requirements
Collecting insightface==0.7.3
  Using cached insightface-0.7.3-cp310-cp310-win_amd64.whl
Requirement already satisfied: onnx in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (1.15.0)
Requirement already satisfied: scipy in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (1.12.0)
Requirement already satisfied: requests in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (2.31.0)
Collecting scikit-learn
  Using cached scikit_learn-1.4.1.post1-cp310-cp310-win_amd64.whl (10.6 MB)
Requirement already satisfied: prettytable in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (3.9.0)
Collecting cython
  Using cached Cython-3.0.8-cp310-cp310-win_amd64.whl (2.8 MB)
Requirement already satisfied: scikit-image in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (0.21.0)
Requirement already satisfied: matplotlib in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (3.8.3)
Requirement already satisfied: Pillow in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (9.5.0)
Requirement already satisfied: numpy in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (1.23.5)
Requirement already satisfied: tqdm in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (4.66.2)
Collecting albumentations
  Using cached albumentations-1.4.0-py3-none-any.whl (123 kB)
Requirement already satisfied: easydict in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (1.12)
Collecting numpy
  Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl (15.8 MB)
Requirement already satisfied: opencv-python>=4.9.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from albumentations->insightface==0.7.3) (4.9.0.80)
Requirement already satisfied: PyYAML in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from albumentations->insightface==0.7.3) (6.0.1)
Collecting qudida>=0.0.4
  Using cached qudida-0.0.4-py3-none-any.whl (3.5 kB)
Requirement already satisfied: imageio>=2.27 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (2.34.0)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (1.5.0)
Requirement already satisfied: networkx>=2.8 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (3.2.1)
Requirement already satisfied: tifffile>=2022.8.12 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (2024.2.12)
Requirement already satisfied: lazy_loader>=0.2 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (0.3)
Requirement already satisfied: packaging>=21 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (23.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (3.1.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (1.4.5)
Requirement already satisfied: fonttools>=4.22.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (4.49.0)
Requirement already satisfied: cycler>=0.10 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (0.12.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (2.8.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (1.2.0)
Requirement already satisfied: protobuf>=3.20.2 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from onnx->insightface==0.7.3) (3.20.3)
Requirement already satisfied: wcwidth in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from prettytable->insightface==0.7.3) (0.2.13)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (2024.2.2)
Collecting joblib>=1.2.0
  Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-learn->insightface==0.7.3) (3.3.0)
Requirement already satisfied: colorama in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from tqdm->insightface==0.7.3) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->insightface==0.7.3) (1.16.0)
Collecting opencv-python-headless>=4.0.1
  Using cached opencv_python_headless-4.9.0.80-cp37-abi3-win_amd64.whl (38.5 MB)
Requirement already satisfied: typing-extensions in c:\stablediffusion\stable-diffusion-webui\venv\lib\site-packages (from qudida>=0.0.4->albumentations->insightface==0.7.3) (4.9.0)
Installing collected packages: numpy, joblib, cython, opencv-python-headless, scikit-learn, qudida, albumentations, insightface
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5
CUDA 11.8
Error: The 'insightface==0.7.3' distribution was not found and is required by the application

        +---------------------------------+
        --- PLEASE, RESTART the Server! ---
        +---------------------------------+
Launching Web UI with arguments:
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Style database not found: C:\StableDiffusion\stable-diffusion-webui\styles.csv
*** Error loading script: console_log_patch.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 4, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_api.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_api.py", line 17, in <module>
        from scripts.reactor_swapper import EnhancementOptions, swap_face, DetectionOptions
      File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 11, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 18, in <module>
        from reactor_ui import (
      File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-reactor\reactor_ui\__init__.py", line 2, in <module>
        import reactor_ui.reactor_tools_ui as ui_tools
      File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-reactor\reactor_ui\reactor_tools_ui.py", line 2, in <module>
        from scripts.reactor_swapper import build_face_model, blend_faces
      File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 11, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_helpers.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in <module>
        from insightface.app.common import Face
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_logger.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_logger.py", line 7, in <module>
        from scripts.reactor_helpers import addLoggingLevel
      File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in <module>
        from insightface.app.common import Face
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_swapper.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 11, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_version.py
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\StableDiffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_version.py", line 4, in <module>
        from scripts.reactor_logger import logger, get_Run, set_Run
      File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_logger.py", line 7, in <module>
        from scripts.reactor_helpers import addLoggingLevel
      File "C:\StableDiffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in <module>
        from insightface.app.common import Face
    ModuleNotFoundError: No module named 'insightface'
```

**Comment by MicheleBonus** [comment]
Ran into the exact same issue today. Temporarily fixed it by copying each of
```
%userprofile%\AppData\Local\Programs\Python\Python310\Lib\site-packages\insightface
%userprofile%\AppData\Local\Programs\Python\Python310\Lib\site-packages\albumentations
%userprofile%\AppData\Local\Programs\Python\Python310\Lib\site-packages\qudida
%userprofile%\AppData\Local\Programs\Python\Python310\Lib\site-packages\sklearn
%userprofile%\AppData\Local\Programs\Python\Python310\Lib\site-packages\joblib
```
to `\venv\Lib\site-packages`.

**Comment by Gourieff** [comment]
https://github.com/Gourieff/sd-webui-reactor/issues?q=is%3Aissue+is%3Aclosed+ModuleNotFoundError%3A+No+module+named+%27insightface%27

**Comment by Desfore** [comment]
> https://github.com/Gourieff/sd-webui-reactor/issues?q=is%3Aissue+is%3Aclosed+ModuleNotFoundError%3A+No+module+named+%27insightface%27
> 
> https://github.com/Gourieff/sd-webui-reactor#insightfacebuild

I'm having the same problem, but the link [prebuilt Insightface package] doesn't seem to work anymore. When I look at the path it's pointing to, I come to the Example folder, but the file it's linking is missing

**Comment by IRadics** [comment]
> > https://github.com/Gourieff/sd-webui-reactor/issues?q=is%3Aissue+is%3Aclosed+ModuleNotFoundError%3A+No+module+named+%27insightface%27
> > https://github.com/Gourieff/sd-webui-reactor#insightfacebuild
> 
> I'm having the same problem, but the link [prebuilt Insightface package] doesn't seem to work anymore. When I look at the path it's pointing to, I come to the Example folder, but the file it's linking is missing

Hi, not sure what did happen to the link, but if you go to the releases (https://github.com/Gourieff/sd-webui-reactor/releases)
and download the source code .zip file, that will have the .whl file in the examples folder
