### ISSUE TITLE
ImportError: cannot import name 'get_random_image_from_folder'

### ISSUE THREAD

**Issue by Dutch77** [Gourieff/sd-webui-reactor#392]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Pulled main branch. Reactor is not working.

### Steps to reproduce the problem

1. Navigate to directory with reactor extension
2. git pull
3. doesn't load

### Sysinfo

-

### Relevant console log

```Shell
ai-stable-diffusion-webui-1  | *** Error loading script: reactor_api.py
ai-stable-diffusion-webui-1  |     Traceback (most recent call last):
ai-stable-diffusion-webui-1  |       File "/workspace/stable-diffusion-webui/modules/scripts.py", line 518, in load_scripts
ai-stable-diffusion-webui-1  |         script_module = script_loading.load_module(scriptfile.path)
ai-stable-diffusion-webui-1  |       File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
ai-stable-diffusion-webui-1  |         module_spec.loader.exec_module(module)
ai-stable-diffusion-webui-1  |       File "<frozen importlib._bootstrap_external>", line 883, in exec_module
ai-stable-diffusion-webui-1  |       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ai-stable-diffusion-webui-1  |       File "/workspace/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_api.py", line 17, in <module>
ai-stable-diffusion-webui-1  |         from scripts.reactor_swapper import EnhancementOptions, swap_face, DetectionOptions
ai-stable-diffusion-webui-1  |     ImportError: cannot import name 'DetectionOptions' from 'scripts.reactor_swapper' (/workspace/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_swapper.py)
ai-stable-diffusion-webui-1  | 
ai-stable-diffusion-webui-1  | ---
ai-stable-diffusion-webui-1  | *** Error loading script: reactor_faceswap.py
ai-stable-diffusion-webui-1  |     Traceback (most recent call last):
ai-stable-diffusion-webui-1  |       File "/workspace/stable-diffusion-webui/modules/scripts.py", line 518, in load_scripts
ai-stable-diffusion-webui-1  |         script_module = script_loading.load_module(scriptfile.path)
ai-stable-diffusion-webui-1  |       File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
ai-stable-diffusion-webui-1  |         module_spec.loader.exec_module(module)
ai-stable-diffusion-webui-1  |       File "<frozen importlib._bootstrap_external>", line 883, in exec_module
ai-stable-diffusion-webui-1  |       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ai-stable-diffusion-webui-1  |       File "/workspace/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_faceswap.py", line 18, in <module>
ai-stable-diffusion-webui-1  |         from reactor_ui import (
ai-stable-diffusion-webui-1  |     ImportError: cannot import name 'ui_detection' from 'reactor_ui' (/workspace/stable-diffusion-webui/extensions/sd-webui-reactor/reactor_ui/__init__.py)
ai-stable-diffusion-webui-1  | 
ai-stable-diffusion-webui-1  | ---
ai-stable-diffusion-webui-1  | *** Error loading script: reactor_swapper.py
ai-stable-diffusion-webui-1  |     Traceback (most recent call last):
ai-stable-diffusion-webui-1  |       File "/workspace/stable-diffusion-webui/modules/scripts.py", line 518, in load_scripts
ai-stable-diffusion-webui-1  |         script_module = script_loading.load_module(scriptfile.path)
ai-stable-diffusion-webui-1  |       File "/workspace/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
ai-stable-diffusion-webui-1  |         module_spec.loader.exec_module(module)
ai-stable-diffusion-webui-1  |       File "<frozen importlib._bootstrap_external>", line 883, in exec_module
ai-stable-diffusion-webui-1  |       File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ai-stable-diffusion-webui-1  |       File "/workspace/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_swapper.py", line 15, in <module>
ai-stable-diffusion-webui-1  |         from scripts.reactor_helpers import (
ai-stable-diffusion-webui-1  |     ImportError: cannot import name 'get_random_image_from_folder' from 'scripts.reactor_helpers' (/workspace/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_helpers.py)
ai-stable-diffusion-webui-1  | 
ai-stable-diffusion-webui-1  | ---

```
```


### Additional information

I believe you broke something with the last features we begged you to add :D

**Comment by Dutch77** [comment]
I did nothing and it started working. Hate these random errors. Closing. Sry
