### ISSUE TITLE
Error loading scripts in scripts folder

### ISSUE THREAD

**Issue by satosCZ** [Gourieff/sd-webui-reactor#396]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Using Automatic1111 Forge. Freshly installed ReActor and it wont work. Updated PIP. Won't be shown at WebUI.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### Sysinfo

[sysinfo-2024-03-14-07-41.json](https://github.com/Gourieff/sd-webui-reactor/files/14598635/sysinfo-2024-03-14-07-41.json)

### Relevant console log

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-276-g29be1da7
Commit hash: 29be1da7cf2b5dccfc70fbdd33eb35c56a31ffb7
Installing requirements
bin d:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
CUDA 12.1
bin d:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: bdc784a86349e6529624cb8e4b3339e5d0f01aee
Checking xformers...
Checking bitsandbytes...
Checking bitsandbytes (Windows)
Virtual environment path: d:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\venv
Checking for d:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda111.dll
Found windows BNB DLL d:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda111.dll
Checking Dreambooth requirements...
Installed version of accelerate: 0.21.0
[Dreambooth] accelerate v0.21.0 is already installed.
Installed version of dadaptation: 3.2
[Dreambooth] dadaptation v3.2 is already installed.
Installed version of diffusers: 0.25.0
[Dreambooth] diffusers v0.25.0 is already installed.
Installed version of discord-webhook: 1.3.0
[Dreambooth] discord-webhook v1.3.0 is already installed.
Installed version of fastapi: 0.94.0
[Dreambooth] fastapi is already installed.
Installed version of gitpython: 3.1.32
[Dreambooth] gitpython v3.1.40 is not installed.
Successfully installed gitpython-3.1.42

Installed version of pytorch_optimizer: 2.12.0
[Dreambooth] pytorch_optimizer v2.12.0 is already installed.
Installed version of Pillow: 9.5.0
[Dreambooth] Pillow is already installed.
Installed version of tqdm: 4.66.2
[Dreambooth] tqdm is already installed.
Installed version of tomesd: 0.1.3
[Dreambooth] tomesd v0.1.2 is already installed.
Installed version of tensorboard: 2.13.0
[Dreambooth] tensorboard v2.13.0 is already installed.
[+] torch version 2.1.2+cu121 installed.
[+] torchvision version 0.16.2+cu121 installed.
[+] accelerate version 0.21.0 installed.
[+] diffusers version 0.25.0 installed.
[+] bitsandbytes version 0.41.2.post2 installed.
[!] xformers NOT installed.
--------------------------------------------------------
| You are not up to date with the most recent release. |
| Consider running `git pull` to update.               |
--------------------------------------------------------
Launching Web UI with arguments: --update-check --pin-shared-memory --cuda-malloc --cuda-stream
Using cudaMallocAsync backend.
Total VRAM 8192 MB, total RAM 32702 MB
Set vram state to: NORMAL_VRAM
Always pin shared GPU memory
Device: cuda:0 NVIDIA GeForce RTX 2070 SUPER : cudaMallocAsync
VAE dtype: torch.float32
CUDA Stream Activated:  True
Using pytorch cross attention
ControlNet preprocessor location: D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\models\ControlNetPreprocessor
*** Error loading script: console_log_patch.py
    Traceback (most recent call last):
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 17, in <module>
        from scripts.reactor_logger import logger
    ModuleNotFoundError: No module named 'scripts.reactor_logger'

---
*** Error loading script: reactor_api.py
    Traceback (most recent call last):
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\extensions\sd-webui-reactor\scripts\reactor_api.py", line 17, in <module>
        from scripts.reactor_swapper import EnhancementOptions, swap_face, DetectionOptions
    ModuleNotFoundError: No module named 'scripts.reactor_swapper'

---
*** Error loading script: reactor_faceswap.py
    Traceback (most recent call last):
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 18, in <module>
        from reactor_ui import (
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\extensions\sd-webui-reactor\reactor_ui\__init__.py", line 2, in <module>
        import reactor_ui.reactor_tools_ui as ui_tools
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\extensions\sd-webui-reactor\reactor_ui\reactor_tools_ui.py", line 2, in <module>
        from scripts.reactor_swapper import build_face_model, blend_faces
    ModuleNotFoundError: No module named 'scripts.reactor_swapper'

---
*** Error loading script: reactor_helpers.py
    Traceback (most recent call last):
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 14, in <module>
        from scripts.reactor_globals import DEVICE, BASE_PATH, FACE_MODELS_PATH, IS_SDNEXT
    ModuleNotFoundError: No module named 'scripts.reactor_globals'

---
*** Error loading script: reactor_logger.py
    Traceback (most recent call last):
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\extensions\sd-webui-reactor\scripts\reactor_logger.py", line 6, in <module>
        from scripts.reactor_globals import IS_RUN
    ModuleNotFoundError: No module named 'scripts.reactor_globals'

---
*** Error loading script: reactor_swapper.py
    Traceback (most recent call last):
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 14, in <module>
        from scripts.reactor_globals import FACE_MODELS_PATH
    ModuleNotFoundError: No module named 'scripts.reactor_globals'

---
*** Error loading script: reactor_version.py
    Traceback (most recent call last):
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\extensions\sd-webui-reactor\scripts\reactor_version.py", line 4, in <module>
        from scripts.reactor_logger import logger, get_Run, set_Run
    ModuleNotFoundError: No module named 'scripts.reactor_logger'

---
*** Error loading script: reactor_xyz.py
    Traceback (most recent call last):
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\extensions\sd-webui-reactor\scripts\reactor_xyz.py", line 8, in <module>
        from scripts.reactor_helpers import (
    ModuleNotFoundError: No module named 'scripts.reactor_helpers'

---
Loading weights [c8df560d29] from D:\Developement\Stable Diffusion\stable-diffusion-webui-forge\stable-diffusion-webui-forge\models\Stable-diffusion\juggernautXL_v9Rdphoto2Lightning.safetensors
2024-03-14 08:27:11,199 - ControlNet - INFO - ControlNet UI callback registered.
model_type EPS
UNet ADM Dimension 2816
Running on local URL:  http://127.0.0.1:7860
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE

To create a public link, set `share=True` in `launch()`.
Startup time: 47.3s (prepare environment: 30.4s, import torch: 5.6s, import gradio: 1.2s, setup paths: 1.6s, initialize shared: 0.2s, other imports: 0.5s, load scripts: 3.9s, create ui: 1.3s, gradio launch: 2.6s).
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_g.logit_scale', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids'}
To load target model SDXLClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  7110.539154052734
[Memory Management] Model Memory (MB) =  2144.3546981811523
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  3942.184455871582
Moving model(s) has taken 0.61 seconds
Model loaded in 6.5s (load weights from disk: 0.7s, forge instantiate config: 0.2s, forge load real models: 3.8s, forge finalize: 0.9s, calculate empty prompt: 0.9s).
Advanced elements visible: False
```

**Comment by Diffus3d** [comment]
I also have this issue.  I'm using the venv folder and models from my automatic 1111 installation, perhaps related?

**Comment by satosCZ** [comment]
Thank you, this helped.
