### ISSUE TITLE
[SOLVED] Error loading script: faceswap.py and ModuleNotFoundError: No module named 'insightface.model_zoo'

### ISSUE THREAD

**Issue by mrmihaell** [Gourieff/sd-webui-reactor#41]
**Сделал все по инструкции**

```
Collecting insightface==0.7.3
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy in f:\stable_portable\venv\lib\site-packages (from insightface==0.7.3) (1.23.3)
Requirement already satisfied: onnx in f:\stable_portable\venv\lib\site-packages (from insightface==0.7.3) (1.14.0)
Requirement already satisfied: tqdm in f:\stable_portable\venv\lib\site-packages (from insightface==0.7.3) (4.65.0)
Requirement already satisfied: requests in f:\stable_portable\venv\lib\site-packages (from insightface==0.7.3) (2.25.1)
Requirement already satisfied: matplotlib in f:\stable_portable\venv\lib\site-packages (from insightface==0.7.3) (3.7.1)
Requirement already satisfied: Pillow in f:\stable_portable\venv\lib\site-packages (from insightface==0.7.3) (9.4.0)
Requirement already satisfied: scipy in f:\stable_portable\venv\lib\site-packages (from insightface==0.7.3) (1.10.1)
Collecting scikit-learn (from insightface==0.7.3)
  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/96/cf/a714a655266229b51eb2bda117f15275f12457887f165f3c1cc58ab502f1/scikit_learn-1.3.0-cp310-cp310-win_amd64.whl.metadata
  Using cached scikit_learn-1.3.0-cp310-cp310-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: scikit-image in f:\stable_portable\venv\lib\site-packages (from insightface==0.7.3) (0.19.2)
Requirement already satisfied: easydict in f:\stable_portable\venv\lib\site-packages (from insightface==0.7.3) (1.10)
Collecting cython (from insightface==0.7.3)
  Obtaining dependency information for cython from https://files.pythonhosted.org/packages/6d/0b/889b9b839ea7237eb6048191fe653c17ce93e298495eaf8f893cff748951/Cython-3.0.0-cp310-cp310-win_amd64.whl.metadata
  Using cached Cython-3.0.0-cp310-cp310-win_amd64.whl.metadata (3.2 kB)
Collecting albumentations (from insightface==0.7.3)
  Obtaining dependency information for albumentations from https://files.pythonhosted.org/packages/9b/f6/c486cedb4f75147232f32ec4c97026714cfef7c7e247a1f0427bc5489f66/albumentations-1.3.1-py3-none-any.whl.metadata
  Using cached albumentations-1.3.1-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: prettytable in f:\stable_portable\venv\lib\site-packages (from insightface==0.7.3) (3.8.0)
Requirement already satisfied: PyYAML in f:\stable_portable\venv\lib\site-packages (from albumentations->insightface==0.7.3) (6.0)
Collecting qudida>=0.0.4 (from albumentations->insightface==0.7.3)
  Using cached qudida-0.0.4-py3-none-any.whl (3.5 kB)
Collecting opencv-python-headless>=4.1.1 (from albumentations->insightface==0.7.3)
  Obtaining dependency information for opencv-python-headless>=4.1.1 from https://files.pythonhosted.org/packages/60/e7/a6dedca760db7a4686fd3b6053487ad4ad4d8f0591295dc8a9cf35269c42/opencv_python_headless-4.8.0.74-cp37-abi3-win_amd64.whl.metadata
  Using cached opencv_python_headless-4.8.0.74-cp37-abi3-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: networkx>=2.2 in f:\stable_portable\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (3.0)
Requirement already satisfied: imageio>=2.4.1 in f:\stable_portable\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (2.26.0)
Requirement already satisfied: tifffile>=2019.7.26 in f:\stable_portable\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (2023.2.28)
Requirement already satisfied: PyWavelets>=1.1.1 in f:\stable_portable\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (1.4.1)
Requirement already satisfied: packaging>=20.0 in f:\stable_portable\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (23.0)
Requirement already satisfied: contourpy>=1.0.1 in f:\stable_portable\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (1.0.7)
Requirement already satisfied: cycler>=0.10 in f:\stable_portable\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in f:\stable_portable\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (4.39.0)
Requirement already satisfied: kiwisolver>=1.0.1 in f:\stable_portable\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (1.4.4)
Requirement already satisfied: pyparsing>=2.3.1 in f:\stable_portable\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in f:\stable_portable\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (2.8.2)
Requirement already satisfied: protobuf>=3.20.2 in f:\stable_portable\venv\lib\site-packages (from onnx->insightface==0.7.3) (4.23.4)
Requirement already satisfied: typing-extensions>=3.6.2.1 in f:\stable_portable\venv\lib\site-packages (from onnx->insightface==0.7.3) (4.5.0)
Requirement already satisfied: wcwidth in f:\stable_portable\venv\lib\site-packages (from prettytable->insightface==0.7.3) (0.2.6)
Requirement already satisfied: chardet<5,>=3.0.2 in f:\stable_portable\venv\lib\site-packages (from requests->insightface==0.7.3) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in f:\stable_portable\venv\lib\site-packages (from requests->insightface==0.7.3) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in f:\stable_portable\venv\lib\site-packages (from requests->insightface==0.7.3) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in f:\stable_portable\venv\lib\site-packages (from requests->insightface==0.7.3) (2022.12.7)
Collecting joblib>=1.1.1 (from scikit-learn->insightface==0.7.3)
  Obtaining dependency information for joblib>=1.1.1 from https://files.pythonhosted.org/packages/28/08/9dcdaa5aac4634e4c23af26d92121f7ce445c630efa0d3037881ae2407fb/joblib-1.3.1-py3-none-any.whl.metadata
  Using cached joblib-1.3.1-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: threadpoolctl>=2.0.0 in f:\stable_portable\venv\lib\site-packages (from scikit-learn->insightface==0.7.3) (3.2.0)
Requirement already satisfied: colorama in f:\stable_portable\venv\lib\site-packages (from tqdm->insightface==0.7.3) (0.4.6)
Requirement already satisfied: six>=1.5 in f:\stable_portable\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->insightface==0.7.3) (1.16.0)
Using cached albumentations-1.3.1-py3-none-any.whl (125 kB)
Using cached Cython-3.0.0-cp310-cp310-win_amd64.whl (2.8 MB)
Using cached scikit_learn-1.3.0-cp310-cp310-win_amd64.whl (9.2 MB)
Using cached joblib-1.3.1-py3-none-any.whl (301 kB)
Using cached opencv_python_headless-4.8.0.74-cp37-abi3-win_amd64.whl (38.0 MB)
Building wheels for collected packages: insightface
  Building wheel for insightface (pyproject.toml): started
  Building wheel for insightface (pyproject.toml): finished with status 'error'
Failed to build insightface
Checking ReActor (ex Roop-GE) requirements...
--- PLEASE, RESTART the Server! ---



Launching Web UI with arguments: --xformers --autolaunch --theme=dark
2023-08-06 23:22:38,213 - ControlNet - INFO - ControlNet v1.1.234
ControlNet preprocessor location: F:\Stable_portable\extensions\sd-webui-controlnet\annotator\downloads
2023-08-06 23:22:38,275 - ControlNet - INFO - ControlNet v1.1.234
Error loading script: console_log_patch.py
Traceback (most recent call last):
  File "F:\Stable_portable\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "F:\Stable_portable\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Stable_portable\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 5, in <module>
    from insightface.model_zoo.model_zoo import ModelRouter, PickableInferenceSession
ModuleNotFoundError: No module named 'insightface.model_zoo'

23:22:38 - ReActor - STATUS - Running v0.3.0
Error loading script: faceswap.py
Traceback (most recent call last):
  File "F:\Stable_portable\modules\scripts.py", line 248, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "F:\Stable_portable\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Stable_portable\extensions\sd-webui-reactor\scripts\faceswap.py", line 17, in <module>
    from scripts.console_log_patch import apply_logging_patch
  File "F:\Stable_portable\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 5, in <module>
    from insightface.model_zoo.model_zoo import ModelRouter, PickableInferenceSession
ModuleNotFoundError: No module named 'insightface.model_zoo'

```

**После этого пробовал устанавливать по инструкции в случае проблем:**

```
F:\Stable_portable\venv\Scripts>activate

(venv) F:\Stable_portable\venv\Scripts>python -m pip install -U pip
Requirement already satisfied: pip in f:\stable_portable\venv\lib\site-packages (23.2.1)
DEPRECATION: pytorch-lightning 1.7.6 has a non-standard dependency specifier torch>=1.9.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pytorch-lightning or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

(venv) F:\Stable_portable\venv\Scripts>pip uninstall protobuf
Found existing installation: protobuf 4.23.4
Uninstalling protobuf-4.23.4:
  Would remove:
    f:\stable_portable\venv\lib\site-packages\google\_upb\_message.pyd
    f:\stable_portable\venv\lib\site-packages\google\protobuf\*
    f:\stable_portable\venv\lib\site-packages\protobuf-4.23.4.dist-info\*
Proceed (Y/n)? y
  Successfully uninstalled protobuf-4.23.4
ERROR: Exception:
Traceback (most recent call last):
  File "F:\Stable_portable\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "F:\Stable_portable\venv\lib\site-packages\pip\_internal\commands\uninstall.py", line 110, in run
    uninstall_pathset.commit()
  File "F:\Stable_portable\venv\lib\site-packages\pip\_internal\req\req_uninstall.py", line 432, in commit
    self._moved_paths.commit()
  File "F:\Stable_portable\venv\lib\site-packages\pip\_internal\req\req_uninstall.py", line 278, in commit
    save_dir.cleanup()
  File "F:\Stable_portable\venv\lib\site-packages\pip\_internal\utils\temp_dir.py", line 173, in cleanup
    rmtree(self._path)
  File "F:\Stable_portable\venv\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 291, in wrapped_f
    return self(f, *args, **kw)
  File "F:\Stable_portable\venv\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 381, in __call__
    do = self.iter(retry_state=retry_state)
  File "F:\Stable_portable\venv\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 327, in iter
    raise retry_exc.reraise()
  File "F:\Stable_portable\venv\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 160, in reraise
    raise self.last_attempt.result()
  File "F:\Stable_portable\python\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "F:\Stable_portable\python\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "F:\Stable_portable\venv\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 384, in __call__
    result = fn(*args, **kwargs)
  File "F:\Stable_portable\venv\lib\site-packages\pip\_internal\utils\misc.py", line 130, in rmtree
    shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)
  File "F:\Stable_portable\python\lib\shutil.py", line 749, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "F:\Stable_portable\python\lib\shutil.py", line 619, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "F:\Stable_portable\python\lib\shutil.py", line 617, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Отказано в доступе: 'F:\\Stable_portable\\venv\\Lib\\site-packages\\google\\~upb\\_message.pyd'

(venv) F:\Stable_portable\venv\Scripts>pip install protobuf==3.20.3
WARNING: Ignoring invalid distribution -rotobuf (f:\stable_portable\venv\lib\site-packages)
Collecting protobuf==3.20.3
  Downloading protobuf-3.20.3-cp310-cp310-win_amd64.whl (904 kB)
     ---------------------------------------- 904.0/904.0 kB 3.2 MB/s eta 0:00:00
WARNING: Ignoring invalid distribution -rotobuf (f:\stable_portable\venv\lib\site-packages)
DEPRECATION: pytorch-lightning 1.7.6 has a non-standard dependency specifier torch>=1.9.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pytorch-lightning or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: protobuf
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rembg 2.0.38 requires asyncer>=0.0.2, which is not installed.
rembg 2.0.38 requires filetype>=1.2.0, which is not installed.
rembg 2.0.38 requires imagehash>=4.3.1, which is not installed.
rembg 2.0.38 requires opencv-python-headless>=4.6.0.66, which is not installed.
rembg 2.0.38 requires watchdog>=2.1.9, which is not installed.
open-clip-torch 2.7.0 requires protobuf==3.20.0, but you have protobuf 3.20.3 which is incompatible.
rembg 2.0.38 requires numpy>=1.23.5, but you have numpy 1.23.3 which is incompatible.
rembg 2.0.38 requires scikit-image>=0.19.3, but you have scikit-image 0.19.2 which is incompatible.
Successfully installed protobuf-3.20.3
```

**Все работает кроме этого. С рупом стандартным было что-то похожее**

**Comment by Gourieff** [comment]
> PermissionError: [WinError 5] Отказано в доступе: 'F:\\Stable_portable\\venv\\Lib\\site-packages\\google\\~upb\\_message.pyd'

> WARNING: Ignoring invalid distribution -rotobuf (f:\stable_portable\venv\lib\site-packages)

Это говорит о том, что не всё прошло гладко
В директории "f:\stable_portable\venv\lib\site-packages" необходимо удалить все папки с именами, начинающимися с "~", и то же самое в директории "f:\stable_portable\venv\lib\site-packages\google"
А затем снова повторить "pip uninstall protobuf" и "pip install protobuf==3.20.3"
И главное, делать это при полностью выключенном А1111

> ModuleNotFoundError: No module named 'insightface.model_zoo'

По идее такая ошибка должна была пропасть после перезагрузки A1111
В директории "f:\stable_portable\venv\lib\site-packages\" есть папки insightface и insightface-0.7.3.dist-info?
Внутри insightface есть ли папка model_zoo?

**Comment by mrmihaell** [comment]
Спасибо за быстрый ответ. В конце установки pip install insightface==0.7.3 я получил такое
```
Installing collected packages: opencv-python-headless, joblib, cython, scikit-learn, qudida, albumentations, insightface
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rembg 2.0.38 requires asyncer>=0.0.2, which is not installed.
rembg 2.0.38 requires filetype>=1.2.0, which is not installed.
rembg 2.0.38 requires imagehash>=4.3.1, which is not installed.
rembg 2.0.38 requires watchdog>=2.1.9, which is not installed.
rembg 2.0.38 requires numpy>=1.23.5, but you have numpy 1.23.3 which is incompatible.
rembg 2.0.38 requires scikit-image>=0.19.3, but you have scikit-image 0.19.2 which is incompatible.
Successfully installed albumentations-1.3.1 cython-3.0.0 insightface-0.7.3 joblib-1.3.1 opencv-python-headless-4.8.0.74 qudida-0.0.4 scikit-learn-1.3.0
```
И то же самое при установке pip install protobuf==3.20.3

```
Installing collected packages: protobuf
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rembg 2.0.38 requires asyncer>=0.0.2, which is not installed.
rembg 2.0.38 requires filetype>=1.2.0, which is not installed.
rembg 2.0.38 requires imagehash>=4.3.1, which is not installed.
rembg 2.0.38 requires watchdog>=2.1.9, which is not installed.
open-clip-torch 2.7.0 requires protobuf==3.20.0, but you have protobuf 3.20.3 which is incompatible.
rembg 2.0.38 requires numpy>=1.23.5, but you have numpy 1.23.3 which is incompatible.
rembg 2.0.38 requires scikit-image>=0.19.3, but you have scikit-image 0.19.2 which is incompatible.
Successfully installed protobuf-3.20.3
```
Но все работает теперь, спасибо большое за помощь!
