### ISSUE TITLE
Reactor doesn't show after installing

### ISSUE THREAD

**Issue by DemDem18** [Gourieff/sd-webui-reactor#461]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Hello everyone

I have seen several times in the bug reports things quite similar to my problem. I am on PC and I have followed the installation process of the extension correctly, but nothing works. It seems that the problem always comes from InsightFace, without me being able to do anything about it.

Thanks in advance to those who will take the time to help me.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### Sysinfo

I am on PC, with an NVIDIA GeForce RTX 3070 Laptop GPU and A1111 operating system.

### Relevant console log

```Shell
Launching Web UI with arguments: --theme dark --xformers
*** Error loading script: console_log_patch.py
    Traceback (most recent call last):
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 4, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_api.py
    Traceback (most recent call last):
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_api.py", line 23, in <module>
        from scripts.reactor_swapper import EnhancementOptions, swap_face, DetectionOptions
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 11, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 18, in <module>
        from reactor_ui import (
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\extensions\sd-webui-reactor\reactor_ui\__init__.py", line 2, in <module>
        import reactor_ui.reactor_tools_ui as ui_tools
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\extensions\sd-webui-reactor\reactor_ui\reactor_tools_ui.py", line 2, in <module>
        from scripts.reactor_swapper import build_face_model, blend_faces
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 11, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_helpers.py
    Traceback (most recent call last):
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in <module>
        from insightface.app.common import Face
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_logger.py
    Traceback (most recent call last):
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_logger.py", line 7, in <module>
        from scripts.reactor_helpers import addLoggingLevel
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in <module>
        from insightface.app.common import Face
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_swapper.py
    Traceback (most recent call last):
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 11, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_version.py
    Traceback (most recent call last):
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_version.py", line 4, in <module>
        from scripts.reactor_logger import logger, get_Run, set_Run
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_logger.py", line 7, in <module>
        from scripts.reactor_helpers import addLoggingLevel
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in <module>
        from insightface.app.common import Face
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_xyz.py
    Traceback (most recent call last):
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_xyz.py", line 8, in <module>
        from scripts.reactor_helpers import (
      File "C:\Users\eu2ju\OneDrive\Bureau\A1111\webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in <module>
        from insightface.app.common import Face
    ModuleNotFoundError: No module named 'insightface'
```

**Comment by DemDem18** [comment]
Well, I suppose this is the kind of beginner's mistake, but it is simply enough to download controlnet beforehand for reactor to work. I am leaving my solution message here, maybe an idiot like me will go through this again. My apologies.

**Comment by valtezar** [comment]
> Well, I suppose this is the kind of beginner's mistake, but it is simply enough to download controlnet beforehand for reactor to work. I am leaving my solution message here, maybe an idiot like me will go through this again. My apologies.

Exactly the same problem, and no, it's not a beginner's mistake, I had ControlNet installed, and exactly the same error, I can't solve it yet either...

**Comment by Gourieff** [comment]
https://github.com/Gourieff/sd-webui-reactor?tab=readme-ov-file#insightfacebuild

https://github.com/Gourieff/sd-webui-reactor/issues?q=is%3Aissue+is%3Aclosed+No+module+named+%27insightface%27
