### ISSUE TITLE
Get console errors and Reactor does not appear in SD Webui Forge UI.

### ISSUE THREAD

**Issue by HooliGali** [Gourieff/sd-webui-reactor#468]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I Get console errors when running  SD Webui Forge UI and Reactor does not appear in SD Webui Forge UI.

### Steps to reproduce the problem

1. Install Reactor following installation steps in Install guide including installing build tools "Desktop Development with C++"  then Installing Reactor extension through UI from extensions tab in SD Webui Forge then restarting UI.  

2.  Get Error Loading script messages in console. Same console errors appear if I disable all other extensions and run web UI again. Webi UI forge runs but does not have Reactor in UI. Tried running through the troubleshooting steps "II. Any problems with installing Insightface or other dependencies", still get same errors in console.

### Sysinfo

[sysinfo-2024-06-21-01-10.json](https://github.com/user-attachments/files/15921640/sysinfo-2024-06-21-01-10.json)

### Relevant console log

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-277-g0af28699
Commit hash: 0af28699c45c1c5bf9cb6818caac6ce881123131
CUDA 12.1
Installing forge_legacy_preprocessor requirement: changing opencv-python version from 4.10.0.84 to 4.8.0
Installing sd-forge-controlnet requirement: changing opencv-python version from 4.10.0.84 to 4.8.0
Path J:\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads does not exist. Skip setting --controlnet-preprocessor-models-dir
Launching Web UI with arguments: --skip-torch-cuda-test --xformers --cuda-malloc --cuda-stream --forge-ref-a1111-home J:\stable-diffusion-webui --ckpt-dir J:\stable-diffusion-webui\models\Stable-diffusion --vae-dir J:\stable-diffusion-webui\models\VAE --hypernetwork-dir J:\stable-diffusion-webui\models\hypernetworks --embeddings-dir J:\stable-diffusion-webui\embeddings --lora-dir J:\stable-diffusion-webui\models\lora --controlnet-dir J:\stable-diffusion-webui\models\ControlNet
Using cudaMallocAsync backend.
Total VRAM 12288 MB, total RAM 130878 MB
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
xformers version: 0.0.23.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
Hint: your device supports --pin-shared-memory for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  True
Using xformers cross attention
ControlNet preprocessor location: J:\webui_forge_cu121_torch21\webui\models\ControlNetPreprocessor
*** Error loading script: console_log_patch.py
    Traceback (most recent call last):
      File "J:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\webui_forge_cu121_torch21\webui\extensions\sd-webui-reactor-main\scripts\console_log_patch.py", line 17, in <module>
        from scripts.reactor_logger import logger
    ModuleNotFoundError: No module named 'scripts.reactor_logger'

---
*** Error loading script: reactor_api.py
    Traceback (most recent call last):
      File "J:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\webui_forge_cu121_torch21\webui\extensions\sd-webui-reactor-main\scripts\reactor_api.py", line 23, in <module>
        from scripts.reactor_swapper import EnhancementOptions, swap_face, DetectionOptions
    ModuleNotFoundError: No module named 'scripts.reactor_swapper'

---
*** Error loading script: reactor_faceswap.py
    Traceback (most recent call last):
      File "J:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\webui_forge_cu121_torch21\webui\extensions\sd-webui-reactor-main\scripts\reactor_faceswap.py", line 18, in <module>
        from reactor_ui import (
      File "J:\webui_forge_cu121_torch21\webui\extensions\sd-webui-reactor-main\reactor_ui\__init__.py", line 2, in <module>
        import reactor_ui.reactor_tools_ui as ui_tools
      File "J:\webui_forge_cu121_torch21\webui\extensions\sd-webui-reactor-main\reactor_ui\reactor_tools_ui.py", line 2, in <module>
        from scripts.reactor_swapper import build_face_model, blend_faces
    ModuleNotFoundError: No module named 'scripts.reactor_swapper'

---
*** Error loading script: reactor_helpers.py
    Traceback (most recent call last):
      File "J:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\webui_forge_cu121_torch21\webui\extensions\sd-webui-reactor-main\scripts\reactor_helpers.py", line 14, in <module>
        from scripts.reactor_globals import DEVICE, BASE_PATH, FACE_MODELS_PATH, IS_SDNEXT
    ModuleNotFoundError: No module named 'scripts.reactor_globals'

---
*** Error loading script: reactor_logger.py
    Traceback (most recent call last):
      File "J:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\webui_forge_cu121_torch21\webui\extensions\sd-webui-reactor-main\scripts\reactor_logger.py", line 6, in <module>
        from scripts.reactor_globals import IS_RUN
    ModuleNotFoundError: No module named 'scripts.reactor_globals'

---
*** Error loading script: reactor_swapper.py
    Traceback (most recent call last):
      File "J:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\webui_forge_cu121_torch21\webui\extensions\sd-webui-reactor-main\scripts\reactor_swapper.py", line 14, in <module>
        from scripts.reactor_globals import FACE_MODELS_PATH
    ModuleNotFoundError: No module named 'scripts.reactor_globals'

---
*** Error loading script: reactor_version.py
    Traceback (most recent call last):
      File "J:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\webui_forge_cu121_torch21\webui\extensions\sd-webui-reactor-main\scripts\reactor_version.py", line 4, in <module>
        from scripts.reactor_logger import logger, get_Run, set_Run
    ModuleNotFoundError: No module named 'scripts.reactor_logger'

---
*** Error loading script: reactor_xyz.py
    Traceback (most recent call last):
      File "J:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "J:\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "J:\webui_forge_cu121_torch21\webui\extensions\sd-webui-reactor-main\scripts\reactor_xyz.py", line 8, in <module>
        from scripts.reactor_helpers import (
    ModuleNotFoundError: No module named 'scripts.reactor_helpers'
```

### Additional information

I get similar errors as in this thread https://github.com/Gourieff/sd-webui-reactor/issues/396 but I don't have dreambooth installed. Apart from the built in extensions in SD webui forge the only extensions I have are sd-forge-layerdiffuse-main, stable-diffusion-webui-GPU-temperature-protection-main, sd-forge-layerdiffuse-main and reactor itself.

**Comment by RichardGoldbergSchool** [comment]
Did you install the new Depth Anything v2? For whatever reason, having that extension installed produces the exact same errors for me.

**Comment by HooliGali** [comment]
I do not have Depth anything v2 installed but I do have "depth-anything==2024.1.22.0" package installed according to sysinfo.

**Comment by KungFuFurniture** [comment]
I have this same error...  I have no idea what it is.  I have a1111 installed and everything works fine.   Maybe it should be noted that I cannot get any faceswap type extension to work with forge.  All seem to produce a similar error.
