### ISSUE TITLE
[Feature]: other Models

### ISSUE THREAD

**Issue by kalle07** [Gourieff/sd-webui-reactor#478]
### Feature description

hey,

for now only "inswapper_128" works
what is with other models like:
codeformer.onnx
ghost_unet_3_block.onnx
simswap_512_unofficial.onnx
uniface_256.onnx

they all endup with error:
---
Total progress: 100%|██████████████████████████████████████████████████████████████████| 40/40 [00:22<00:00,  1.77it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [00:14<00:00,  2.81it/s]
Memory cleanup has taken 0.49 seconds██████████████████████████████████████████████████| 40/40 [00:13<00:00,  2.86it/s]
09:57:16 - ReActor - STATUS - Working: source face index [0], target face index [0]
09:57:16 - ReActor - STATUS - Using Loaded Source Face Model: vero03.safetensors
09:57:16 - ReActor - STATUS - Analyzing Target Image...
09:57:17 - ReActor - STATUS - Detecting Source Face, Index = 0
09:57:17 - ReActor - STATUS - Detected: -43- y.o. Female
09:57:18 - ReActor - STATUS - Detecting Target Face, Index = 0
09:57:18 - ReActor - STATUS - Detected: -29- y.o. Female
09:57:18 - ReActor - STATUS - Swapping Source into Target
*** Error running postprocess_image: E:\WebUI_Forge\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "E:\WebUI_Forge\webui\modules\scripts.py", line 883, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "E:\WebUI_Forge\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 465, in postprocess_image
        result, output, swapped = swap_face(
      File "E:\WebUI_Forge\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 616, in swap_face
        result_image, output, swapped = operate(source_img,target_img,target_img_orig,model,source_faces_index,faces_index,source_faces,target_faces,gender_source,gender_target,source_face,wrong_gender,source_age,source_gender,output,swapped,mask_face,entire_mask_image,enhancement_options,detection_options)
      File "E:\WebUI_Forge\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 770, in operate
        swapped_image = face_swapper.get(result, target_face, source_face)
    AttributeError: 'RetinaFace' object has no attribute 'get'

---

**Comment by Gourieff** [comment]
The best face swapping model (among available for the Community) is still "inswapper_128"

>
what is with other models like:
codeformer.onnx
ghost_unet_3_block.onnx
simswap_512_unofficial.onnx
uniface_256.onnx
gfpgan_1.4.onnx

These models are not for face-swapping

**Comment by kalle07** [comment]
but 
gfpgan_1.4.onnx
is standart in reactor and it give that error ...

where i can change that, i can edit python  ;)

**Comment by Gourieff** [comment]
gfpgan_1.4.onnx - is the facerestoration model and it works fine from the box (if you downloaded it from here https://huggingface.co/datasets/Gourieff/ReActor/blob/main/models/facerestore_models/GFPGANv1.4.onnx)
but GFPGANv1.4.pth works faster
Anyway these models cannot be used as face-swapping models
