### ISSUE TITLE
ReActor stopped working after downloading another extension

### ISSUE THREAD

**Issue by ccas010** [Gourieff/sd-webui-reactor#536]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

I Downloaded the "FaceFusion" A1111 extension, and it messed up my A1111
first it didnt start up at all, after deleting the venv folder it started again but i have a new issue, reActor doenst work anymore
doesnt show up in my ui, and gives an error when i start up A1111, how do i fix this ?

### Steps to reproduce the problem

i donwloaded a extension called, facefusion

### Sysinfo

AMD Ryzen 5 5600X 6-Core Processor 3.70 GHz
64GB RAM
NVIDIA RTX 3060 12 GB
Windows 10

### Relevant console log

```Shell
I downloaded this extension, and my A1111 didnt boot up at all after that, it gave a error.
i deleted the venv folder and A1111 starts again, but now i have a new problem

My ReActor extension wont show up again, and it stopped working, very very very annoying

How do i solve this? the A1111 folder is 120GB large and i dont want to start all over again

this is the error log i get when i start up A1111:

*** Error loading script: console_log_patch.py
Traceback (most recent call last):
File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "D:\AI\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
module_spec.loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in call_with_frames_removed
File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 4, in
import insightface
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface_init.py", line 16, in
from . import model_zoo
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo_init_.py", line 1, in
from .model_zoo import get_model
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in
from .arcface_onnx import *
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in
import onnx
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\onnx_init_.py", line 77, in
from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: Een initialisatieroutine van de dynamic link library (DLL-bestand) is mislukt.

*** Error loading script: reactor_api.py
Traceback (most recent call last):
File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "D:\AI\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
module_spec.loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in call_with_frames_removed
File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_api.py", line 28, in
from scripts.reactor_swapper import EnhancementOptions, blend_faces, swap_face, DetectionOptions
File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 11, in
import insightface
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface_init.py", line 16, in
from . import model_zoo
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo_init_.py", line 1, in
from .model_zoo import get_model
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in
from .arcface_onnx import *
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in
import onnx
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\onnx_init_.py", line 77, in
from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: Een initialisatieroutine van de dynamic link library (DLL-bestand) is mislukt.

*** Error loading script: reactor_faceswap.py
Traceback (most recent call last):
File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "D:\AI\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
module_spec.loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in call_with_frames_removed
File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 18, in
from reactor_ui import (
File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\reactor_ui_init.py", line 2, in
import reactor_ui.reactor_tools_ui as ui_tools
File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\reactor_ui\reactor_tools_ui.py", line 2, in
from scripts.reactor_swapper import build_face_model, blend_faces
File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 11, in
import insightface
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface_init_.py", line 16, in
from . import model_zoo
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo_init_.py", line 1, in
from .model_zoo import get_model
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in
from .arcface_onnx import *
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in
import onnx
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\onnx_init_.py", line 77, in
from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: Een initialisatieroutine van de dynamic link library (DLL-bestand) is mislukt.

*** Error loading script: reactor_helpers.py
Traceback (most recent call last):
File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "D:\AI\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
module_spec.loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in call_with_frames_removed
File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in
from insightface.app.common import Face
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface_init.py", line 16, in
from . import model_zoo
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo_init_.py", line 1, in
from .model_zoo import get_model
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in
from .arcface_onnx import *
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in
import onnx
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\onnx_init_.py", line 77, in
from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: Een initialisatieroutine van de dynamic link library (DLL-bestand) is mislukt.

*** Error loading script: reactor_logger.py
Traceback (most recent call last):
File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "D:\AI\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
module_spec.loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in call_with_frames_removed
File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_logger.py", line 7, in
from scripts.reactor_helpers import addLoggingLevel
File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in
from insightface.app.common import Face
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface_init.py", line 16, in
from . import model_zoo
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo_init_.py", line 1, in
from .model_zoo import get_model
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in
from .arcface_onnx import *
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in
import onnx
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\onnx_init_.py", line 77, in
from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: Een initialisatieroutine van de dynamic link library (DLL-bestand) is mislukt.

*** Error loading script: reactor_swapper.py
Traceback (most recent call last):
File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "D:\AI\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
module_spec.loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in call_with_frames_removed
File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 11, in
import insightface
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface_init.py", line 16, in
from . import model_zoo
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo_init_.py", line 1, in
from .model_zoo import get_model
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in
from .arcface_onnx import *
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in
import onnx
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\onnx_init_.py", line 77, in
from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: Een initialisatieroutine van de dynamic link library (DLL-bestand) is mislukt.

*** Error loading script: reactor_version.py
Traceback (most recent call last):
File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "D:\AI\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
module_spec.loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in call_with_frames_removed
File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_version.py", line 4, in
from scripts.reactor_logger import logger, get_Run, set_Run
File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_logger.py", line 7, in
from scripts.reactor_helpers import addLoggingLevel
File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in
from insightface.app.common import Face
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface_init.py", line 16, in
from . import model_zoo
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo_init_.py", line 1, in
from .model_zoo import get_model
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in
from .arcface_onnx import *
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in
import onnx
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\onnx_init_.py", line 77, in
from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: Een initialisatieroutine van de dynamic link library (DLL-bestand) is mislukt.

*** Error loading script: reactor_xyz.py
Traceback (most recent call last):
File "D:\AI\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
script_module = script_loading.load_module(scriptfile.path)
File "D:\AI\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
module_spec.loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in call_with_frames_removed
File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_xyz.py", line 8, in
from scripts.reactor_helpers import (
File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in
from insightface.app.common import Face
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface_init.py", line 16, in
from . import model_zoo
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo_init_.py", line 1, in
from .model_zoo import get_model
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in
from .arcface_onnx import *
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in
import onnx
File "D:\AI\stable-diffusion-webui\venv\lib\site-packages\onnx_init_.py", line 77, in
from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: Een initialisatieroutine van de dynamic link library (DLL-bestand) is mislukt.

Loading weights [ec41bd2a82] from D:\AI\stable-diffusion-webui\models\Stable-diffusion\photon_v1.safetensors
Creating model from config: D:\AI\stable-diffusion-webui\configs\v1-inference.yaml
2024-09-27 00:27:00,239 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL: http://127.0.0.1:7860

To create a public link, set share=True in launch().
Startup time: 49.7s (prepare environment: 13.5s, import torch: 7.5s, import gradio: 1.9s, setup paths: 1.0s, initialize shared: 0.2s, other imports: 0.5s, list SD models: 0.2s, load scripts: 23.3s, create ui: 1.2s, gradio launch: 0.4s).
Applying attention optimization: xformers... done.
Model loaded in 4.8s (create model: 1.0s, apply weights to model: 2.5s, load textual inversion embeddings: 0.7s, calculate empty prompt: 0.4s).
```

**Comment by Gourieff** [comment]
Try to delete "onnx" and "onnxruntime" folders from the `D:\AI\stable-diffusion-webui\venv\lib\site-packages` directory and let A1111 to install this libs again according to the ReActor's requirements

**Comment by ccas010** [comment]
@Gourieff That didnt work, thanks for reacting

UPDATE:

I downloaded the cuda and cudnn again, and the extensions showed up. only now it cant find my gpu or something...

so it uses the cpu in stead of the gpu.

this is the error code:


2024-09-28 01:54:23.5918312 [E:onnxruntime:Default, provider_bridge_ort.cc:1992 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1637 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\AI\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2024-09-28 01:54:23.9001259 [E:onnxruntime:Default, provider_bridge_ort.cc:1992 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1637 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\AI\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2024-09-28 01:54:23.9360043 [E:onnxruntime:Default, provider_bridge_ort.cc:1992 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1637 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\AI\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2024-09-28 01:54:23.9784359 [E:onnxruntime:Default, provider_bridge_ort.cc:1992 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1637 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\AI\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2024-09-28 01:54:24.0421927 [E:onnxruntime:Default, provider_bridge_ort.cc:1992 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1637 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\AI\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

**Comment by Gourieff** [comment]
@ccas010 It detects wrong version of ort-gpu, try to downgrade onnxruntime-gpu to e.g. 1.17.1

**Comment by ccas010** [comment]
@Gourieff i really appreciate your reactions!

I deleted onnxruntime, and installed the version you mentioned, and i have still the same error when using reActor
when i start up A1111 it says reActor is working on CUDA as seen here:

venv "D:\AI\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.10.1
Commit hash: 82a973c04367123ae98bd9abdf80d9eda9b910e2
CUDA 12.1
Launching Web UI with arguments: --xformers --no-half-vae
[-] ADetailer initialized. version: 24.9.0, num models: 10
ControlNet preprocessor location: D:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2024-10-03 14:28:40,206 - ControlNet - INFO - ControlNet v1.1.455
14:28:41 - ReActor - STATUS - Running v0.7.1-b1 on Device: CUDA
Loading weights [ec41bd2a82] from D:\AI\stable-diffusion-webui\models\Stable-diffusion\photon_v1.safetensors
2024-10-03 14:28:41,538 - ControlNet - INFO - ControlNet UI callback registered.
Creating model from config: D:\AI\stable-diffusion-webui\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860



but when i create an image using reActor it still gives the same error as seen here:


2024-10-03 14:29:27.2282929 [E:onnxruntime:Default, provider_bridge_ort.cc:1992 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1637 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\AI\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"


I use CUDA 12.1:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0

cudnn 9.4.0


what am i not seeing? what am i doing wrong ???


this all started when i installed the extension Facefusion on A1111

**Comment by ccas010** [comment]
Thanks for the update!

No more errors! everything is working fine!

1 question tho...
Did it remove the error, but still working on the CPU
or is it fixed and working on cuda ?

thanks anyway! you are a boss!
