### ISSUE TITLE
faceswap.py error

### ISSUE THREAD

**Issue by ZeFluffyNuphkin** [Gourieff/sd-webui-reactor#54]
When I try to generate an image using this extension, I always get this error message

```
Error running postprocess_batch: F:\Stable diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\faceswap.py
Traceback (most recent call last):
  File "F:\Stable diffusion\stable-diffusion-webui\modules\scripts.py", line 422, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "F:\Stable diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\faceswap.py", line 258, in postprocess_image
    result = swap_face(
  File "F:\Stable diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\swapper.py", line 221, in swap_face
    face_swapper = getFaceSwapModel(model_path)
  File "F:\Stable diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\swapper.py", line 73, in getFaceSwapModel
    FS_MODEL = insightface.model_zoo.get_model(model_path, providers=providers)
  File "F:\Stable diffusion\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "F:\Stable diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 21, in patched_get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "F:\Stable diffusion\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "F:\Stable diffusion\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "F:\Stable diffusion\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from F:\Stable diffusion\stable-diffusion-webui\models/roop\inswapper_128.onnx failed:Protobuf parsing failed.
```

Does anyone know what could be causing this?

**Comment by Gourieff** [comment]
Something wrong with "inswapper_128.onnx" model
Try Troubleshooting Sec V: https://github.com/Gourieff/sd-webui-reactor#troubleshooting

**Comment by ZeFluffyNuphkin** [comment]
> Something wrong with "inswapper_128.onnx" model Try Troubleshooting Sec V: https://github.com/Gourieff/sd-webui-reactor#troubleshooting

Thank you so much that actually worked perfectly
