### ISSUE TITLE
Error running install.py (A1111, windows 11 24H2) 

### ISSUE THREAD

**Issue by septerlt** [Gourieff/sd-webui-reactor#542]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Installed a clean windows 11 24H2 system, and latest stable Automatic1111 (Python 3.10.6 + Git) and got an error when installing Reactor: 

`*** Error running install.py for extension E:\NeuroHub\A1111\extensions\sd-webui-reactor.
*** Command: "E:\NeuroHub\A1111\venv\Scripts\python.exe" "E:\NeuroHub\A1111\extensions\sd-webui-reactor\install.py"
*** Error code: 1
*** stderr: E:\NeuroHub\A1111\extensions\sd-webui-reactor\install.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
***   import pkg_resources
*** Traceback (most recent call last):
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1348, in do_open
***     h.request(req.get_method(), req.selector, req.data, headers,
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
***     self._send_request(method, url, body, headers, encode_chunked)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request
***     self.endheaders(body, encode_chunked=encode_chunked)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
***     self._send_output(message_body, encode_chunked=encode_chunked)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
***     self.send(msg)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
***     self.connect()
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1454, in connect
***     self.sock = self._context.wrap_socket(self.sock,
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 513, in wrap_socket
***     return self.sslsocket_class._create(
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1071, in _create
***     self.do_handshake()
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1342, in do_handshake
***     self._sslobj.do_handshake()
*** ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
***
*** During handling of the above exception, another exception occurred:
***
*** Traceback (most recent call last):
***   File "E:\NeuroHub\A1111\extensions\sd-webui-reactor\install.py", line 62, in <module>
***     download(model_url, model_path)
***   File "E:\NeuroHub\A1111\extensions\sd-webui-reactor\install.py", line 53, in download
***     request = urllib.request.urlopen(url)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
***     return opener.open(url, data, timeout)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
***     response = meth(req, response)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
***     response = self.parent.error(
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 557, in error
***     result = self._call_chain(*args)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
***     result = func(*args)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 749, in http_error_302
***     return self.parent.open(new, timeout=req.timeout)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open
***     response = self._open(req, data)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 536, in _open
***     result = self._call_chain(self.handle_open, protocol, protocol +
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
***     result = func(*args)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1391, in https_open
***     return self.do_open(http.client.HTTPSConnection, req,
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1351, in do_open
***     raise URLError(err)
*** urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>`

### Steps to reproduce the problem

1. Install latest Windows 11 24H2
2. Install Python 3.10.6
3. Install Git
4. Install latest stable Automatic1111 from GIT CLONE command
5. Install Reactor from Automatic1111 "extensions" tab. Getting Error running install.py for extension E:\NeuroHub\A1111\extensions\sd-webui-reactor

### Sysinfo

Ryzen 7600, 64gb RAM, 4060 ti 16 gb, 2Tb SSD for Automatic1111 e.t,c
Windows 11 Pro 24H2 (license)
Google chrome browser
Automatic1111 version: [v1.10.1] •  python: 3.10.6  •  torch: 2.1.2+cu121  •  xformers: N/A  •  gradio: 3.41.2
[sysinfo-2024-10-13-01-47.json](https://github.com/user-attachments/files/17352695/sysinfo-2024-10-13-01-47.json)

### Relevant console log

```Shell
Creating venv in directory E:\NeuroHub\A1111\venv using python "C:\Users\septe\AppData\Local\Programs\Python\Python310\python.exe"
Requirement already satisfied: pip in e:\neurohub\a1111\venv\lib\site-packages (22.2.1)
Collecting pip
  Downloading pip-24.2-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 3.4 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.2.1
    Uninstalling pip-22.2.1:
      Successfully uninstalled pip-22.2.1
Successfully installed pip-24.2
venv "E:\NeuroHub\A1111\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.10.1
Commit hash: 82a973c04367123ae98bd9abdf80d9eda9b910e2
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
Collecting torch==2.1.2
  Downloading https://download.pytorch.org/whl/cu121/torch-2.1.2%2Bcu121-cp310-cp310-win_amd64.whl (2473.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 GB 10.0 MB/s eta 0:00:00
Collecting torchvision==0.16.2
  Downloading https://download.pytorch.org/whl/cu121/torchvision-0.16.2%2Bcu121-cp310-cp310-win_amd64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 9.6 MB/s eta 0:00:00
Collecting filelock (from torch==2.1.2)
  Downloading filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
Collecting typing-extensions (from torch==2.1.2)
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting sympy (from torch==2.1.2)
  Downloading sympy-1.13.3-py3-none-any.whl.metadata (12 kB)
Collecting networkx (from torch==2.1.2)
  Downloading networkx-3.4.1-py3-none-any.whl.metadata (6.3 kB)
Collecting jinja2 (from torch==2.1.2)
  Downloading jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Collecting fsspec (from torch==2.1.2)
  Downloading fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
Collecting numpy (from torchvision==0.16.2)
  Downloading numpy-2.1.2-cp310-cp310-win_amd64.whl.metadata (59 kB)
Collecting requests (from torchvision==0.16.2)
  Downloading requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting pillow!=8.3.*,>=5.3.0 (from torchvision==0.16.2)
  Downloading pillow-10.4.0-cp310-cp310-win_amd64.whl.metadata (9.3 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch==2.1.2)
  Downloading MarkupSafe-3.0.1-cp310-cp310-win_amd64.whl.metadata (4.1 kB)
Collecting charset-normalizer<4,>=2 (from requests->torchvision==0.16.2)
  Downloading charset_normalizer-3.4.0-cp310-cp310-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests->torchvision==0.16.2)
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests->torchvision==0.16.2)
  Downloading urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests->torchvision==0.16.2)
  Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy->torch==2.1.2)
  Downloading https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 8.8 MB/s eta 0:00:00
Downloading pillow-10.4.0-cp310-cp310-win_amd64.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 7.3 MB/s eta 0:00:00
Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
Downloading fsspec-2024.9.0-py3-none-any.whl (179 kB)
Downloading jinja2-3.1.4-py3-none-any.whl (133 kB)
Downloading networkx-3.4.1-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 4.5 MB/s eta 0:00:00
Downloading numpy-2.1.2-cp310-cp310-win_amd64.whl (12.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 10.8 MB/s eta 0:00:00
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
Downloading sympy-1.13.3-py3-none-any.whl (6.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 11.1 MB/s eta 0:00:00
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Downloading certifi-2024.8.30-py3-none-any.whl (167 kB)
Downloading charset_normalizer-3.4.0-cp310-cp310-win_amd64.whl (102 kB)
Downloading idna-3.10-py3-none-any.whl (70 kB)
Downloading MarkupSafe-3.0.1-cp310-cp310-win_amd64.whl (15 kB)
Downloading urllib3-2.2.3-py3-none-any.whl (126 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, fsspec, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision
Successfully installed MarkupSafe-3.0.1 certifi-2024.8.30 charset-normalizer-3.4.0 filelock-3.16.1 fsspec-2024.9.0 idna-3.10 jinja2-3.1.4 mpmath-1.3.0 networkx-3.4.1 numpy-2.1.2 pillow-10.4.0 requests-2.32.3 sympy-1.13.3 torch-2.1.2+cu121 torchvision-0.16.2+cu121 typing-extensions-4.12.2 urllib3-2.2.3
Installing clip
Installing open_clip
Cloning assets into E:\NeuroHub\A1111\repositories\stable-diffusion-webui-assets...
Cloning into 'E:\NeuroHub\A1111\repositories\stable-diffusion-webui-assets'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 20 (delta 0), reused 20 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (20/20), 132.70 KiB | 499.00 KiB/s, done.
Cloning Stable Diffusion into E:\NeuroHub\A1111\repositories\stable-diffusion-stability-ai...
Cloning into 'E:\NeuroHub\A1111\repositories\stable-diffusion-stability-ai'...
remote: Enumerating objects: 580, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 580 (delta 0), reused 0 (delta 0), pack-reused 577 (from 1)
Receiving objects: 100% (580/580), 73.44 MiB | 10.06 MiB/s, done.
Resolving deltas: 100% (283/283), done.
Cloning Stable Diffusion XL into E:\NeuroHub\A1111\repositories\generative-models...
Cloning into 'E:\NeuroHub\A1111\repositories\generative-models'...
remote: Enumerating objects: 1064, done.
remote: Counting objects: 100% (123/123), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 1064 (delta 55), reused 94 (delta 47), pack-reused 941 (from 1)
Receiving objects: 100% (1064/1064), 53.61 MiB | 5.94 MiB/s, done.
Resolving deltas: 100% (545/545), done.
Cloning K-diffusion into E:\NeuroHub\A1111\repositories\k-diffusion...
Cloning into 'E:\NeuroHub\A1111\repositories\k-diffusion'...
remote: Enumerating objects: 1345, done.
remote: Counting objects: 100% (646/646), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 1345 (delta 604), reused 561 (delta 560), pack-reused 699 (from 1)
Receiving objects: 100% (1345/1345), 239.07 KiB | 874.00 KiB/s, done.
Resolving deltas: 100% (944/944), done.
Cloning BLIP into E:\NeuroHub\A1111\repositories\BLIP...
Cloning into 'E:\NeuroHub\A1111\repositories\BLIP'...
remote: Enumerating objects: 277, done.
remote: Counting objects: 100% (183/183), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 277 (delta 145), reused 137 (delta 137), pack-reused 94 (from 1)
Receiving objects: 100% (277/277), 7.04 MiB | 6.74 MiB/s, done.
Resolving deltas: 100% (152/152), done.
Installing requirements
Launching Web UI with arguments:
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Downloading: "https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors" to E:\NeuroHub\A1111\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors

loading stable diffusion model: FileNotFoundError
Traceback (most recent call last):
  File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "E:\NeuroHub\A1111\modules\initialize.py", line 149, in load_model
    shared.sd_model  # noqa: B018
  File "E:\NeuroHub\A1111\modules\shared_items.py", line 175, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "E:\NeuroHub\A1111\modules\sd_models.py", line 693, in get_sd_model
    load_model()
  File "E:\NeuroHub\A1111\modules\sd_models.py", line 788, in load_model
    checkpoint_info = checkpoint_info or select_checkpoint()
  File "E:\NeuroHub\A1111\modules\sd_models.py", line 234, in select_checkpoint
    raise FileNotFoundError(error_message)
FileNotFoundError: No checkpoints found. When searching for checkpoints, looked at:
 - file E:\NeuroHub\A1111\model.ckpt
 - directory E:\NeuroHub\A1111\models\Stable-diffusionCan't run without a checkpoint. Find and place a .ckpt or .safetensors file into any of those locations.


Stable diffusion model failed to load
Applying attention optimization: Doggettx... done.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 517.5s (prepare environment: 480.2s, import torch: 9.6s, import gradio: 22.0s, setup paths: 0.9s, initialize shared: 0.4s, other imports: 1.5s, list SD models: 1.6s, load scripts: 0.7s, create ui: 0.3s, gradio launch: 0.3s).
loading stable diffusion model: FileNotFoundError
Traceback (most recent call last):
  File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "E:\NeuroHub\A1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\NeuroHub\A1111\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "E:\NeuroHub\A1111\modules\ui.py", line 1165, in <lambda>
    update_image_cfg_scale_visibility = lambda: gr.update(visible=shared.sd_model and shared.sd_model.cond_stage_key == "edit")
  File "E:\NeuroHub\A1111\modules\shared_items.py", line 175, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "E:\NeuroHub\A1111\modules\sd_models.py", line 693, in get_sd_model
    load_model()
  File "E:\NeuroHub\A1111\modules\sd_models.py", line 788, in load_model
    checkpoint_info = checkpoint_info or select_checkpoint()
  File "E:\NeuroHub\A1111\modules\sd_models.py", line 234, in select_checkpoint
    raise FileNotFoundError(error_message)
FileNotFoundError: No checkpoints found. When searching for checkpoints, looked at:
 - file E:\NeuroHub\A1111\model.ckpt
 - directory E:\NeuroHub\A1111\models\Stable-diffusionCan't run without a checkpoint. Find and place a .ckpt or .safetensors file into any of those locations.


Stable diffusion model failed to load
Downloading: "https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors" to E:\NeuroHub\A1111\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors

Downloading: "https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors" to E:\NeuroHub\A1111\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors

*** Error running install.py for extension E:\NeuroHub\A1111\extensions\sd-webui-reactor.
*** Command: "E:\NeuroHub\A1111\venv\Scripts\python.exe" "E:\NeuroHub\A1111\extensions\sd-webui-reactor\install.py"
*** Error code: 1
*** stderr: E:\NeuroHub\A1111\extensions\sd-webui-reactor\install.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
***   import pkg_resources
*** Traceback (most recent call last):
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1348, in do_open
***     h.request(req.get_method(), req.selector, req.data, headers,
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1282, in request
***     self._send_request(method, url, body, headers, encode_chunked)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1328, in _send_request
***     self.endheaders(body, encode_chunked=encode_chunked)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1277, in endheaders
***     self._send_output(message_body, encode_chunked=encode_chunked)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1037, in _send_output
***     self.send(msg)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 975, in send
***     self.connect()
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1454, in connect
***     self.sock = self._context.wrap_socket(self.sock,
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 513, in wrap_socket
***     return self.sslsocket_class._create(
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1071, in _create
***     self.do_handshake()
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1342, in do_handshake
***     self._sslobj.do_handshake()
*** ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
***
*** During handling of the above exception, another exception occurred:
***
*** Traceback (most recent call last):
***   File "E:\NeuroHub\A1111\extensions\sd-webui-reactor\install.py", line 62, in <module>
***     download(model_url, model_path)
***   File "E:\NeuroHub\A1111\extensions\sd-webui-reactor\install.py", line 53, in download
***     request = urllib.request.urlopen(url)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
***     return opener.open(url, data, timeout)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
***     response = meth(req, response)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
***     response = self.parent.error(
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 557, in error
***     result = self._call_chain(*args)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
***     result = func(*args)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 749, in http_error_302
***     return self.parent.open(new, timeout=req.timeout)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open
***     response = self._open(req, data)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 536, in _open
***     result = self._call_chain(self.handle_open, protocol, protocol +
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
***     result = func(*args)
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1391, in https_open
***     return self.do_open(http.client.HTTPSConnection, req,
***   File "C:\Users\septe\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1351, in do_open
***     raise URLError(err)
*** urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
```

**Comment by g2goswami** [comment]
I am getting the same or similar error trying to install on SD WebUI Forge
Web UI Forge - CU 12.1 - Torch 23.1

*** Error running install.py for extension D:\AI\WebUI\webui\extensions\sd-webui-reactor.
*** Command: "D:\AI\WebUI\system\python\python.exe" "D:\AI\WebUI\webui\extensions\sd-webui-reactor\install.py"
*** Error code: 1
*** stderr: D:\AI\WebUI\webui\extensions\sd-webui-reactor\install.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
***   import pkg_resources
*** Traceback (most recent call last):
***   File "urllib\request.py", line 1348, in do_open
***   File "http\client.py", line 1282, in request
***   File "http\client.py", line 1328, in _send_request
***   File "http\client.py", line 1277, in endheaders
***   File "http\client.py", line 1037, in _send_output
***   File "http\client.py", line 975, in send
***   File "http\client.py", line 1454, in connect
***   File "ssl.py", line 513, in wrap_socket
***   File "ssl.py", line 1071, in _create
***   File "ssl.py", line 1342, in do_handshake
*** ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
***
*** During handling of the above exception, another exception occurred:
***
*** Traceback (most recent call last):
***   File "D:\AI\WebUI\webui\extensions\sd-webui-reactor\install.py", line 62, in <module>
***     download(model_url, model_path)
***   File "D:\AI\WebUI\webui\extensions\sd-webui-reactor\install.py", line 53, in download
***     request = urllib.request.urlopen(url)
***   File "urllib\request.py", line 216, in urlopen
***   File "urllib\request.py", line 525, in open
***   File "urllib\request.py", line 634, in http_response
***   File "urllib\request.py", line 557, in error
***   File "urllib\request.py", line 496, in _call_chain
***   File "urllib\request.py", line 749, in http_error_302
***   File "urllib\request.py", line 519, in open
***   File "urllib\request.py", line 536, in _open
***   File "urllib\request.py", line 496, in _call_chain
***   File "urllib\request.py", line 1391, in https_open
***   File "urllib\request.py", line 1351, in do_open
*** urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

---- Important Note - I have Reactor running perfectly on Automatic 1111 on the same machine.

**Comment by jai10maran** [comment]
.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)> Same error .....Any solutions ? @g2goswami @Gourieff

**Comment by spekcool** [comment]
I use a translator so don't judge me too harshly.
I use Stability Matrix, through which I run Stable Diffusion and want to install the Reactor extension for it.

I just want to share with the community how it worked for me on Windows 11.
next CMD prompts:

pip install wheel
pip install --upgrade pip setuptools wheel
activate
python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl
...
Successfully uninstalled insightface-0.2.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
open-clip-torch 2.20.0 requires protobuf<4, but you have protobuf 5.29.0 which is incompatible.
...

pip uninstall protobuf
pip install protobuf==3.20.3

python.exe -m pip install insightface-0.7.3-cp310-cp310-in_amd64.whl
pip install --upgrade pip setuptools
deactivate

After that, the Reactor started and works correctly.

**Comment by waldenjoy** [comment]
Same issue in SD-NEXT with Windows10

I was able to resolve it by -

1 - Manually installing required packages ( pip install -r requirements )

2 - Download and copy inswapper_128.onnx into sd-next\extensions\sd-webui-reactor\models\insightface

3 - Download and copy v1-5-pruned-emaonly.safetensors into sd-next\models\Stable-diffusion


I did notice a lot of the recommended fixes had 

**import request
import urllib**

Instead of 

**import urllib.request**

No idea if that helps or not. The above method worked so i stopped there.
