### ISSUE TITLE
Multiple scripts missing

### ISSUE THREAD

**Issue by thejzain** [Gourieff/sd-webui-reactor#562]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Installed forge ui and reactor, Restarted the ui the reactor not appearing in ui the log shows No module named 'scripts.reactor_helpers', 'scripts.reactor_logger', 'scripts.reactor_globals', 'scripts.reactor_swapper'

### Steps to reproduce the problem

1. Install sd-webui-reactor in forge ui
2. Restart

### Sysinfo

[sysinfo-2024-11-15-04-58.json](https://github.com/user-attachments/files/17769843/sysinfo-2024-11-15-04-58.json)

### Relevant console log

```Shell
################################################################
Launching launch.py...
################################################################
=============================================================================================
INCOMPATIBLE PYTHON VERSION

This program is tested with 3.10.6 Python, but you have 3.12.7.
If you encounter an error with "RuntimeError: Couldn't install torch." message,
or any other error regarding unsuccessful package (library) installation,
please downgrade (or upgrade) to the latest version of 3.10 Python
and delete current Python and "venv" folder in WebUI's directory.

You can download 3.10 Python from here: https://www.python.org/downloads/release/python-3106/



Use --skip-python-version-check to suppress this warning.
=============================================================================================
Python 3.12.7 (main, Oct  1 2024, 11:15:50) [GCC 14.2.1 20240910]
Version: f2.0.1v1.10.1-previous-617-g19a9a78c
Commit hash: 19a9a78c9bb54d13a8f291f43939331af3242e8a
CUDA 12.1
Launching Web UI with arguments: --always-offload-from-vram --cuda-malloc
Using cudaMallocAsync backend.
Total VRAM 3795 MB, total RAM 7339 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Always offload VRAM
Device: cuda:0 NVIDIA GeForce RTX 3050 Laptop GPU : cudaMallocAsync
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: /home/zain/sd/stable-diffusion-webui-forge/models/ControlNetPreprocessor
*** Error loading script: console_log_patch.py
    Traceback (most recent call last):
      File "/home/zain/sd/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/zain/sd/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 995, in exec_module
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "/home/zain/sd/stable-diffusion-webui-forge/extensions/sd-webui-reactor/scripts/console_log_patch.py", line 17, in <module>
        from scripts.reactor_logger import logger
    ModuleNotFoundError: No module named 'scripts.reactor_logger'

---
*** Error loading script: reactor_api.py
    Traceback (most recent call last):
      File "/home/zain/sd/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/zain/sd/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 995, in exec_module
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "/home/zain/sd/stable-diffusion-webui-forge/extensions/sd-webui-reactor/scripts/reactor_api.py", line 28, in <module>
        from scripts.reactor_swapper import EnhancementOptions, blend_faces, swap_face, DetectionOptions
    ModuleNotFoundError: No module named 'scripts.reactor_swapper'

---
*** Error loading script: reactor_faceswap.py
    Traceback (most recent call last):
      File "/home/zain/sd/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/zain/sd/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 995, in exec_module
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "/home/zain/sd/stable-diffusion-webui-forge/extensions/sd-webui-reactor/scripts/reactor_faceswap.py", line 18, in <module>
        from reactor_ui import (
      File "/home/zain/sd/stable-diffusion-webui-forge/extensions/sd-webui-reactor/reactor_ui/__init__.py", line 2, in <module>
        import reactor_ui.reactor_tools_ui as ui_tools
      File "/home/zain/sd/stable-diffusion-webui-forge/extensions/sd-webui-reactor/reactor_ui/reactor_tools_ui.py", line 2, in <module>
        from scripts.reactor_swapper import build_face_model, blend_faces
    ModuleNotFoundError: No module named 'scripts.reactor_swapper'

---
*** Error loading script: reactor_helpers.py
    Traceback (most recent call last):
      File "/home/zain/sd/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/zain/sd/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 995, in exec_module
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "/home/zain/sd/stable-diffusion-webui-forge/extensions/sd-webui-reactor/scripts/reactor_helpers.py", line 14, in <module>
        from scripts.reactor_globals import DEVICE, BASE_PATH, FACE_MODELS_PATH, IS_SDNEXT
    ModuleNotFoundError: No module named 'scripts.reactor_globals'

---
*** Error loading script: reactor_logger.py
    Traceback (most recent call last):
      File "/home/zain/sd/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/zain/sd/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 995, in exec_module
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "/home/zain/sd/stable-diffusion-webui-forge/extensions/sd-webui-reactor/scripts/reactor_logger.py", line 6, in <module>
        from scripts.reactor_globals import IS_RUN
    ModuleNotFoundError: No module named 'scripts.reactor_globals'

---
*** Error loading script: reactor_swapper.py
    Traceback (most recent call last):
      File "/home/zain/sd/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/zain/sd/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 995, in exec_module
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "/home/zain/sd/stable-diffusion-webui-forge/extensions/sd-webui-reactor/scripts/reactor_swapper.py", line 14, in <module>
        from scripts.reactor_globals import FACE_MODELS_PATH
    ModuleNotFoundError: No module named 'scripts.reactor_globals'

---
*** Error loading script: reactor_version.py
    Traceback (most recent call last):
      File "/home/zain/sd/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/zain/sd/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 995, in exec_module
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "/home/zain/sd/stable-diffusion-webui-forge/extensions/sd-webui-reactor/scripts/reactor_version.py", line 4, in <module>
        from scripts.reactor_logger import logger, get_Run, set_Run
    ModuleNotFoundError: No module named 'scripts.reactor_logger'

---
*** Error loading script: reactor_xyz.py
    Traceback (most recent call last):
      File "/home/zain/sd/stable-diffusion-webui-forge/modules/scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/zain/sd/stable-diffusion-webui-forge/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 995, in exec_module
      File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
      File "/home/zain/sd/stable-diffusion-webui-forge/extensions/sd-webui-reactor/scripts/reactor_xyz.py", line 8, in <module>
        from scripts.reactor_helpers import (
    ModuleNotFoundError: No module named 'scripts.reactor_helpers'

---
Loading additional modules ... done.
2024-11-15 10:26:36,067 - ControlNet - INFO - ControlNet UI callback registered.
You do not have any model!
Model selected: {'checkpoint_info': None, 'additional_modules': [], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 23.1s (prepare environment: 2.9s, launcher: 0.3s, import torch: 5.1s, other imports: 0.2s, load scripts: 1.3s, initialize google blockly: 10.7s, create ui: 1.6s, gradio launch: 0.8s).
Environment vars changed: {'stream': False, 'inference_memory': 1024.0, 'pin_shared_memory': False}
[GPU Setting] You will use 73.01% GPU memory (2770.00 MB) to load weights, and use 26.99% GPU memory (1024.00 MB) to do matrix computation.
```

**Comment by gulp79** [comment]
same here, i've Python 3.10.6, this is my log:

`Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-previous-621-gf4a6a08e
Commit hash: f4a6a08ec2ae80305c45a3fb181e8b006828de09
Installing requirements
CUDA 12.1
Launching Web UI with arguments:
Total VRAM 8188 MB, total RAM 16104 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Laptop GPU : native
Hint: your device supports --cuda-malloc for potential speed improvements.
VAE dtype preferences: [torch.bfloat16, torch.float32] -> torch.bfloat16
CUDA Using Stream: False
D:\AI_\StableDiffusion_webui_forge\system\python\lib\site-packages\transformers\utils\hub.py:128: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Using pytorch cross attention
Using pytorch attention for VAE
ControlNet preprocessor location: D:\AI_\StableDiffusion_webui_forge\webui\models\ControlNetPreprocessor
CHv1.8.11: Get Custom Model Folder
[-] ADetailer initialized. version: 24.11.1, num models: 12
*** Error loading script: console_log_patch.py
    Traceback (most recent call last):
      File "D:\AI_\StableDiffusion_webui_forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI_\StableDiffusion_webui_forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI_\StableDiffusion_webui_forge\webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 17, in <module>
        from scripts.reactor_logger import logger
    ModuleNotFoundError: No module named 'scripts.reactor_logger'

---
*** Error loading script: reactor_api.py
    Traceback (most recent call last):
      File "D:\AI_\StableDiffusion_webui_forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI_\StableDiffusion_webui_forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI_\StableDiffusion_webui_forge\webui\extensions\sd-webui-reactor\scripts\reactor_api.py", line 28, in <module>
        from scripts.reactor_swapper import EnhancementOptions, blend_faces, swap_face, DetectionOptions
    ModuleNotFoundError: No module named 'scripts.reactor_swapper'

---
*** Error loading script: reactor_faceswap.py
    Traceback (most recent call last):
      File "D:\AI_\StableDiffusion_webui_forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI_\StableDiffusion_webui_forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI_\StableDiffusion_webui_forge\webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 18, in <module>
        from reactor_ui import (
      File "D:\AI_\StableDiffusion_webui_forge\webui\extensions\sd-webui-reactor\reactor_ui\__init__.py", line 2, in <module>
        import reactor_ui.reactor_tools_ui as ui_tools
      File "D:\AI_\StableDiffusion_webui_forge\webui\extensions\sd-webui-reactor\reactor_ui\reactor_tools_ui.py", line 2, in <module>
        from scripts.reactor_swapper import build_face_model, blend_faces
    ModuleNotFoundError: No module named 'scripts.reactor_swapper'

---
*** Error loading script: reactor_helpers.py
    Traceback (most recent call last):
      File "D:\AI_\StableDiffusion_webui_forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI_\StableDiffusion_webui_forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI_\StableDiffusion_webui_forge\webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 14, in <module>
        from scripts.reactor_globals import DEVICE, BASE_PATH, FACE_MODELS_PATH, IS_SDNEXT
    ModuleNotFoundError: No module named 'scripts.reactor_globals'

---
*** Error loading script: reactor_logger.py
    Traceback (most recent call last):
      File "D:\AI_\StableDiffusion_webui_forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI_\StableDiffusion_webui_forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI_\StableDiffusion_webui_forge\webui\extensions\sd-webui-reactor\scripts\reactor_logger.py", line 6, in <module>
        from scripts.reactor_globals import IS_RUN
    ModuleNotFoundError: No module named 'scripts.reactor_globals'

---
*** Error loading script: reactor_swapper.py
    Traceback (most recent call last):
      File "D:\AI_\StableDiffusion_webui_forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI_\StableDiffusion_webui_forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI_\StableDiffusion_webui_forge\webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 14, in <module>
        from scripts.reactor_globals import FACE_MODELS_PATH
    ModuleNotFoundError: No module named 'scripts.reactor_globals'

---
*** Error loading script: reactor_version.py
    Traceback (most recent call last):
      File "D:\AI_\StableDiffusion_webui_forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI_\StableDiffusion_webui_forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI_\StableDiffusion_webui_forge\webui\extensions\sd-webui-reactor\scripts\reactor_version.py", line 4, in <module>
        from scripts.reactor_logger import logger, get_Run, set_Run
    ModuleNotFoundError: No module named 'scripts.reactor_logger'

---
*** Error loading script: reactor_xyz.py
    Traceback (most recent call last):
      File "D:\AI_\StableDiffusion_webui_forge\webui\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\AI_\StableDiffusion_webui_forge\webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\AI_\StableDiffusion_webui_forge\webui\extensions\sd-webui-reactor\scripts\reactor_xyz.py", line 8, in <module>
        from scripts.reactor_helpers import (
    ModuleNotFoundError: No module named 'scripts.reactor_helpers'

---
Loading additional modules ... done.
CHv1.8.11: Set Proxy:
2024-11-20 12:48:13,640 - ControlNet - INFO - ControlNet UI callback registered.
Model selected: {'checkpoint_info': {'filename': 'D:\\AI_\\StableDiffusion_webui_forge\\webui\\models\\Stable-diffusion\\Flux\\flux1-schnell-Q4_K_S.gguf', 'hash': 'e3672abd'}, 'additional_modules': ['D:\\AI_\\StableDiffusion_webui_forge\\webui\\models\\VAE\\ae.safetensors', 'D:\\AI_\\StableDiffusion_webui_forge\\webui\\models\\text_encoder\\clip_l.safetensors', 'D:\\AI_\\StableDiffusion_webui_forge\\webui\\models\\text_encoder\\t5-v1_1-xxl-encoder-Q6_K.gguf'], 'unet_storage_dtype': None}
Using online LoRAs in FP16: True
Running on local URL:  http://127.0.0.1:7860`

**Comment by Gourieff** [comment]
Check this solution guys https://github.com/Gourieff/sd-webui-reactor/issues/396

**Comment by gulp79** [comment]
I don't have Dreamboot, btw i've disabled all custom extensions and same error.
Then i've disabled all extensions, also the Forge internal ones.
Always the same error.... really strange.
