### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by goodluck821** [Gourieff/sd-webui-reactor#571]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Error running postprocess_image: J:\sd-webui-aki-v4.9\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "J:\sd-webui-aki-v4.9\modules\scripts.py", line 912, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "J:\sd-webui-aki-v4.9\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 465, in postprocess_image
        result, output, swapped = swap_face(
      File "J:\sd-webui-aki-v4.9\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 616, in swap_face
        result_image, output, swapped = operate(source_img,target_img,target_img_orig,model,source_faces_index,faces_index,source_faces,target_faces,gender_source,gender_target,source_face,wrong_gender,source_age,source_gender,output,swapped,mask_face,entire_mask_image,enhancement_options,detection_options)
      File "J:\sd-webui-aki-v4.9\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 779, in operate
        swapped_image = face_swapper.get(result, target_face, source_face)
    AttributeError: 'NoneType' object has no attribute 'get'

### Steps to reproduce the problem

Error running postprocess_image: J:\sd-webui-aki-v4.9\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "J:\sd-webui-aki-v4.9\modules\scripts.py", line 912, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "J:\sd-webui-aki-v4.9\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 465, in postprocess_image
        result, output, swapped = swap_face(
      File "J:\sd-webui-aki-v4.9\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 616, in swap_face
        result_image, output, swapped = operate(source_img,target_img,target_img_orig,model,source_faces_index,faces_index,source_faces,target_faces,gender_source,gender_target,source_face,wrong_gender,source_age,source_gender,output,swapped,mask_face,entire_mask_image,enhancement_options,detection_options)
      File "J:\sd-webui-aki-v4.9\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 779, in operate
        swapped_image = face_swapper.get(result, target_face, source_face)
    AttributeError: 'NoneType' object has no attribute 'get'

### Sysinfo

Error running postprocess_image: J:\sd-webui-aki-v4.9\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "J:\sd-webui-aki-v4.9\modules\scripts.py", line 912, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "J:\sd-webui-aki-v4.9\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 465, in postprocess_image
        result, output, swapped = swap_face(
      File "J:\sd-webui-aki-v4.9\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 616, in swap_face
        result_image, output, swapped = operate(source_img,target_img,target_img_orig,model,source_faces_index,faces_index,source_faces,target_faces,gender_source,gender_target,source_face,wrong_gender,source_age,source_gender,output,swapped,mask_face,entire_mask_image,enhancement_options,detection_options)
      File "J:\sd-webui-aki-v4.9\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 779, in operate
        swapped_image = face_swapper.get(result, target_face, source_face)
    AttributeError: 'NoneType' object has no attribute 'get'

### Relevant console log

```Shell
Error running postprocess_image: J:\sd-webui-aki-v4.9\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "J:\sd-webui-aki-v4.9\modules\scripts.py", line 912, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "J:\sd-webui-aki-v4.9\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 465, in postprocess_image
        result, output, swapped = swap_face(
      File "J:\sd-webui-aki-v4.9\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 616, in swap_face
        result_image, output, swapped = operate(source_img,target_img,target_img_orig,model,source_faces_index,faces_index,source_faces,target_faces,gender_source,gender_target,source_face,wrong_gender,source_age,source_gender,output,swapped,mask_face,entire_mask_image,enhancement_options,detection_options)
      File "J:\sd-webui-aki-v4.9\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 779, in operate
        swapped_image = face_swapper.get(result, target_face, source_face)
    AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by Gourieff** [comment]
https://github.com/Gourieff/sd-webui-reactor#v-invalid_protobuf--load-model-from-modelsinsightfaceinswapper_128onnx-failedprotobuf-parsing-failed-or-attributeerror-nonetype-object-has-no-attribute-get-or-attributeerror-faceswapscript-object-has-no-attribute-save_original

https://github.com/Gourieff/sd-webui-reactor/issues?q=is%3Aissue+is%3Aclosed+AttributeError%3A+%27NoneType%27+object+has+no+attribute+%27get%27

**Comment by goodluck821** [comment]
It doesn't work.but It can work with sd-webui forge.

**Comment by goodluck821** [comment]
That's allright!
