### ISSUE TITLE
ONNX Runtime, CUDAExecutionProvider problems

### ISSUE THREAD

**Issue by rvpv** [Gourieff/sd-webui-reactor#63]
ReActor has stopped working, when I try to use it I get this error. 

`17:15:08 - ReActor - STATUS - Working: source face index [0], target face index [0]████| 16/16 [00:01<00:00, 13.17it/s]
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\sd.webui\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\sd.webui\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\sd.webui\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\sd.webui\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\sd.webui\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
*** Error running postprocess_image: D:\sd.webui\webui\extensions\sd-webui-roop-nsfw\scripts\faceswap.py
    Traceback (most recent call last):
      File "D:\sd.webui\webui\modules\scripts.py", line 575, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\sd.webui\webui\extensions\sd-webui-roop-nsfw\scripts\faceswap.py", line 273, in postprocess_image
        result = swap_face(
      File "D:\sd.webui\webui\extensions\sd-webui-roop-nsfw\scripts\swapper.py", line 248, in swap_face
        source_face, wrong_gender = get_face_single(source_img, face_index=source_faces_index[0], gender_source=gender_source)
      File "D:\sd.webui\webui\extensions\sd-webui-roop-nsfw\scripts\swapper.py", line 192, in get_face_single
        face_analyser = copy.deepcopy(getAnalysisModel())
      File "copy.py", line 172, in deepcopy
      File "copy.py", line 271, in _reconstruct
      File "copy.py", line 146, in deepcopy
      File "copy.py", line 231, in _deepcopy_dict
      File "copy.py", line 146, in deepcopy
      File "copy.py", line 231, in _deepcopy_dict
      File "copy.py", line 172, in deepcopy
      File "copy.py", line 271, in _reconstruct
      File "copy.py", line 146, in deepcopy
      File "copy.py", line 231, in _deepcopy_dict
      File "copy.py", line 172, in deepcopy
      File "copy.py", line 273, in _reconstruct
      File "D:\sd.webui\system\python\lib\site-packages\insightface\model_zoo\model_zoo.py", line 33, in __setstate__
        self.__init__(model_path)
      File "D:\sd.webui\system\python\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "D:\sd.webui\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 396, in __init__
        raise e
      File "D:\sd.webui\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "D:\sd.webui\system\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 415, in _create_inference_session
        raise ValueError(
    ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)`

**Comment by Gourieff** [comment]
Please read Troubleshooting Sec.VI https://github.com/Gourieff/sd-webui-reactor#troubleshooting

**Comment by rvpv** [comment]
```

- Go to the (Windows)venv\Lib\site-packages or (MacOS/Linux)venv/lib/python3.10/site-packages and see if there are any folders with names start from "~" (for example "~rotobuf"), delete them
- Go to the (Windows)venv\Scripts or (MacOS/Linux)venv/bin run Terminal or Console (cmd) there and type activate

```
In the automatic1111 (Windows) directory, there is no 'venv' folder. The directory only contains the 'scripts' folder, but there is no activate file to initiate it through CMD.

**Comment by Gourieff** [comment]
There MUST be "venv" folder if you use the original A1111 or SD.Next
If no - that is the reason that you get errors
You use some portable version, not the original one (of A1111 or SD.Next)
This extension is guaranteed to work only with original versions of A1111, SD.Next or Cagliostro Colab UI.
It's not tested with 3rd-party builds 
So, please use supported SD WebUI apps

The reason you see the error `ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled` - is that you use the wrong version of "onnxruntime" package, you have "onnxruntime-gpu" installed instead of "onnxruntime"
To make this extension work - you have to uninstall "onnxruntime-gpu" and install "onnxruntime==1.15.0" inside your "sd.webui\system\python"
