### ISSUE TITLE
AttributeError: 'FaceSwapScript' object has no attribute 'enable'

### ISSUE THREAD

**Issue by hoolswelsh** [Gourieff/sd-webui-reactor#71]
``*** Error running postprocess_batch: C:\Users\Holly\Documents\StableDifusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\faceswap.py
    Traceback (most recent call last):
      File "C:\Users\Holly\Documents\StableDifusion\stable-diffusion-webui\modules\scripts.py", line 559, in postprocess_batch
        script.postprocess_batch(p, *script_args, images=images, **kwargs)
      File "C:\Users\Holly\Documents\StableDifusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\faceswap.py", line 263, in postprocess_batch
        if self.enable:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'

---
*** Error running postprocess_image: C:\Users\Holly\Documents\StableDifusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\faceswap.py
    Traceback (most recent call last):
      File "C:\Users\Holly\Documents\StableDifusion\stable-diffusion-webui\modules\scripts.py", line 575, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\Users\Holly\Documents\StableDifusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\faceswap.py", line 267, in postprocess_image
        if self.enable and self.swap_in_generated:
    AttributeError: 'FaceSwapScript' object has no attribute 'enable'``

Don't know how I got this error, freshly installed with all dependancies.

**Comment by Gourieff** [comment]
Please read "Sec. IV" of [troubleshooting](https://github.com/Gourieff/sd-webui-reactor#troubleshooting)
