### ISSUE TITLE
Error The insightface 0.7.3 distribution was not found and is required

### ISSUE THREAD

**Issue by qawasx** [Gourieff/sd-webui-reactor#72]
Did i do something wrong?

`Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.5.2
Commit hash: c9c8485bc1e8720aba70f029d25cba1c4abf2b5c
Collecting insightface==0.7.3
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
Checking ReActor requirements... Error: The 'insightface==0.7.3' distribution was not found and is required by the application

--- PLEASE, RESTART the Server! ---

Launching Web UI with arguments:
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
*** Error loading script: console_log_patch.py
    Traceback (most recent call last):
      File "E:\Downloads\sd.webui\webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Downloads\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Downloads\sd.webui\webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 4, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: faceswap.py
    Traceback (most recent call last):
      File "E:\Downloads\sd.webui\webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Downloads\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Downloads\sd.webui\webui\extensions\sd-webui-reactor\scripts\faceswap.py", line 16, in <module>
        from scripts.swapper import UpscaleOptions, swap_face, check_process_halt, reset_messaged
      File "E:\Downloads\sd.webui\webui\extensions\sd-webui-reactor\scripts\swapper.py", line 10, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_api.py
    Traceback (most recent call last):
      File "E:\Downloads\sd.webui\webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Downloads\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Downloads\sd.webui\webui\extensions\sd-webui-reactor\scripts\reactor_api.py", line 17, in <module>
        from scripts.swapper import UpscaleOptions, swap_face
      File "E:\Downloads\sd.webui\webui\extensions\sd-webui-reactor\scripts\swapper.py", line 10, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: swapper.py
    Traceback (most recent call last):
      File "E:\Downloads\sd.webui\webui\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Downloads\sd.webui\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Downloads\sd.webui\webui\extensions\sd-webui-reactor\scripts\swapper.py", line 10, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'
`

**Comment by Gourieff** [comment]
Did you try "--- PLEASE, RESTART the Server! ---" ? I hope you did :)
Do you have the "insightface" folder inside the "E:\Downloads\sd.webui\webui\venv\Lib\site-packages" directory?
If no - please read "Step 1" of [installation](https://github.com/Gourieff/sd-webui-reactor#installation) or "Sec. VIII" of [troubleshooting](https://github.com/Gourieff/sd-webui-reactor#troubleshooting)

The most common issue about that - is you need to have C++ Build Tools in your OS, otherwise Insightface dependency won't be installed

**Comment by qawasx** [comment]
I did restart it of course.
The folder venv does not exist.

**Comment by Gourieff** [comment]
What sd-webui do you use? Some portable version?

**Comment by qawasx** [comment]
this one https://github.com/AUTOMATIC1111/stable-diffusion-webui/#installation-on-windows-1011-with-nvidia-gpus-using-release-package

**Comment by Gourieff** [comment]
Do you have "Visual Studio 2022" or "VS C++ Build Tools" installed?

**Comment by qawasx** [comment]
no, only git and python

**Comment by Gourieff** [comment]
This is the reason, Insightface cannot be built without C++ Build Tools
But ok, you can download pre-built Insightface package https://github.com/Gourieff/sd-webui-reactor/raw/main/example/insightface-0.7.3-cp310-cp310-win_amd64.whl
Then:
1. Put the file in the `E:\Downloads\sd.webui\system` folder
3. Run CMD for that folder (just type `cmd` instead of your folder path)
4. Close sd-webui server if it's running
5. Run `python\python.exe -m pip install insightface-0.7.3-cp310-cp310-win_amd64.whl` and wait for the process to complete
6. That's all, ReActor should work after that

**Comment by bytechomp** [comment]
I'm facing same issue - running sd-webui-reactor on macOS arm64. Previous versions of reactor worked without issues.

**Comment by Creepybits** [comment]
I got it to work eventually. I had to check VS again and make sure to download:

Desktop development with C++

And then select the following individual components:

Windows 11 SDK
C++ x64/x86 build tools

After that I CMD in \venv\Lib\site-packages

And did the following:

pip uninstall insightface

git clone https://github.com/deepinsight/insightface.git

cd insightface

pip install -r requirements.txt

cd python-package

pip install -e .

After a couple of restarts it seems to work.

**Comment by 00RohitRoshan** [comment]
It seems to work when installed from the `~Stable Diffusion\stable-diffusion-webui\venv\Scripts` folder.
run `pip install insightface-0.7.3-cp310-cp310-win_amd64.whl` .
and keep the `.whl` file in the same folder.

**Comment by EGCReborn** [comment]
It seems to work when installed from the ~Stable Diffusion\stable-diffusion-webui\venv\Scripts folder.
run pip install insightface-0.7.3-cp310-cp310-win_amd64.whl .
and keep the .whl file in the same folder.

**Comment by xenjee** [comment]
error 404 with [https://github.com/Gourieff/sd-webui-reactor/raw/main/example/insightface-0.7.3-cp310-cp310-win_amd64.whl]

**Comment by Gourieff** [comment]
@xenjee you can find it here https://github.com/Gourieff/Assets/blob/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl

**Comment by xenjee** [comment]
@Gourieff thank you, appreciated.

**Comment by Ammaramd22** [comment]
venv "E:\Stable Diffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.10.1
Commit hash: 82a973c04367123ae98bd9abdf80d9eda9b910e2
Collecting insightface==0.7.3
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (1.26.2)
Requirement already satisfied: onnx in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (1.16.2)
Requirement already satisfied: tqdm in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (4.66.5)
Requirement already satisfied: requests in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (2.32.3)
Requirement already satisfied: matplotlib in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (3.9.2)
Requirement already satisfied: Pillow in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (9.5.0)
Requirement already satisfied: scipy in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (1.14.1)
Requirement already satisfied: scikit-learn in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (1.5.2)
Requirement already satisfied: scikit-image in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (0.21.0)
Collecting easydict (from insightface==0.7.3)
  Using cached easydict-1.13-py3-none-any.whl.metadata (4.2 kB)
Collecting cython (from insightface==0.7.3)
  Using cached Cython-3.0.11-cp310-cp310-win_amd64.whl.metadata (3.2 kB)
Requirement already satisfied: albumentations in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from insightface==0.7.3) (1.4.3)
Collecting prettytable (from insightface==0.7.3)
  Using cached prettytable-3.11.0-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: PyYAML in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from albumentations->insightface==0.7.3) (6.0.2)
Requirement already satisfied: typing-extensions>=4.9.0 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from albumentations->insightface==0.7.3) (4.12.2)
Requirement already satisfied: opencv-python-headless>=4.9.0 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from albumentations->insightface==0.7.3) (4.10.0.84)
Requirement already satisfied: networkx>=2.8 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (3.3)
Requirement already satisfied: imageio>=2.27 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (2.35.1)
Requirement already satisfied: tifffile>=2022.8.12 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (2024.8.30)
Requirement already satisfied: PyWavelets>=1.1.1 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (1.7.0)
Requirement already satisfied: packaging>=21 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (24.1)
Requirement already satisfied: lazy_loader>=0.2 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-image->insightface==0.7.3) (0.4)
Requirement already satisfied: joblib>=1.2.0 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-learn->insightface==0.7.3) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from scikit-learn->insightface==0.7.3) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (1.3.0)
Requirement already satisfied: cycler>=0.10 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (1.4.7)
Requirement already satisfied: pyparsing>=2.3.1 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from matplotlib->insightface==0.7.3) (2.9.0.post0)
Collecting protobuf>=3.20.2 (from onnx->insightface==0.7.3)
  Using cached protobuf-5.28.1-cp310-abi3-win_amd64.whl.metadata (592 bytes)
Requirement already satisfied: wcwidth in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from prettytable->insightface==0.7.3) (0.2.13)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from requests->insightface==0.7.3) (2024.8.30)
Requirement already satisfied: colorama in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from tqdm->insightface==0.7.3) (0.4.6)
Requirement already satisfied: six>=1.5 in e:\stable diffusion\stable-diffusion-webui\venv\lib\site-packages (from python-dateutil>=2.7->matplotlib->insightface==0.7.3) (1.16.0)
Using cached Cython-3.0.11-cp310-cp310-win_amd64.whl (2.8 MB)
Using cached easydict-1.13-py3-none-any.whl (6.8 kB)
Using cached prettytable-3.11.0-py3-none-any.whl (28 kB)
Using cached protobuf-5.28.1-cp310-abi3-win_amd64.whl (431 kB)
Building wheels for collected packages: insightface
  Building wheel for insightface (pyproject.toml): started
  Building wheel for insightface (pyproject.toml): finished with status 'error'
Failed to build insightface
CUDA 12.1
Error: The 'insightface==0.7.3' distribution was not found and is required by the application

        +---------------------------------+
        --- PLEASE, RESTART the Server! ---
        +---------------------------------+
Launching Web UI with arguments: --xformers
*** Error loading script: console_log_patch.py
    Traceback (most recent call last):
      File "E:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Stable Diffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 4, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_api.py
    Traceback (most recent call last):
      File "E:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Stable Diffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_api.py", line 28, in <module>
        from scripts.reactor_swapper import EnhancementOptions, swap_face, DetectionOptions
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 11, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_faceswap.py
    Traceback (most recent call last):
      File "E:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Stable Diffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 18, in <module>
        from reactor_ui import (
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\reactor_ui\__init__.py", line 2, in <module>
        import reactor_ui.reactor_tools_ui as ui_tools
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\reactor_ui\reactor_tools_ui.py", line 2, in <module>
        from scripts.reactor_swapper import build_face_model, blend_faces
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 11, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_helpers.py
    Traceback (most recent call last):
      File "E:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Stable Diffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in <module>
        from insightface.app.common import Face
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_logger.py
    Traceback (most recent call last):
      File "E:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Stable Diffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_logger.py", line 7, in <module>
        from scripts.reactor_helpers import addLoggingLevel
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in <module>
        from insightface.app.common import Face
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_swapper.py
    Traceback (most recent call last):
      File "E:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Stable Diffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 11, in <module>
        import insightface
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_version.py
    Traceback (most recent call last):
      File "E:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Stable Diffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_version.py", line 4, in <module>
        from scripts.reactor_logger import logger, get_Run, set_Run
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_logger.py", line 7, in <module>
        from scripts.reactor_helpers import addLoggingLevel
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in <module>
        from insightface.app.common import Face
    ModuleNotFoundError: No module named 'insightface'

---
*** Error loading script: reactor_xyz.py
    Traceback (most recent call last):
      File "E:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Stable Diffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_xyz.py", line 8, in <module>
        from scripts.reactor_helpers import (
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_helpers.py", line 10, in <module>
        from insightface.app.common import Face
    ModuleNotFoundError: No module named 'insightface'

---
Loading weights [6ce0161689] from E:\Stable Diffusion\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: E:\Stable Diffusion\stable-diffusion-webui\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 86.6s (prepare environment: 50.2s, import torch: 14.6s, import gradio: 5.4s, setup paths: 5.2s, initialize shared: 1.5s, other imports: 2.7s, setup gfpgan: 0.1s, list SD models: 0.3s, load scripts: 2.6s, initialize extra networks: 0.5s, scripts before_ui_callback: 0.2s, create ui: 3.0s, gradio launch: 1.0s).
E:\Stable Diffusion\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py:1142: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
