### ISSUE TITLE
run-time error

### ISSUE THREAD

**Issue by lniaen** [Gourieff/sd-webui-reactor#75]
04:52:06 - ReActor - STATUS - Working: source face index [0], target face index [0]
*** Error running postprocess_image: D:\StableDiffusion\sd-webui-aki-v4.3\extensions\sd-webui-reactor\scripts\faceswap.py
    Traceback (most recent call last):
      File "D:\StableDiffusion\sd-webui-aki-v4.3\modules\scripts.py", line 575, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\StableDiffusion\sd-webui-aki-v4.3\extensions\sd-webui-reactor\scripts\faceswap.py", line 279, in postprocess_image
        result = swap_face(
      File "D:\StableDiffusion\sd-webui-aki-v4.3\extensions\sd-webui-reactor\scripts\swapper.py", line 253, in swap_face
        source_face, wrong_gender = get_face_single(source_img, face_index=source_faces_index[0], gender_source=gender_source)
      File "D:\StableDiffusion\sd-webui-aki-v4.3\extensions\sd-webui-reactor\scripts\swapper.py", line 193, in get_face_single
        face_analyser = copy.deepcopy(getAnalysisModel())
      File "D:\StableDiffusion\sd-webui-aki-v4.3\extensions\sd-webui-reactor\scripts\swapper.py", line 89, in getAnalysisModel
        ANALYSIS_MODEL = insightface.app.FaceAnalysis(
      File "D:\StableDiffusion\sd-webui-aki-v4.3\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 48, in patched_faceanalysis_init
        model = model_zoo.get_model(onnx_file, **kwargs)
      File "D:\StableDiffusion\sd-webui-aki-v4.3\python\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
        model = router.get_model(providers=providers, provider_options=provider_options)
      File "D:\StableDiffusion\sd-webui-aki-v4.3\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 21, in patched_get_model
        session = PickableInferenceSession(self.onnx_file, **kwargs)
      File "D:\StableDiffusion\sd-webui-aki-v4.3\python\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "D:\StableDiffusion\sd-webui-aki-v4.3\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 360, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "D:\StableDiffusion\sd-webui-aki-v4.3\python\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 408, in _create_inference_session
        sess.initialize_session(providers, provider_options, disabled_optimizers)
    RuntimeError: D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1106 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\StableDiffusion\sd-webui-aki-v4.3\python\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by lniaen** [comment]
I have resolved the issue, if you have the same problem try the following code.

`pip uninstall rembg //uninstall rembg
pip uninstall onnxruntime //uninstall onnxruntime
pip install rembg[gpu] onnxruntime-gpu //install rembg with GPU support`
