### ISSUE TITLE
A lot of errors

### ISSUE THREAD

**Issue by lotnick** [Gourieff/sd-webui-reactor#76]
Any idea?
 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1827 onnxruntime::python::CreateInferencePybindStateModule] Init provider bridge failed.
Error loading script: console_log_patch.py
Traceback (most recent call last):
  File "C:\Users\lotni\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\lotni\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\lotni\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 4, in <module>
    import insightface
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\app\mask_renderer.py", line 4, in <module>
    import albumentations as A
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\__init__.py", line 5, in <module>
    from .augmentations import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\__init__.py", line 8, in <module>
    from .domain_adaptation import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\domain_adaptation.py", line 6, in <module>
    from qudida import DomainAdapter
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\qudida\__init__.py", line 6, in <module>
    from sklearn.decomposition import PCA
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\__init__.py", line 80, in <module>
    from . import _distributor_init  # noqa: F401
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\_distributor_init.py", line 21, in <module>
    WinDLL(op.abspath(vcomp140_dll_filename))
  File "C:\Users\lotni\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\.libs\vcomp140.dll' (or one of its dependencies). Try using the full path with constructor syntax.

Error loading script: faceswap.py
Traceback (most recent call last):
  File "C:\Users\lotni\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\lotni\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\lotni\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\faceswap.py", line 16, in <module>
    from scripts.swapper import UpscaleOptions, swap_face, check_process_halt, reset_messaged
  File "C:\Users\lotni\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\swapper.py", line 10, in <module>
    import insightface
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\app\mask_renderer.py", line 4, in <module>
    import albumentations as A
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\__init__.py", line 5, in <module>
    from .augmentations import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\__init__.py", line 8, in <module>
    from .domain_adaptation import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\domain_adaptation.py", line 6, in <module>
    from qudida import DomainAdapter
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\qudida\__init__.py", line 6, in <module>
    from sklearn.decomposition import PCA
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\__init__.py", line 80, in <module>
    from . import _distributor_init  # noqa: F401
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\_distributor_init.py", line 21, in <module>
    WinDLL(op.abspath(vcomp140_dll_filename))
  File "C:\Users\lotni\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\.libs\vcomp140.dll' (or one of its dependencies). Try using the full path with constructor syntax.

Error loading script: reactor_api.py
Traceback (most recent call last):
  File "C:\Users\lotni\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\lotni\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\lotni\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_api.py", line 17, in <module>
    from scripts.swapper import UpscaleOptions, swap_face
  File "C:\Users\lotni\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\swapper.py", line 10, in <module>
    import insightface
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\app\mask_renderer.py", line 4, in <module>
    import albumentations as A
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\__init__.py", line 5, in <module>
    from .augmentations import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\__init__.py", line 8, in <module>
    from .domain_adaptation import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\domain_adaptation.py", line 6, in <module>
    from qudida import DomainAdapter
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\qudida\__init__.py", line 6, in <module>
    from sklearn.decomposition import PCA
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\__init__.py", line 80, in <module>
    from . import _distributor_init  # noqa: F401
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\_distributor_init.py", line 21, in <module>
    WinDLL(op.abspath(vcomp140_dll_filename))
  File "C:\Users\lotni\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\.libs\vcomp140.dll' (or one of its dependencies). Try using the full path with constructor syntax.

Error loading script: swapper.py
Traceback (most recent call last):
  File "C:\Users\lotni\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\lotni\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\lotni\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\swapper.py", line 10, in <module>
    import insightface
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\app\mask_renderer.py", line 4, in <module>
    import albumentations as A
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\__init__.py", line 5, in <module>
    from .augmentations import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\__init__.py", line 8, in <module>
    from .domain_adaptation import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\domain_adaptation.py", line 6, in <module>
    from qudida import DomainAdapter
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\qudida\__init__.py", line 6, in <module>
    from sklearn.decomposition import PCA
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\__init__.py", line 80, in <module>
    from . import _distributor_init  # noqa: F401
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\_distributor_init.py", line 21, in <module>
    WinDLL(op.abspath(vcomp140_dll_filename))
  File "C:\Users\lotni\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\.libs\vcomp140.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by lotnick** [comment]
Yes, VS 2022.

**Comment by lotnick** [comment]
And vcomp140.dll is in the right folder

**Comment by Gourieff** [comment]
Try to delete "sd-webui-reactor" extension folder and insightface folder (inside `venv\lib\site-packages`) and reinstall ReActor - if it doesn't help, try a clean installation of sd-webui
Smth wrong with dependencies
I've never gotten errors like these
Log says that Insightface library doesn't work
It might be corrupted or other dependencies (which Insightface works with) are corrupted

**Comment by lotnick** [comment]
Thank you, I'll try!

**Comment by lotnick** [comment]
New problems... I'll try a clean installation:

Error loading script: console_log_patch.py
Traceback (most recent call last):
  File "C:\Users\lotni\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\lotni\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\lotni\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 4, in <module>
    import insightface
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\app\mask_renderer.py", line 4, in <module>
    import albumentations as A
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\__init__.py", line 5, in <module>
    from .augmentations import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\__init__.py", line 8, in <module>
    from .domain_adaptation import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\domain_adaptation.py", line 6, in <module>
    from qudida import DomainAdapter
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\qudida\__init__.py", line 6, in <module>
    from sklearn.decomposition import PCA
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\__init__.py", line 83, in <module>
    from .base import clone
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\base.py", line 19, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\utils\__init__.py", line 22, in <module>
    from ._param_validation import Interval, validate_params
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 15, in <module>
    from .validation import _is_arraylike_not_scalar
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\utils\validation.py", line 28, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\utils\_array_api.py", line 9, in <module>
    from .fixes import parse_version
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\utils\fixes.py", line 19, in <module>
    import threadpoolctl
ModuleNotFoundError: No module named 'threadpoolctl'

Error loading script: faceswap.py
Traceback (most recent call last):
  File "C:\Users\lotni\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\lotni\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\lotni\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\faceswap.py", line 16, in <module>
    from scripts.swapper import UpscaleOptions, swap_face, check_process_halt, reset_messaged
  File "C:\Users\lotni\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\swapper.py", line 10, in <module>
    import insightface
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\app\mask_renderer.py", line 4, in <module>
    import albumentations as A
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\__init__.py", line 5, in <module>
    from .augmentations import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\__init__.py", line 8, in <module>
    from .domain_adaptation import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\domain_adaptation.py", line 6, in <module>
    from qudida import DomainAdapter
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\qudida\__init__.py", line 6, in <module>
    from sklearn.decomposition import PCA
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\__init__.py", line 83, in <module>
    from .base import clone
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\base.py", line 19, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\utils\__init__.py", line 22, in <module>
    from ._param_validation import Interval, validate_params
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 15, in <module>
    from .validation import _is_arraylike_not_scalar
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\utils\validation.py", line 28, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\utils\_array_api.py", line 9, in <module>
    from .fixes import parse_version
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\utils\fixes.py", line 19, in <module>
    import threadpoolctl
ModuleNotFoundError: No module named 'threadpoolctl'

Error loading script: reactor_api.py
Traceback (most recent call last):
  File "C:\Users\lotni\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\lotni\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\lotni\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_api.py", line 17, in <module>
    from scripts.swapper import UpscaleOptions, swap_face
  File "C:\Users\lotni\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\swapper.py", line 10, in <module>
    import insightface
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\app\mask_renderer.py", line 4, in <module>
    import albumentations as A
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\__init__.py", line 5, in <module>
    from .augmentations import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\__init__.py", line 8, in <module>
    from .domain_adaptation import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\domain_adaptation.py", line 6, in <module>
    from qudida import DomainAdapter
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\qudida\__init__.py", line 6, in <module>
    from sklearn.decomposition import PCA
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\__init__.py", line 83, in <module>
    from .base import clone
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\base.py", line 19, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\utils\__init__.py", line 22, in <module>
    from ._param_validation import Interval, validate_params
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 15, in <module>
    from .validation import _is_arraylike_not_scalar
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\utils\validation.py", line 28, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\utils\_array_api.py", line 9, in <module>
    from .fixes import parse_version
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\utils\fixes.py", line 19, in <module>
    import threadpoolctl
ModuleNotFoundError: No module named 'threadpoolctl'

Error loading script: swapper.py
Traceback (most recent call last):
  File "C:\Users\lotni\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\Users\lotni\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\lotni\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\swapper.py", line 10, in <module>
    import insightface
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\insightface\app\mask_renderer.py", line 4, in <module>
    import albumentations as A
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\__init__.py", line 5, in <module>
    from .augmentations import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\__init__.py", line 8, in <module>
    from .domain_adaptation import *
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\albumentations\augmentations\domain_adaptation.py", line 6, in <module>
    from qudida import DomainAdapter
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\qudida\__init__.py", line 6, in <module>
    from sklearn.decomposition import PCA
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\__init__.py", line 83, in <module>
    from .base import clone
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\base.py", line 19, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\utils\__init__.py", line 22, in <module>
    from ._param_validation import Interval, validate_params
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\utils\_param_validation.py", line 15, in <module>
    from .validation import _is_arraylike_not_scalar
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\utils\validation.py", line 28, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\utils\_array_api.py", line 9, in <module>
    from .fixes import parse_version
  File "C:\Users\lotni\stable-diffusion-webui\venv\lib\site-packages\sklearn\utils\fixes.py", line 19, in <module>
    import threadpoolctl
ModuleNotFoundError: No module named 'threadpoolctl'

**Comment by Gourieff** [comment]
I think you do smth wrong when installing sd-webui 🤷‍♂️ I've never encountered errors like you got neither with A1111/SD.Next nor even with Google Colab sd-webui notebooks
The current version of ReActor is quite stable and friendly to different sd web-uis

Do you follow all the installation steps recommended by A1111 team or Vladmandic?

You can try the pre-installed version of A1111: https://github.com/AUTOMATIC1111/stable-diffusion-webui/#installation-on-windows-1011-with-nvidia-gpus-using-release-package
And you can install the Insightface package for this version as described here: https://github.com/Gourieff/sd-webui-reactor/issues/72#issuecomment-1698043261

**Comment by lotnick** [comment]
I use Python 3.10.6. I'll'try the pre-installed version. Thank you!
