### ISSUE TITLE
File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\faceswap.py", line 23, in <module>         from scripts.helpers import make_grid     ImportError: cannot import name 'make_grid' from 'scripts.helpers' (M:\SD\git\sdxlwebui\extensions\sd-webui-fabric\scripts\helpers.py)

### ISSUE THREAD

**Issue by swumagic** [Gourieff/sd-webui-reactor#79]
*** Error loading script: faceswap.py
    Traceback (most recent call last):
      File "M:\SD\git\sdxlwebui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "M:\SD\git\sdxlwebui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "M:\SD\git\sdxlwebui\extensions\sd-webui-roop-nsfw\scripts\faceswap.py", line 23, in <module>
        from scripts.helpers import make_grid
    ImportError: cannot import name 'make_grid' from 'scripts.helpers' (M:\SD\git\sdxlwebui\extensions\sd-webui-fabric\scripts\helpers.py)

**Comment by Gourieff** [comment]
For some reasons Python is trying to import make_grid from "sd-webui-fabric\scripts\helpers.py" but not from ReActor folder 🤔

**Comment by Gourieff** [comment]
I will change the name of the helpers file to more unique one

**Comment by Gourieff** [comment]
Fixed https://github.com/Gourieff/sd-webui-reactor/commit/9a86140cf2d836291b4769e4bfab16e5846cdc22

**Comment by swumagic** [comment]
TK you!
