### ISSUE TITLE
Tried all install versions for Automatic1111 -  Visual Studio Installed

### ISSUE THREAD

**Issue by stasha17** [Gourieff/sd-webui-reactor#85]
Thanks for your work.  I was using Reactor for many weeks and then I did a total delete of Stable-Diffusion-webui folder and reinstalled from scratch.  Since then, I have not been able to use Reactor.  I have tried many times to reinstall from the URL, tried step VII as well by downloading insightface-0.7.3, etc.  I also tried downloading buffalo.zip and copy pasting the files.  Nothing seems to work.  

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Checking ReActor requirements... Ok
Launching Web UI with arguments: --no-half-vae --medvram
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
14:03:37 - ReActor - STATUS - Running v0.4.1
Loading weights [31e35c80fc] from C:\Users\WIN11\stable-diffusion-webui\models\Stable-diffusion\sd_xl_base_1.0.safetensors
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 6.7s (prepare environment: 1.6s, import torch: 1.8s, import gradio: 0.5s, setup paths: 0.4s, initialize shared: 0.2s, other imports: 0.4s, load scripts: 1.1s, create ui: 0.3s, gradio launch: 0.3s).
Creating model from config: C:\Users\WIN11\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
Applying attention optimization: Doggettx... done.

**ERROR text**

14:04:19 - ReActor - STATUS - Working: source face index [0], target face index [0]████| 20/20 [00:07<00:00,  2.62it/s]
*** Error running postprocess_image: C:\Users\WIN11\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\Users\WIN11\stable-diffusion-webui\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\Users\WIN11\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 346, in postprocess_image
        result = swap_face(
      File "C:\Users\WIN11\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 260, in swap_face
        face_swapper = getFaceSwapModel(model)
      File "C:\Users\WIN11\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 100, in getFaceSwapModel
        FS_MODEL = insightface.model_zoo.get_model(model_path, providers=providers)
      File "C:\Users\WIN11\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
        model = router.get_model(providers=providers, provider_options=provider_options)
      File "C:\Users\WIN11\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\console_log_patch.py", line 21, in patched_get_model
        session = PickableInferenceSession(self.onnx_file, **kwargs)
      File "C:\Users\WIN11\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "C:\Users\WIN11\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "C:\Users\WIN11\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
        sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\WIN11\stable-diffusion-webui\models\insightface\inswapper_128.onnx failed:Protobuf parsing failed.

**Comment by Gourieff** [comment]
Smth wrong with the inswapper model file
Please try this solution https://github.com/Gourieff/sd-webui-reactor#v-invalid_protobuf--load-model-from-modelsinsightfaceinswapper_128onnx-failedprotobuf-parsing-failed

**Comment by stasha17** [comment]
> Smth wrong with the inswapper model file Please try this solution https://github.com/Gourieff/sd-webui-reactor#v-invalid_protobuf--load-model-from-modelsinsightfaceinswapper_128onnx-failedprotobuf-parsing-failed

Thank you, this works now.

**Comment by stasha17** [comment]
issue closed
