### ISSUE TITLE
[SOLVED] AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by maxHadrome** [Gourieff/sd-webui-reactor#86]
receive following, can anyone help?

*** Error running postprocess: C:\Stable Diffusion\a1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\Stable Diffusion\a1111\stable-diffusion-webui\modules\scripts.py", line 651, in postprocess
        script.postprocess(p, processed, *script_args)
      File "C:\Stable Diffusion\a1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 299, in postprocess
        result = swap_face(
      File "C:\Stable Diffusion\a1111\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 274, in swap_face
        result = face_swapper.get(result, target_face, source_face)
    AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Gourieff** [comment]
The most common thing about such errors is the corrupted inswapper model file
So, try this solution: https://github.com/Gourieff/sd-webui-reactor#v-invalid_protobuf--load-model-from-modelsinsightfaceinswapper_128onnx-failedprotobuf-parsing-failed

**Comment by maxHadrome** [comment]
Thank you, could solve the issue
