### ISSUE TITLE
SD 1.6 after updated latest version still not function and got error

### ISSUE THREAD

**Issue by n714** [Gourieff/sd-webui-reactor#96]
15:28:43 - ReActor - STATUS - Working: source face index [0], target face index [0]████| 20/20 [00:13<00:00,  1.42it/s]
15:28:43 - ReActor - STATUS - Detecting Source Face, Index = 0
*** Error running postprocess_image: C:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 675, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_faceswap.py", line 360, in postprocess_image
        result, output, swapped = swap_face(
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 279, in swap_face        source_face, wrong_gender, source_age, source_gender = get_face_single(source_img, face_index=source_faces_index[0], gender_source=gender_source)
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\scripts\reactor_swapper.py", line 198, in get_face_single
        face_analyser = copy.deepcopy(getAnalysisModel())
      File "C:\Users\nelson\AppData\Local\Programs\Python\Python310\lib\copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "C:\Users\nelson\AppData\Local\Programs\Python\Python310\lib\copy.py", line 271, in _reconstruct
        state = deepcopy(state, memo)
      File "C:\Users\nelson\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "C:\Users\nelson\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "C:\Users\nelson\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "C:\Users\nelson\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "C:\Users\nelson\AppData\Local\Programs\Python\Python310\lib\copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "C:\Users\nelson\AppData\Local\Programs\Python\Python310\lib\copy.py", line 271, in _reconstruct
        state = deepcopy(state, memo)
      File "C:\Users\nelson\AppData\Local\Programs\Python\Python310\lib\copy.py", line 146, in deepcopy
        y = copier(x, memo)
      File "C:\Users\nelson\AppData\Local\Programs\Python\Python310\lib\copy.py", line 231, in _deepcopy_dict
        y[deepcopy(key, memo)] = deepcopy(value, memo)
      File "C:\Users\nelson\AppData\Local\Programs\Python\Python310\lib\copy.py", line 172, in deepcopy
        y = _reconstruct(x, memo, *rv)
      File "C:\Users\nelson\AppData\Local\Programs\Python\Python310\lib\copy.py", line 273, in _reconstruct
        y.__setstate__(state)
      File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 33, in __setstate__
        self.__init__(model_path)
      File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 396, in __init__
        raise e
      File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 415, in _create_inference_session
        raise ValueError(
    ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

**Comment by Gourieff** [comment]
You have a wrong version of ORT
Please read https://github.com/Gourieff/sd-webui-reactor#vi-valueerror-this-ort-build-has-tensorrtexecutionprovider-cudaexecutionprovider-cpuexecutionprovider-enabled

**Comment by n714** [comment]
numba                        0.57.1
numpy                        1.24.3
nvidia-pyindex               1.0.9
oauthlib                     3.2.2
omegaconf                    2.3.0
onnx                         1.14.0
onnxruntime                  1.15.0
openai-whisper               20230314
opencv-python                4.8.0.74
opencv-python-headless       4.8.0.74
opennsfw2                    0.10.2
opt-einsum                   3.3.0
orjson                       3.9.5
packaging                    23.1
pandas                       2.1.0
pefile                       2022.5.30
phonemizer                   3.2.0
Pillow                       10.0.0
pip                          23.2.1
platformdirs                 3.10.0
portalocker                  2.7.0
prettytable                  3.8.0
proces                       0.1.6
protobuf                     3.20.3
psutil                       5.9.5
pyasn1                       0.5.0
pyasn1-modules               0.3.0
pycparser                    2.21
pydantic                     2.3.0


Still the same error

**Comment by Gourieff** [comment]
This error `ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled` means that you have ORT-GPU installed but not ORT
Some other extension calls "ort-gpu" to be installed when you start sd-webui

**Comment by Gourieff** [comment]
Try to disable other extension which have onnxruntime-gpu in requirements and then reinstall onnxruntime

**Comment by n714** [comment]
i just tried disable all extensions, only load Reactor, the error still come up, still the same.

**Comment by Gourieff** [comment]
Check the `site-packages` directory for folders with names start from ~, delete them
After that you need to delete both onnxruntime-gpu and onnxruntime, and install onnxruntime once again (inside the activated VENV and closed sd-webui)
Please read the Issue section, this problem has been discussed many times
I'm tired of writing the same things over and over again, just because some people don't want to carefully read the documentation and the Issues section
https://github.com/Gourieff/sd-webui-reactor/issues?q=is%3Aissue+is%3Aclosed+onnxruntime-gpu
This error appears ONLY if you have onnxruntime-gpu installed inside the venv `site-packages` directory but app wants onnxruntime - no other reasons
Please make sure you install ORT inside the sd-webui's VENV folder, but not in your OS
If you do everything according to the instructions, then this extension will work perfectly and with no errors
If you don't succeed at all - delete the venv folder and let your sd-webui build it from the scratch
